<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="xunit.v3" />
		<ProjectReference Include="../../src/DotGram.Finance/DotGram.Finance.csproj" />
		<ProjectReference Include="../../examples/DotGram.Examples/DotGram.Examples.csproj" />
		<None Include="Fixtures.json" CopyToOutputDirectory="PreserveNewest" />
		<None Include="../../src/DotGram.Finance/Fix/Specification/OrchestraFIX44.xml" Link="OrchestraFIX44.xml" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>
