<Project>

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Deterministic>true</Deterministic>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
	</PropertyGroup>

	<PropertyGroup>
		<Product>.Gram</Product>
		<Company>DotGram</Company>
		<Version>0.1.0-alpha</Version>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/dotgram/dotgram</RepositoryUrl>
	</PropertyGroup>

</Project>
