using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

using DotGram.Finance.Fix;

namespace DotGram.Finance.Generator;

/// <summary>
/// Writes a dictionary out as validation code: a method per message type, per component and per
/// repeating group, and a validator holding them.
/// </summary>
/// <remarks>
/// <para>
/// D74's shape. A component gets a method of its own, called, rather than being expanded into
/// every message that names it: expanding costs 2.16× the code and, measured on a 391-field
/// message, buys nothing.
/// </para>
/// <para>
/// <strong>Membership cannot be shared, and that is a property of the problem.</strong> A
/// component's method is called on a scope its caller is already walking, so it must not walk it
/// again; what it carries is the required checks, read off the caller's mask, and the groups it
/// holds. Every tag of every component a scope names is therefore a case of that scope's own
/// switch. The saving is in the required checks, the group bodies and the method count.
/// </para>
/// <para>
/// Everything emitted calls the package's public surface and nothing reimplements it. A value is
/// held to its type by <c>FixValues.Valid</c>, the one implementation, because a second copy of
/// those rules is a second thing to disagree with the first — and three quarters of what they cost
/// is reading the characters of the value, which no amount of emitting removes.
/// </para>
/// </remarks>
static class Emitter
{
	public static string Rules(string space, string name, string accessibility, FixDictionary dictionary)
	{
		var w = new Writer(dictionary);

		w.Head(space, name, accessibility);

		var types = dictionary.MessageTypes.OrderBy(t => t, StringComparer.Ordinal).ToArray();

		foreach (var type in types)
			w.Scope("M_" + Mangled(type), dictionary.Message(type), type, group: false);

		w.Scope("H_header", dictionary.Header, "the header", group: false);
		w.Scope("T_trailer", dictionary.Trailer, "the trailer", group: false);

		foreach (var type in types)
			w.Whole("R_" + Mangled(type), "M_" + Mangled(type));

		w.Table(types.Select(type => (type, "R_" + Mangled(type))).ToArray());
		w.Sets();
		w.Tail();

		return w.ToString();
	}

	// A method name from a MsgType, which may be "D", "AB" or "n" and may differ from another only
	// by case: the octets in hexadecimal are unique and are a C# identifier whatever the type is.
	static string Mangled(string type) =>
		string.Concat(type.Select(c => ((int)c).ToString("x2", CultureInfo.InvariantCulture)));

	sealed class Writer(FixDictionary dictionary)
	{
		readonly StringBuilder   text    = new();
		readonly HashSet<string> written = [];
		readonly SortedSet<int>  sets    = [];

		public override string ToString() => text.ToString();

		public void Head(string space, string name, string accessibility)
		{
			text.AppendLine("// <auto-generated/>");
			text.AppendLine("// Written from a FIX dictionary by DotGram.Finance.Generator. Do not edit.");
			text.AppendLine("#nullable enable");
			text.AppendLine();
			text.AppendLine("using global::System;");
			text.AppendLine("using global::System.Collections.Generic;");
			text.AppendLine();
			text.AppendLine("using global::DotGram.Finance.Fix;");
			text.AppendLine();

			if (space.Length != 0)
			{
				text.Append("namespace ").Append(space).AppendLine(";");
				text.AppendLine();
			}

			text.Append(accessibility).Append(" static partial class ").AppendLine(name);
			text.AppendLine("{");
			text.AppendLine("\tstatic bool Seen(ReadOnlySpan<ulong> seen, int tag) => tag is > 0 and < 957 && (seen[tag >> 6] & 1UL << (tag & 63)) != 0;");
			text.AppendLine();
			text.AppendLine("\tstatic void Mark(Span<ulong> seen, int tag) { if (tag is > 0 and < 957) seen[tag >> 6] |= 1UL << (tag & 63); }");
			text.AppendLine();
		}

		public void Tail() => text.AppendLine("}");

		/// <summary>One scope: a message's body, the header, the trailer, or a group's entry.</summary>
		public void Scope(string name, SchemaRef[] schema, string where, bool group)
		{
			if (!written.Add(name))
				return;

			var members = new Members(dictionary, schema);

			foreach (var part in members.Parts)
				Component(part.Name, dictionary.Component(part.Id), where);

			foreach (var one in members.Groups)
				Scope(one.Call, dictionary.Group(one.Id), where, group: true);

			var body = new StringBuilder();

			body.Append("\tstatic void ").Append(name)
				.AppendLine("(FixFieldSet scope, FixScope area, int groupTag, int entry, List<FixFinding> found)");
			body.AppendLine("\t{");
			body.AppendLine("\t\tSpan<ulong> seen = stackalloc ulong[15];");

			if (group)
				body.AppendLine("\t\tvar rank = -1;");

			body.AppendLine();
			body.AppendLine("\t\tforeach (var field in scope.Fields)");
			body.AppendLine("\t\t{");
			body.AppendLine("\t\t\tvar tag = field.Tag;");
			body.AppendLine();
			body.AppendLine("\t\t\tswitch (tag)");
			body.AppendLine("\t\t\t{");

			foreach (var tag in members.Tags)
			{
				body.Append("\t\t\t\tcase ").Append(tag).AppendLine(":");

				if (group && members.Rank.TryGetValue(tag, out var rank))
				{
					body.Append("\t\t\t\t\tif (").Append(rank).AppendLine(" < rank)");
					body.AppendLine("\t\t\t\t\t\tfound.Add(new FixFinding(FixRule.FieldOutOfOrder, area, tag, groupTag, entry, field.ValuePosition,");
					body.AppendLine("\t\t\t\t\t\t\t\"The fields of a group entry are not in the order the schema gives them.\"));");
					body.AppendLine("\t\t\t\t\telse");
					body.Append("\t\t\t\t\t\trank = ").Append(rank).AppendLine(";");
					body.AppendLine();
				}

				var type = FixVocabulary.Of(dictionary.CodeType(tag));

				if (type != FixValueType.None)
				{
					var codes = dictionary.CodeArray(tag);

					if (codes != null)
						sets.Add(tag);

					body.Append("\t\t\t\t\tif (!FixValues.Valid(field, FixValueType.").Append(type)
						.Append(", ").Append(codes == null ? "null" : "S" + tag).AppendLine("))");
					body.AppendLine("\t\t\t\t\t\tfound.Add(new FixFinding(FixRule.InvalidValue, area, tag, groupTag, entry, field.ValuePosition,");
					body.AppendLine("\t\t\t\t\t\t\t\"The value does not fit the field's type, or is not one of its code set.\"));");
					body.AppendLine();
				}

				body.AppendLine("\t\t\t\t\tbreak;");
				body.AppendLine();
			}

			// The same two sentences the walk uses, and told apart the same way. Two roads over one
			// dictionary answering in different words is a difference a reader would see and could
			// not explain, so the wording is part of what has to agree.
			body.AppendLine("\t\t\t\tdefault:");
			body.AppendLine("\t\t\t\t\tfound.Add(new FixFinding(FixRule.FieldNotInScope, area, tag, groupTag, entry, field.ValuePosition,");
			body.AppendLine("\t\t\t\t\t\tDefines(tag)");
			body.AppendLine("\t\t\t\t\t\t\t? \"The schema defines this tag, but not in this scope.\"");
			body.AppendLine("\t\t\t\t\t\t\t: \"The schema defines no such tag.\"));");
			body.AppendLine();
			body.AppendLine("\t\t\t\t\tbreak;");
			body.AppendLine("\t\t\t}");
			body.AppendLine();
			body.AppendLine("\t\t\tif (Seen(seen, tag))");
			body.AppendLine("\t\t\t\tfound.Add(new FixFinding(FixRule.DuplicateField, area, tag, groupTag, entry, field.ValuePosition,");
			body.AppendLine("\t\t\t\t\t\"The tag appears more than once in this scope.\"));");
			body.AppendLine();
			body.AppendLine("\t\t\tMark(seen, tag);");
			body.AppendLine("\t\t}");
			body.AppendLine();

			Calls(body, members, "\t\t");

			body.AppendLine("\t}");
			body.AppendLine();

			text.Append(body);
		}

		/// <summary>
		/// A component: the required checks its caller cannot make, and the groups it holds.
		/// </summary>
		void Component(string name, SchemaRef[] schema, string where)
		{
			if (!written.Add(name))
				return;

			var members = new Members(dictionary, schema);

			foreach (var part in members.Parts)
				Component(part.Name, dictionary.Component(part.Id), where);

			foreach (var one in members.Groups)
				Scope(one.Call, dictionary.Group(one.Id), where, group: true);

			var body = new StringBuilder();

			body.Append("\tstatic void ").Append(name)
				.AppendLine("(FixFieldSet scope, FixScope area, int groupTag, int entry, ReadOnlySpan<ulong> seen, List<FixFinding> found)");
			body.AppendLine("\t{");

			Calls(body, members, "\t\t");

			body.AppendLine("\t}");
			body.AppendLine();

			text.Append(body);
		}

		// In the schema's own order, interleaved as the walk does it, so that the two roads report
		// the same findings in the same sequence and not merely the same set.
		void Calls(StringBuilder body, Members members, string pad)
		{
			foreach (var step in members.Steps)
			{
				if (step.Part is { } part)
				{
					body.Append(pad).Append("if (").Append(part.Any).AppendLine(")");
					body.Append(pad).Append('\t').Append(part.Name).AppendLine("(scope, area, groupTag, entry, seen, found);");

					if (part.Required)
					{
						body.Append(pad).AppendLine("else");
						body.Append(pad).AppendLine("\tfound.Add(new FixFinding(FixRule.RequiredComponentMissing, area, null, groupTag, entry, 0,");
						body.Append(pad).Append("\t\t\"A component the schema requires has none of its fields; its first is tag ")
							.Append(part.First).AppendLine(".\"));");
					}

					body.AppendLine();

					continue;
				}

				body.Append(pad).Append("if (!Seen(seen, ").Append(step.Tag).AppendLine("))");
				body.Append(pad).AppendLine("{");

				if (step.Required)
				{
					body.Append(pad).Append("\tfound.Add(new FixFinding(FixRule.RequiredFieldMissing, area, ").Append(step.Tag)
						.AppendLine(", groupTag, entry, 0,");
					body.Append(pad).AppendLine("\t\t\"The schema requires this tag in this scope.\"));");
				}
				else
				{
					body.Append(pad).AppendLine("\t// nothing: the schema does not require it");
				}

				body.Append(pad).AppendLine("}");

				if (step.Group is not { } one)
				{
					body.AppendLine();

					continue;
				}

				body.Append(pad).AppendLine("else");
				body.Append(pad).AppendLine("{");
				body.Append(pad).Append("\tvar g = scope.GetGroup(").Append(one.Counter).AppendLine(");");
				body.Append(pad).Append("\tvar c = scope.GetField(").Append(one.Counter).AppendLine(")!.Value;");
				body.AppendLine();
				body.Append(pad).AppendLine("\tif (!c.TryGetInt64(out var n) || n != g.Count || n < 0)");
				body.Append(pad).Append("\t\tfound.Add(new FixFinding(FixRule.GroupCountMismatch, area, ").Append(one.Counter)
					.AppendLine(", groupTag, entry, c.ValuePosition,");
				body.Append(pad).AppendLine("\t\t\t$\"The count says {c} and {g.Count} entries follow.\"));");
				body.AppendLine();
				body.Append(pad).AppendLine("\tfor (var e = 0; e < g.Count; e++)");
				body.Append(pad).Append("\t\t").Append(one.Call).Append("(g[e], area, ").Append(one.Counter).AppendLine(", e, found);");
				body.Append(pad).AppendLine("}");
				body.AppendLine();
			}
		}

		/// <summary>A message type end to end: the header, its body, the trailer, and the encoding rule.</summary>
		public void Whole(string name, string body)
		{
			text.Append("\tstatic void ").Append(name).AppendLine("(FixMessage message, List<FixFinding> found)");
			text.AppendLine("\t{");
			text.AppendLine("\t\tif (message.Header.GetField(347) == null && (Encoded(message.Header) || Encoded(message)))");
			text.AppendLine("\t\t\tfound.Add(new FixFinding(FixRule.MessageEncodingMissing, FixScope.Header, 347, 0, -1, 0,");
			text.AppendLine("\t\t\t\t\"MessageEncoding is required where an Encoded field is present.\"));");
			text.AppendLine();
			text.AppendLine("\t\tH_header(message.Header, FixScope.Header, 0, -1, found);");
			text.Append("\t\t").Append(body).AppendLine("(message, FixScope.Body, 0, -1, found);");
			text.AppendLine("\t\tT_trailer(message.Trailer, FixScope.Trailer, 0, -1, found);");
			text.AppendLine("\t}");
			text.AppendLine();
		}

		public void Table((string Type, string Call)[] entries)
		{
			// Which tags oblige a MessageEncoding, read off THIS dictionary rather than asked of
			// the standard's tables: they are the data halves of the Encoded pairs, and a venue's
			// file should answer for a venue's fields. For FIX 4.4 the set is the standard's, and
			// the test holding the generated rules to the compiled ones is what says so.
			var encoded = dictionary.Tags
				.Where(tag => dictionary.Name(tag)?.StartsWith("Encoded", StringComparison.Ordinal) == true)
				.Where(tag => FixVocabulary.Of(dictionary.CodeType(tag)) == FixValueType.Data)
				.OrderBy(tag => tag)
				.ToArray();

			// Every tag the dictionary declares, so that a field out of place is told from a field
			// nobody has heard of — which is the difference between "you put it in the wrong scope"
			// and "this tag does not exist", and the reader needs to know which.
			text.Append("\tstatic bool Defines(int tag) => ");
			text.AppendLine("tag is " + string.Join(" or ", dictionary.Tags.OrderBy(t => t)) + ";");
			text.AppendLine();

			text.Append("\tstatic bool Requires(int tag) => ");
			text.AppendLine(encoded.Length == 0
				? "false;"
				: "tag is " + string.Join(" or ", encoded) + ";");
			text.AppendLine();

			text.AppendLine("\tstatic bool Encoded(FixFieldSet scope)");
			text.AppendLine("\t{");
			text.AppendLine("\t\tforeach (var field in scope.Fields)");
			text.AppendLine("\t\t{");
			text.AppendLine("\t\t\tif (Requires(field.Tag))");
			text.AppendLine("\t\t\t\treturn true;");
			text.AppendLine();
			text.AppendLine("\t\t\tforeach (var entry in scope.GetGroup(field.Tag))");
			text.AppendLine("\t\t\t\tif (Encoded(entry))");
			text.AppendLine("\t\t\t\t\treturn true;");
			text.AppendLine("\t\t}");
			text.AppendLine();
			text.AppendLine("\t\treturn false;");
			text.AppendLine("\t}");
			text.AppendLine();

			text.AppendLine("\t/// <summary>A rule for every message type the dictionary describes, by MsgType.</summary>");
			text.AppendLine("\t/// <remarks>Beside the validator for a reader who wants two dictionaries in one.</remarks>");
			text.AppendLine("\tpublic static IReadOnlyDictionary<string, FixMessageRule> Entries { get; } =");
			text.AppendLine("\t\tnew Dictionary<string, FixMessageRule>(StringComparer.Ordinal)");
			text.AppendLine("\t\t{");

			foreach (var (type, call) in entries)
				text.Append("\t\t\t[\"").Append(type).Append("\"] = ").Append(call).AppendLine(",");

			text.AppendLine("\t\t};");
			text.AppendLine();
			text.AppendLine("\t/// <summary>A validator holding this dictionary's rules, ready to be asked.</summary>");
			text.AppendLine("\tpublic static FixValidator Validator { get; } = Build();");
			text.AppendLine();
			text.AppendLine("\tstatic FixValidator Build()");
			text.AppendLine("\t{");
			text.AppendLine("\t\tvar validator = new FixValidator();");
			text.AppendLine();
			text.AppendLine("\t\tvalidator.Load(Entries);");
			text.AppendLine();
			text.AppendLine("\t\treturn validator;");
			text.AppendLine("\t}");
			text.AppendLine();
		}

		/// <summary>The code sets, as the dictionary gives them, once each.</summary>
		public void Sets()
		{
			foreach (var tag in sets)
			{
				var codes = dictionary.CodeArray(tag)!;

				text.Append("\tstatic readonly string[] S").Append(tag).Append(" = [");

				for (var i = 0; i < codes.Length; i++)
				{
					if (i != 0)
						text.Append(", ");

					text.Append('"').Append(codes[i].Replace("\\", "\\\\").Replace("\"", "\\\"")).Append('"');
				}

				text.AppendLine("];");
			}

			text.AppendLine();
		}

	}

	/// <summary>What one scope holds, flattened the way form B needs it.</summary>
	sealed class Members
	{
		public readonly List<int>  Tags  = [];
		public readonly List<Step> Steps = [];
		public readonly Dictionary<int, int> Rank = [];

		/// <summary>The components and groups, for writing their methods before this one.</summary>
		public IEnumerable<Part>  Parts  => Steps.Select(step => step.Part).Where(part => part is not null)!;
		public IEnumerable<Group> Groups => Steps.Select(step => step.Group).Where(one => one is not null)!;

		public Members(FixDictionary dictionary, SchemaRef[] schema)
		{
			Flatten(dictionary, schema);

			var ordinal = 0;

			Order(dictionary, schema, ref ordinal);

			Tags = Tags.Distinct().OrderBy(t => t).ToList();
		}

		void Flatten(FixDictionary dictionary, SchemaRef[] schema)
		{
			foreach (var reference in schema)
			{
				if (reference.Kind == 1)
				{
					var own = new List<int>();

					Collect(dictionary, dictionary.Component(reference.Id), own);
					Tags.AddRange(own);

					var any = own.Count == 0
						? "false"
						: string.Join(" || ", own.Distinct().OrderBy(t => t).Select(t => "Seen(seen, " + t + ")"));

					Steps.Add(new Step(new Part("C_" + reference.Id, reference.Id, any, own.Count == 0 ? 0 : own[0], reference.Required), null, 0, false));

					continue;
				}

				var tag = reference.Kind == 2 ? dictionary.Counter(reference.Id) : reference.Id;

				Tags.Add(tag);

				Steps.Add(new Step(
					null,
					reference.Kind == 2 ? new Group(tag, "G_" + reference.Id, reference.Id) : null,
					tag,
					reference.Required));
			}
		}

		static void Collect(FixDictionary dictionary, SchemaRef[] schema, List<int> into)
		{
			foreach (var reference in schema)
				if (reference.Kind == 1)
					Collect(dictionary, dictionary.Component(reference.Id), into);
				else
					into.Add(reference.Kind == 2 ? dictionary.Counter(reference.Id) : reference.Id);
		}

		void Order(FixDictionary dictionary, SchemaRef[] schema, ref int ordinal)
		{
			foreach (var reference in schema)
			{
				if (reference.Kind == 1)
				{
					Order(dictionary, dictionary.Component(reference.Id), ref ordinal);

					continue;
				}

				var tag = reference.Kind == 2 ? dictionary.Counter(reference.Id) : reference.Id;

				if (!Rank.ContainsKey(tag))
					Rank.Add(tag, ordinal);

				ordinal++;
			}
		}
	}

	/// <summary>
	/// One reference of a scope, in the order the schema writes it.
	/// </summary>
	/// <remarks>
	/// In ORDER, and that is the point. The walk reports as it reads the schema — a required field
	/// missing, a component's own findings, a group's entries — interleaved exactly as the members
	/// are written. Emitting all the required checks, then all the components, then all the groups
	/// gives the same findings in a different sequence, which two roads over one dictionary must
	/// not do. It was found by printing both answers for one message, not by the test that was
	/// meant to catch it: that one had been narrowed to compare sets.
	/// </remarks>
	sealed class Step(Part? part, Group? group, int tag, bool required)
	{
		public readonly Part?  Part     = part;
		public readonly Group? Group    = group;
		public readonly int    Tag      = tag;
		public readonly bool   Required = required;
	}

	sealed class Part(string name, int id, string any, int first, bool required)
	{
		public readonly string Name     = name;
		public readonly int    Id       = id;
		public readonly string Any      = any;
		public readonly int    First    = first;
		public readonly bool   Required = required;
	}

	sealed class Group(int counter, string call, int id)
	{
		public readonly int    Counter = counter;
		public readonly string Call    = call;
		public readonly int    Id      = id;
	}
}
