# Writes PermissionCatalogue.cs: what permission may be written of what securable class.
#
#     python src/DotGram.Sql/TransactSql/permissions.py
#
# The pairs come from the SERVER, and are then held to the PARSER one statement at a time, which is
# not the same list:
#
#     SELECT class_desc, permission_name FROM sys.fn_builtin_permissions(DEFAULT)
#
# gives 301 rows over 29 classes, and `GRANT CONTROL ON CREDENTIAL::x TO u` is `Incorrect syntax near
# 'CREDENTIAL'`. So CREDENTIAL is a class the view lists and the parser will not take, its two pairs
# can never be reached, and the catalogue holds 299. A class the view omits is not one either: TABLE,
# VIEW, PROCEDURE, SEQUENCE, COLUMN MASTER KEY, EXTERNAL DATA SOURCE and six more were asked and all
# refused, all of them being OBJECT.
#
# Why the tree needs this at all: with an ON clause the engine checks the permission against the
# class WHILE PARSING and answers 102 -- `GRANT SELECT ON ENDPOINT::x` is `Incorrect syntax near
# 'SELECT'`, SELECT being none of ENDPOINT's five. Without an ON clause it does not: mixed scopes are
# Msg 4620 at level 16, after the parse, and the server's business rather than this grammar's.
#
# ALL, ALL PRIVILEGES and EXEC are in no row of the view and are read of every class, so they are
# written in by hand here, as `PermissionName` in the grammar does with them.
#
# Run it against a server whose version the grammar is written for, and read the diff: a permission or
# a class that a release adds appears here, and the grammar's own PermissionName and SecurableClassName
# want the same addition. Nothing reads this table at run time except the parser's guard.

import subprocess
import sys

SQLCMD = r'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\180\Tools\Binn\sqlcmd.exe'
SERVER = 'localhost'
OUTPUT = 'src/DotGram.Sql/TransactSql/PermissionCatalogue.cs'

# The class the view lists and the parser refuses. Asked, not assumed: see the header.
UNREACHABLE = {'CREDENTIAL'}

CR = '\r\n'


def asked(query):
    done = subprocess.run(
        [SQLCMD, '-S', SERVER, '-E', '-d', 'master', '-C', '-l', '5', '-h', '-1', '-W', '-s', '|',
         '-Q', 'SET NOCOUNT ON; ' + query],
        capture_output=True, text=True, timeout=120)

    if done.returncode != 0:
        sys.exit('the server would not answer: ' + (done.stderr or done.stdout))

    return [line.strip() for line in done.stdout.splitlines() if '|' in line]


def pairs():
    rows = asked('SELECT class_desc, permission_name FROM sys.fn_builtin_permissions(DEFAULT) '
                 'ORDER BY class_desc, permission_name;')
    named = []

    for row in rows:
        klass, permission = (one.strip().upper() for one in row.split('|', 1))

        if klass not in UNREACHABLE:
            named.append((klass, permission))

    return named


def written(named):
    rows = CR.join('\t\t"%s|%s",' % pair for pair in sorted(named))

    return HEAD.replace('@ROWS@', rows).replace('@COUNT@', str(len(named))).replace('\n', CR)


HEAD = '''// <auto-generated/>
#nullable enable

// Written by src/DotGram.Sql/TransactSql/permissions.py from the server's own answers. Do not edit:
// add the permission or the class there, and to the grammar's PermissionName or SecurableClassName.
//
// @COUNT@ pairs, from the 301 `sys.fn_builtin_permissions` gives less CREDENTIAL's two, which no
// statement can reach: the view lists CREDENTIAL as a class and the parser refuses `CREDENTIAL::x`.

using System;
using System.Collections.Generic;

namespace DotGram.Sql.TransactSql;

/// <summary>What permission may be written of what securable class, fixed when the grammar was built.</summary>
/// <remarks>
/// The parser reads this table and asks nothing of a consumer's object (D25): it is constants, decided
/// at build time. The engine makes the pairing a SYNTAX rule where an ON clause names a class --
/// <c>GRANT SELECT ON ENDPOINT::x</c> is 102, SELECT being none of ENDPOINT's five -- and leaves mixed
/// scopes without an ON clause to bind time, Msg 4620, which is the server's to answer and not ours.
/// </remarks>
internal static class PermissionCatalogue
{
\tstatic readonly HashSet<string> Pairs = new(StringComparer.Ordinal)
\t{
@ROWS@
\t};

\t/// <summary>Whether every permission written may be written of the securable's class.</summary>
\t/// <param name="permissions">The permissions as read, column lists and all.</param>
\t/// <param name="on">The securable clause as read, or null where the statement names none.</param>
\tinternal static bool Allows(string[]? permissions, string? on)
\t{
\t\t// No ON clause names no class, and then the engine does not make it syntax either.
\t\tif (permissions is null || on is null)
\t\t\treturn true;

\t\tvar named = Class(on);

\t\tforeach (var permission in permissions)
\t\t\tif (!Allows(named, permission))
\t\t\t\treturn false;

\t\treturn true;
\t}

\t/// <summary>Whether one permission may be written of one class.</summary>
\tinternal static bool Allows(string named, string permission)
\t{
\t\tvar one = Normalized(permission);

\t\t// ALL and ALL PRIVILEGES are every class's, and EXEC is EXECUTE's other spelling. The view has
\t\t// a row for none of the three.
\t\tif (one is "ALL" or "ALL PRIVILEGES")
\t\t\treturn true;

\t\tif (one == "EXEC")
\t\t\tone = "EXECUTE";

\t\treturn Pairs.Contains(named + "|" + one);
\t}

\t/// <summary>The class a securable clause names, which is OBJECT where it names only a name.</summary>
\tinternal static string Class(string on)
\t{
\t\tvar at = on.IndexOf("::", StringComparison.Ordinal);

\t\treturn at < 0 ? "OBJECT" : Normalized(on.Substring(0, at));
\t}

\t/// <summary>Upper case, one space between words, and without a column list.</summary>
\tstatic string Normalized(string text)
\t{
\t\tvar at = text.IndexOf('(');

\t\tif (at >= 0)
\t\t\ttext = text.Substring(0, at);

\t\treturn string.Join(
\t\t\t" ", text.ToUpperInvariant().Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));
\t}
}
'''

if __name__ == '__main__':
    named = pairs()

    open(OUTPUT, 'w', encoding='utf-8-sig', newline='').write(written(named))
    print('%s: %d pairs over %d classes' % (OUTPUT, len(named), len({one[0] for one in named})))
