<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" />
		<ProjectReference Include="../../src/DotGram.Finance/DotGram.Finance.csproj" />
		<ProjectReference Include="../../examples/DotGram.Examples/DotGram.Examples.csproj" />
	</ItemGroup>
</Project>
