// <auto-generated />
using System;
using DotGram;
namespace DotGram.Finance.Fix;

[Gram("ParserHeartbeat.gram", PartSize = 1000, Portable = false)]
static partial class ParserHeartbeat
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserTestRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserTestRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserResendRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserResendRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserReject.gram", PartSize = 1000, Portable = false)]
static partial class ParserReject
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSequenceReset.gram", PartSize = 1000, Portable = false)]
static partial class ParserSequenceReset
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserLogout.gram", PartSize = 1000, Portable = false)]
static partial class ParserLogout
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserIOI.gram", PartSize = 1000, Portable = false)]
static partial class ParserIOI
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserAdvertisement.gram", PartSize = 1000, Portable = false)]
static partial class ParserAdvertisement
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserExecutionReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserExecutionReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserOrderCancelReject.gram", PartSize = 1000, Portable = false)]
static partial class ParserOrderCancelReject
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserLogon.gram", PartSize = 1000, Portable = false)]
static partial class ParserLogon
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserNews.gram", PartSize = 1000, Portable = false)]
static partial class ParserNews
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserEmail.gram", PartSize = 1000, Portable = false)]
static partial class ParserEmail
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserNewOrderSingle.gram", PartSize = 1000, Portable = false)]
static partial class ParserNewOrderSingle
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserNewOrderList.gram", PartSize = 1000, Portable = false)]
static partial class ParserNewOrderList
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserOrderCancelRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserOrderCancelRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserOrderCancelReplaceRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserOrderCancelReplaceRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserOrderStatusRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserOrderStatusRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserAllocationInstruction.gram", PartSize = 1000, Portable = false)]
static partial class ParserAllocationInstruction
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserListCancelRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserListCancelRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserListExecute.gram", PartSize = 1000, Portable = false)]
static partial class ParserListExecute
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserListStatusRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserListStatusRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserListStatus.gram", PartSize = 1000, Portable = false)]
static partial class ParserListStatus
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserAllocationInstructionAck.gram", PartSize = 1000, Portable = false)]
static partial class ParserAllocationInstructionAck
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserDontKnowTrade.gram", PartSize = 1000, Portable = false)]
static partial class ParserDontKnowTrade
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserQuoteRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserQuoteRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserQuote.gram", PartSize = 1000, Portable = false)]
static partial class ParserQuote
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSettlementInstructions.gram", PartSize = 1000, Portable = false)]
static partial class ParserSettlementInstructions
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserMarketDataRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserMarketDataRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserMarketDataSnapshotFullRefresh.gram", PartSize = 1000, Portable = false)]
static partial class ParserMarketDataSnapshotFullRefresh
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserMarketDataIncrementalRefresh.gram", PartSize = 1000, Portable = false)]
static partial class ParserMarketDataIncrementalRefresh
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserMarketDataRequestReject.gram", PartSize = 1000, Portable = false)]
static partial class ParserMarketDataRequestReject
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserQuoteCancel.gram", PartSize = 1000, Portable = false)]
static partial class ParserQuoteCancel
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserQuoteStatusRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserQuoteStatusRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserMassQuoteAcknowledgement.gram", PartSize = 1000, Portable = false)]
static partial class ParserMassQuoteAcknowledgement
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSecurityDefinitionRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserSecurityDefinitionRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSecurityDefinition.gram", PartSize = 1000, Portable = false)]
static partial class ParserSecurityDefinition
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSecurityStatusRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserSecurityStatusRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSecurityStatus.gram", PartSize = 1000, Portable = false)]
static partial class ParserSecurityStatus
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserTradingSessionStatusRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserTradingSessionStatusRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserTradingSessionStatus.gram", PartSize = 1000, Portable = false)]
static partial class ParserTradingSessionStatus
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserMassQuote.gram", PartSize = 1000, Portable = false)]
static partial class ParserMassQuote
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserBusinessMessageReject.gram", PartSize = 1000, Portable = false)]
static partial class ParserBusinessMessageReject
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserBidRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserBidRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserBidResponse.gram", PartSize = 1000, Portable = false)]
static partial class ParserBidResponse
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserListStrikePrice.gram", PartSize = 1000, Portable = false)]
static partial class ParserListStrikePrice
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserXMLnonFIX.gram", PartSize = 1000, Portable = false)]
static partial class ParserXMLnonFIX
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserRegistrationInstructions.gram", PartSize = 1000, Portable = false)]
static partial class ParserRegistrationInstructions
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserRegistrationInstructionsResponse.gram", PartSize = 1000, Portable = false)]
static partial class ParserRegistrationInstructionsResponse
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserOrderMassCancelRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserOrderMassCancelRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserOrderMassCancelReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserOrderMassCancelReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserNewOrderCross.gram", PartSize = 1000, Portable = false)]
static partial class ParserNewOrderCross
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCrossOrderCancelReplaceRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserCrossOrderCancelReplaceRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCrossOrderCancelRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserCrossOrderCancelRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSecurityTypeRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserSecurityTypeRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSecurityTypes.gram", PartSize = 1000, Portable = false)]
static partial class ParserSecurityTypes
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSecurityListRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserSecurityListRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSecurityList.gram", PartSize = 1000, Portable = false)]
static partial class ParserSecurityList
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserDerivativeSecurityListRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserDerivativeSecurityListRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserDerivativeSecurityList.gram", PartSize = 1000, Portable = false)]
static partial class ParserDerivativeSecurityList
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserNewOrderMultileg.gram", PartSize = 1000, Portable = false)]
static partial class ParserNewOrderMultileg
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserMultilegOrderCancelReplace.gram", PartSize = 1000, Portable = false)]
static partial class ParserMultilegOrderCancelReplace
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserTradeCaptureReportRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserTradeCaptureReportRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserTradeCaptureReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserTradeCaptureReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserOrderMassStatusRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserOrderMassStatusRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserQuoteRequestReject.gram", PartSize = 1000, Portable = false)]
static partial class ParserQuoteRequestReject
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserRFQRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserRFQRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserQuoteStatusReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserQuoteStatusReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserQuoteResponse.gram", PartSize = 1000, Portable = false)]
static partial class ParserQuoteResponse
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserConfirmation.gram", PartSize = 1000, Portable = false)]
static partial class ParserConfirmation
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserPositionMaintenanceRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserPositionMaintenanceRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserPositionMaintenanceReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserPositionMaintenanceReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserRequestForPositions.gram", PartSize = 1000, Portable = false)]
static partial class ParserRequestForPositions
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserRequestForPositionsAck.gram", PartSize = 1000, Portable = false)]
static partial class ParserRequestForPositionsAck
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserPositionReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserPositionReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserTradeCaptureReportRequestAck.gram", PartSize = 1000, Portable = false)]
static partial class ParserTradeCaptureReportRequestAck
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserTradeCaptureReportAck.gram", PartSize = 1000, Portable = false)]
static partial class ParserTradeCaptureReportAck
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserAllocationReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserAllocationReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserAllocationReportAck.gram", PartSize = 1000, Portable = false)]
static partial class ParserAllocationReportAck
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserConfirmationAck.gram", PartSize = 1000, Portable = false)]
static partial class ParserConfirmationAck
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserSettlementInstructionRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserSettlementInstructionRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserAssignmentReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserAssignmentReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCollateralRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserCollateralRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCollateralAssignment.gram", PartSize = 1000, Portable = false)]
static partial class ParserCollateralAssignment
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCollateralResponse.gram", PartSize = 1000, Portable = false)]
static partial class ParserCollateralResponse
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCollateralReport.gram", PartSize = 1000, Portable = false)]
static partial class ParserCollateralReport
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCollateralInquiry.gram", PartSize = 1000, Portable = false)]
static partial class ParserCollateralInquiry
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserNetworkCounterpartySystemStatusRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserNetworkCounterpartySystemStatusRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserNetworkCounterpartySystemStatusResponse.gram", PartSize = 1000, Portable = false)]
static partial class ParserNetworkCounterpartySystemStatusResponse
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserUserRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserUserRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserUserResponse.gram", PartSize = 1000, Portable = false)]
static partial class ParserUserResponse
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCollateralInquiryAck.gram", PartSize = 1000, Portable = false)]
static partial class ParserCollateralInquiryAck
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserConfirmationRequest.gram", PartSize = 1000, Portable = false)]
static partial class ParserConfirmationRequest
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}

[Gram("ParserCustom.gram", PartSize = 1000, Portable = false)]
static partial class ParserCustom
{
	static bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);
}
