// Writes CaseFold.Table.cs, the simple case mappings an ignore-case literal folds by, from the
// Unicode Character Database at the version pinned below:
//
//     dotnet run src/DotGram/Grammar/Model/CaseFold.generate.cs [UnicodeData.txt]
//
// Without an argument it downloads UnicodeData.txt of that version from unicode.org. The generator
// carries the table rather than asking char.ToUpperInvariant, because the runtime's answer is the
// host's: it depends on the ICU a machine has, on invariant globalization mode and on the runtime
// (.NET Framework reads NLS), so one grammar would generate two parsers on two build machines.
//
// Each table holds the code points of the Basic Multilingual Plane whose simple mapping (field 12
// for upper case, 13 for lower) is another character of the plane, as runs: from, to, step, delta.
// A code point c in a run, (c - from) a multiple of step, maps to c + delta. A step of two is the
// alternating upper/lower pairs of the Latin and Cyrillic extensions.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Net.Http;
using System.Runtime.CompilerServices;
using System.Text;

const string Version = "16.0.0";

var here   = Path.GetDirectoryName(ScriptPath())!;
var source = args.Length > 0
	? File.ReadAllText(args[0])
	: new HttpClient().GetStringAsync($"https://www.unicode.org/Public/{Version}/ucd/UnicodeData.txt").Result;

var upper = new SortedDictionary<int, int>();
var lower = new SortedDictionary<int, int>();

foreach (var line in source.Split('\n'))
{
	var fields = line.TrimEnd('\r').Split(';');

	if (fields.Length < 15)
		continue;

	var code = int.Parse(fields[0], NumberStyles.HexNumber, CultureInfo.InvariantCulture);

	Take(upper, code, fields[12]);
	Take(lower, code, fields[13]);
}

var text = new StringBuilder();

text.Append("// <auto-generated/>\r\n");
text.Append($"// Written by CaseFold.generate.cs from UnicodeData.txt, Unicode {Version}: the simple case\r\n");
text.Append("// mappings of the Basic Multilingual Plane, as runs of from, to, step and delta. Do not edit.\r\n");
text.Append("\r\n");
text.Append("using System;\r\n");
text.Append("\r\n");
text.Append("namespace DotGram.Grammar.Model;\r\n");
text.Append("\r\n");
text.Append("public static partial class CaseFold\r\n");
text.Append("{\r\n");
text.Append($"\t/// <summary>The Unicode version the tables below were written from.</summary>\r\n");
text.Append($"\tpublic const string UnicodeVersion = \"{Version}\";\r\n");
Table(text, "Uppers", "simple upper case", upper);
Table(text, "Lowers", "simple lower case", lower);
text.Append("}\r\n");

// With a byte order mark, as every .cs file here is written.
File.WriteAllText(Path.Combine(here, "CaseFold.Table.cs"), text.ToString(), new UTF8Encoding(true));
Console.WriteLine($"Unicode {Version}: {upper.Count} upper and {lower.Count} lower mappings.");

static void Take(SortedDictionary<int, int> table, int code, string mapped)
{
	if (mapped.Length == 0 || code > 0xFFFF)
		return;

	var to = int.Parse(mapped, NumberStyles.HexNumber, CultureInfo.InvariantCulture);

	if (to <= 0xFFFF && to != code)
		table[code] = to - code;
}

static void Table(StringBuilder text, string name, string what, SortedDictionary<int, int> table)
{
	var runs = new List<(int From, int To, int Step, int Delta)>();

	foreach (var (code, delta) in table)
	{
		if (runs.Count > 0)
		{
			var last = runs[^1];

			if (last.Delta == delta &&
				(last.From == last.To ? code - last.To is 1 or 2 : code - last.To == last.Step))
			{
				runs[^1] = (last.From, code, code - last.To, delta);

				continue;
			}
		}

		runs.Add((code, code, 1, delta));
	}

	text.Append("\r\n");
	text.Append($"\t/// <summary>The {what}: {runs.Count} runs over {table.Count} code points.</summary>\r\n");
	text.Append($"\tstatic readonly int[] {name} =\r\n");
	text.Append("\t{\r\n");

	foreach (var (from, to, step, delta) in runs)
		text.Append($"\t\t0x{from:X4}, 0x{to:X4}, {step}, {delta,6},\r\n");

	text.Append("\t};\r\n");
}

static string ScriptPath([CallerFilePath] string path = "")
{
	return path;
}
