using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using DotGram.Grammar.Binding;
using DotGram.Grammar.Model;
using DotGram.Grammar.Parsing;

namespace DotGram.Grammar.Emit;

/// <summary>Indent-aware output. One per generated function, so nothing interleaves.</summary>
sealed class Writer(int depth)
{
	readonly StringBuilder _text = new();

	int _depth = depth;

	/// <summary>How far in the next line will be written — what a nested writer starts at.</summary>
	public int Depth => _depth;

	public void Line(string text = "")
	{
		if (text.Length == 0)
			_text.EndLine();
		else
			_text.Append('\t', _depth).AppendEndingWith(text);
	}

	/// <summary>A single indented line — the body of an <c>if</c> without braces.</summary>
	public void Then(string text)
	{
		_depth++;
		Line(text);
		_depth--;
	}

	public IDisposable Block(string header)
	{
		Line(header);
		Line("{");
		_depth++;

		return new Closer(this);
	}

	/// <summary>Indents what follows, without braces around it — a switch section.</summary>
	public IDisposable Indent()
	{
		_depth++;

		return new Outdenter(this);
	}

	public void Append(Writer other) => _text.Append(other._text);

	/// <summary>Writes text that is already laid out, each line at the current depth.</summary>
	public void Write(string text)
	{
		var written = new Writer(0);

		written._text.Append(text);

		// AppendIndented reads the text as lines, each closed by an ending. Text that
		// does not end with one — a raw string literal, say — would lose its last line.
		if (!text.EndsWith(Lines.Ending, StringComparison.Ordinal))
			written._text.Append(Lines.Ending);

		AppendIndented(written, 0);
	}

	/// <summary>Appends another writer's text, shifted in to this one's depth.</summary>
	public void AppendIndented(Writer other, int extra = 1)
	{
		var lines = other._text.ToString().Split([Lines.Ending], StringSplitOptions.None);

		// The text ends with an ending, so the split leaves a final empty piece that is
		// not a line at all.
		for (var i = 0; i < lines.Length - 1; i++)
			if (lines[i].Length > 0)
				_text.Append('\t', _depth + extra).AppendEndingWith(lines[i]);
			else
				_text.EndLine();
	}

	public override string ToString() => _text.ToString();

	sealed class Closer(Writer writer) : IDisposable
	{
		public void Dispose()
		{
			writer._depth--;
			writer.Line("}");
		}
	}

	sealed class Outdenter(Writer writer) : IDisposable
	{
		public void Dispose() => writer._depth--;
	}
}

/// <summary>
/// Turns a recognition graph into C#.
/// </summary>
/// <remarks>
/// <para>
/// One method per rule, and inside it one static local function per node. Every one of
/// them has the same shape — take the input and a position, return the new position or
/// -1 — so composing them is just calling them, and there is nothing to allocate,
/// nothing virtual, and no closure. Static local functions specifically, because a
/// closure cannot hold a <c>ReadOnlySpan</c>.
/// </para>
/// <para>
/// This is the fast path over the frozen subset of docs/implementation.md §11:
/// sequence, ordered choice, quantifiers, element sets, literals, rule calls. No
/// trivia, no result construction, no recovery yet — a rule's value is the text it
/// matched.
/// </para>
/// </remarks>
public static class CSharpEmitter
{
	/// <param name="graph">The normalized grammar.</param>
	/// <param name="className">
	/// The partial class the generated members go into. A nested host is named by its
	/// chain — <c>Outer.Inner</c> — and written back out nested.
	/// </param>
	/// <param name="namespace">Its namespace, or null for the global one.</param>
	public static string Emit(RecognitionGraph graph, string className, string? @namespace = null)
	{
		if (graph is null)
			throw new ArgumentNullException(nameof(graph));

		var file    = new Writer(0);
		var scope   = new Stack<IDisposable>();
		var results = new ResultTypes(graph, className, @namespace);

		file.Line("// <auto-generated/>");
		file.Line("#nullable enable");
		file.Line();

		// A block namespace rather than a file-scoped one: the consumer's language
		// version is unknown (.claude/rules/emitted-code.md).
		if (@namespace is not null)
			scope.Push(file.Block($"namespace {@namespace}"));

		foreach (var name in className.Split('.'))
			scope.Push(file.Block($"partial class {name}"));

		foreach (var publication in graph.Publications)
		{
			EmitPublication(file, publication, results);
			file.Line();
		}

		foreach (var rule in results.Built)
		{
			EmitResultType(file, graph, results, rule);
			file.Line();
		}

		var needsStack = false;

		// `parse` demands the input end. Asking the rule and then checking would leave it
		// unable to go back for a longer match — the check has to be inside the machine,
		// where failing it is an ordinary failure and the stack still has somewhere to
		// resume. So the rule's body is compiled again, with end-of-input on the end.
		foreach (var publication in graph.Publications)
		{
			if (publication.Kind != PublishKind.Parse)
				continue;

			var whole = new Machine(
				WholeOf(publication.Rule), results, BuiltBy(graph, results, publication.Rule));

			var body = new Node.Sequence([graph.Bodies[publication.Rule], EndOfInput]);

			file.Write(whole.Render(
				whole.Compile(body, Machine.Accept),
				$"parse {publication.Rule.Name}: {graph.Bodies[publication.Rule]} & eof"));
			file.Line();

			foreach (var extra in whole.Extra)
			{
				file.Write(extra);
				file.Line();
			}

			needsStack = true;
		}

		foreach (var rule in graph.Rules)
		{
			needsStack |= EmitRule(file, graph, results, rule);
			file.Line();
		}

		if (graph.Rules.Count > 0)
		{
			file.Write(FailureStruct);
			file.Line();
		}

		if (needsStack)
			file.Write(GrowHelper);

		while (scope.Count > 0)
			scope.Pop().Dispose();

		return file.ToString();
	}

	/// <summary>
	/// One directive, one pair of methods, in the shape of <c>int.Parse</c> /
	/// <c>int.TryParse</c> (docs/syntax.md §6).
	/// </summary>
	/// <remarks>
	/// What a rule yields is either its captures, built into a type of its own, or — when
	/// it captures nothing — the text it matched. Only these signatures know the
	/// difference; what they are built on, a recognizer returning an end position or -1,
	/// does not change either way.
	/// </remarks>
	static void EmitPublication(Writer file, Publication publication, ResultTypes results)
	{
		var method   = publication.MethodName;
		var name     = publication.Rule.Name;
		var isAll    = publication.Kind == PublishKind.FindAll;
		var built    = results.QualifiedOf(publication.Rule);
		var value    = built ?? "string";
		var result   = isAll ? value + "[]" : publication.Kind == PublishKind.Parse ? value : value + "?";
		var outType  = isAll ? value + "[]" : value;
		var outName  = isAll ? "values" : "value";

		file.Line($"/// <summary>{Summary(publication.Kind, name)}</summary>");

		using (file.Block($"public static {result} {method}(string input)"))
		{
			file.Line($"if (Try{method}(input, out var {outName}, out var error, out var errorPosition))");
			file.Then($"return {outName};");
			file.Line();

			// Only `parse` throws: it is the one directive that asserts the input is this
			// rule, so failing it is an error rather than an answer of "no".
			if (publication.Kind == PublishKind.Parse)
				file.Line("throw new global::System.FormatException(error + \" at \" + errorPosition.ToString());");
			else
				file.Line(isAll ? $"return new {value}[0];" : "return null;");
		}

		file.Line();

		using (file.Block(
			$"public static bool Try{method}(string input, out {outType} {outName}, out string? error, out int errorPosition)"))
		{
			// Fully qualified, and as a static call rather than an extension method:
			// the emitted file carries no usings at all (.claude/rules/emitted-code.md).
			file.Line("var text = global::System.MemoryExtensions.AsSpan(input);");
			file.Line();
			file.Line($"{outName} = {(isAll ? $"new {value}[0]" : built is null ? "\"\"" : "null!")};");
			file.Line("error         = null;");
			file.Line("errorPosition = 0;");
			file.Line();

			// Carried through every recognizer this call reaches, so that what comes back
			// is the furthest the input was followed and not merely "no".
			file.Line($"var failure = new {FailureType}();");
			file.Line();

			// A rule that builds hands its value back through the recognizer; one that does
			// not leaves the extent it matched, and the text is cut from the input.
			var hands = built is null ? ", ref failure" : ", ref failure, out var recognized";

			string Recognized(string from, string to) =>
				built is null ? $"input.Substring({from}, {to})" : "recognized";

			switch (publication.Kind)
			{
				case PublishKind.Parse:
				case PublishKind.Match:

					// The difference between the two directives, and the whole of it: one
					// calls the recognizer that also insists the input ended.
					var entry = publication.Kind == PublishKind.Parse
						? WholeOf(publication.Rule)
						: MethodOf(publication.Rule);

					file.Line($"var end = {entry}(text, 0{hands});");
					file.Line();

					using (file.Block("if (end < 0)"))
					{
						file.Line($"error         = \"Input does not match '{name}'.\";");
						file.Line("errorPosition = failure.Position;");
						file.Line("return false;");
					}

					file.Line();
					file.Line($"value = {Recognized("0", "end")};");
					file.Line("return true;");
					break;

				case PublishKind.Find:

					using (file.Block("for (var start = 0; start <= input.Length; start++)"))
					{
						file.Line($"var end = {MethodOf(publication.Rule)}(text, start{hands});");
						file.Line();

						using (file.Block("if (end >= 0)"))
						{
							file.Line($"value = {Recognized("start", "end - start")};");
							file.Line("return true;");
						}
					}

					file.Line();
					file.Line($"error         = \"No occurrence of '{name}'.\";");
					file.Line("errorPosition = failure.Position;");
					file.Line("return false;");
					break;

				default:

					file.Line($"var found = new global::System.Collections.Generic.List<{value}>();");
					file.Line();

					using (file.Block("for (var start = 0; start <= input.Length; )"))
					{
						file.Line($"var end = {MethodOf(publication.Rule)}(text, start{hands});");
						file.Line();

						using (file.Block("if (end < 0)"))
						{
							file.Line("start++;");
							file.Line("continue;");
						}

						file.Line();
						file.Line($"found.Add({Recognized("start", "end - start")});");
						file.Line();
						file.Line("// A rule that matches nothing would otherwise find it for ever.");
						file.Line("start = end > start ? end : start + 1;");
					}

					file.Line();

					using (file.Block("if (found.Count == 0)"))
					{
						file.Line($"error         = \"No occurrence of '{name}'.\";");
						file.Line("errorPosition = failure.Position;");
						file.Line("return false;");
					}

					file.Line();
					file.Line("values = found.ToArray();");
					file.Line("return true;");
					break;
			}
		}
	}

	static string Summary(PublishKind kind, string rule) => kind switch
	{
		PublishKind.Parse   => $"Parses the whole input as <c>{rule}</c>.",
		PublishKind.Match   => $"Matches <c>{rule}</c> at the start of the input.",
		PublishKind.Find    => $"Finds the first occurrence of <c>{rule}</c>.",
		_                   => $"Finds every non-overlapping occurrence of <c>{rule}</c>.",
	};

	/// <summary>
	/// The type a rule's captures are built into: a constructor and a get-only property
	/// per capture, and nothing else.
	/// </summary>
	/// <remarks>
	/// <c>public</c>, unlike the support types of §6.1 — those are shared between
	/// assemblies and so have a version to skew, while this one is generated from the
	/// grammar it belongs to, in the assembly that uses it. That is what lets a published
	/// method hand it back.
	/// </remarks>
	static void EmitResultType(Writer file, RecognitionGraph graph, ResultTypes results, RuleSymbol rule)
	{
		var name    = results.NameOf(rule)!;
		var members = graph.Results[rule];

		string Type(ResultMember member) =>
			results.ValueOf(member.Rule) + (member.IsOptional ? "?" : "");

		file.Line($"/// <summary>What the rule <c>{rule.Name}</c> recognized.</summary>");

		using (file.Block($"public sealed class {name}"))
		{
			var parameters = members.Select(member => $"{Type(member)} {ResultTypes.ParameterOf(member)}");

			using (file.Block($"public {name}({string.Join(", ", parameters)})"))
				foreach (var member in members)
					file.Line($"{ResultTypes.PropertyOf(member, name)} = {ResultTypes.ParameterOf(member)};");

			foreach (var member in members)
			{
				file.Line();
				file.Line($"/// <summary>The <c>{member.Name}</c> capture.</summary>");
				file.Line($"public {Type(member)} {ResultTypes.PropertyOf(member, name)} {{ get; }}");
			}
		}
	}

	/// <summary>What a rule's machine builds, or null when its value is the text.</summary>
	static Machine.Built? BuiltBy(RecognitionGraph graph, ResultTypes results, RuleSymbol rule) =>
		results.NameOf(rule) is null
			? null
			: new Machine.Built(
				results.QualifiedOf(rule)!,
				graph.Results[rule],
				CaptureLayout.Of(graph.Bodies[rule], other => results.NameOf(other) is not null));

	/// <summary>One rule, and whether it needed the shared stack helper.</summary>
	static bool EmitRule(Writer file, RecognitionGraph graph, ResultTypes results, RuleSymbol rule)
	{
		var machine = new Machine(MethodOf(rule), results, BuiltBy(graph, results, rule));
		var entry   = machine.Compile(graph.Bodies[rule], Machine.Accept);
		var text    = machine.Render(entry, $"{rule.Name} = {graph.Bodies[rule]}");

		foreach (var extra in machine.Extra)
		{
			file.Write(extra);
			file.Line();
		}

		file.Write(text);

		return machine.UsesStack || machine.Extra.Count > 0;
	}

	internal static string MethodOf(RuleSymbol rule) => $"Recognize_{rule.Name.Replace('.', '_')}";

	/// <summary>The recognizer that also insists the input ended — what `parse` calls.</summary>
	static string WholeOf(RuleSymbol rule) => MethodOf(rule) + "_Whole";

	/// <summary>
	/// End of input: the complement of everything, not present. The same node `eof`
	/// lowers to, built here rather than looked up so that a grammar which never
	/// mentions `eof` still gets one.
	/// </summary>
	static Node EndOfInput =>
		new Node.Lookahead(IsPositive: false, new Node.Element(IsNegated: true, [], [], []));

	/// <summary>
	/// What every recognizer carries so that a failure can be described.
	/// </summary>
	/// <remarks>
	/// The name a rule may not take: <see cref="ResultTypes"/> renames its own type
	/// instead if a grammar declares a rule called this.
	/// </remarks>
	internal const string FailureType = "Failure";

	/// <summary>
	/// The record of the best failure a match saw, threaded through every recognizer.
	/// </summary>
	/// <remarks>
	/// A struct passed by <c>ref</c> rather than more <c>out</c> parameters, and that is
	/// the point of it: what a failure has to say is going to grow — the set of what was
	/// expected there, an outcome that tells a malformed record from no record at all
	/// (docs/syntax.md §8.1) — and each of those would otherwise be another parameter on
	/// every recognizer and another edit at every call site.
	/// </remarks>
	internal const string FailureStruct = """
		/// <summary>Where a match got before it gave up, and why.</summary>
		struct Failure
		{
			/// <summary>
			/// The furthest position the input was followed to. Zero on a match that
			/// succeeded without ever backtracking, and meaningless unless one failed.
			/// </summary>
			public int Position;
		}
		""";

	/// <summary>
	/// Grows the backtracking stack. Emitted once per class, next to the recognizers
	/// that share it.
	/// </summary>
	internal const string GrowHelper = """
		static int[] Grow(global::System.Span<int> from)
		{
			var bigger = new int[from.Length * 2];

			from.CopyTo(bigger);

			return bigger;
		}
		""";

	internal static string Test(Node.Element element)
	{
		var tests = new List<string>();

		foreach (var range in element.Ranges)
			tests.Add(range.IsSingle
				? $"c == {Char(range.From)}"
				: $"(c >= {Char(range.From)} && c <= {Char(range.To)})");

		foreach (var category in element.Categories)
			// `\p{Lu}` is the regular-expression spelling; the enum member is
			// UppercaseLetter. `\p{L}` is not one category but five, so a group expands
			// into a test for each.
			foreach (var name in UnicodeCategories.Expand(category))
				tests.Add(
					"global::System.Globalization.CharUnicodeInfo.GetUnicodeCategory(c) == " +
					$"global::System.Globalization.UnicodeCategory.{name}");

		// An empty set admits nothing, and its complement admits everything. Said as
		// constants rather than as `!(false)`, so the caller can drop the test — and with
		// it the character it would otherwise read and never look at.
		if (tests.Count == 0)
			return element.IsNegated ? "true" : "false";

		var test = string.Join(" || ", tests);

		return element.IsNegated ? $"!({test})" : $"({test})";
	}

	/// <summary>
	/// A char as a C# character literal.
	/// </summary>
	/// <remarks>
	/// Everything outside plain printable ASCII goes out as <c>\uXXXX</c>. Putting the
	/// character itself into the file would work for most of them and produce a source
	/// file with a raw control character in it for the rest — and the emitted text is
	/// read by people, not only by a compiler.
	/// </remarks>
	internal static string Char(char value) => value switch
	{
		'\''                         => @"'\''",
		'\\'                         => @"'\\'",
		>= ' ' and <= '~'            => $"'{value}'",
		'\0'                         => @"'\0'",
		'\a'                         => @"'\a'",
		'\b'                         => @"'\b'",
		'\f'                         => @"'\f'",
		'\n'                         => @"'\n'",
		'\r'                         => @"'\r'",
		'\t'                         => @"'\t'",
		'\v'                         => @"'\v'",
		_                            => $@"'\u{(int)value:X4}'",
	};
}
