using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using DotGram.Grammar.Binding;
using DotGram.Grammar.Model;
using DotGram.Grammar.Parsing;

namespace DotGram.Grammar.Emit;

/// <summary>
/// Turns a recognition graph into C#.
/// </summary>
/// <remarks>
/// <para>
/// Publications share one state-machine method; their recognizers are thin entry
/// wrappers selecting a label and the expected result. Every recognizer has the same external
/// shape: take the input and a position and return the new position or -1.
/// </para>
/// <para>
/// What this file is responsible for is everything around the machines — the published
/// methods, the result types, the factories a <c>=&gt;</c> becomes, the support types
/// shared with the machines, and the layout of the file they all go in. The machines
/// themselves are compiled by <see cref="Machine"/>.
/// </para>
/// <para>
/// The text produced here is compiled in the consumer's project, which is a different
/// set of rules from this assembly's own: see .claude/rules/emitted-code.md.
/// </para>
/// </remarks>
public static partial class CSharpEmitter
{
	/// <param name="graph">The normalized grammar.</param>
	/// <param name="className">
	/// The partial class the generated members go into. A nested host is named by its
	/// chain — <c>Outer.Inner</c> — and written back out nested.
	/// </param>
	/// <param name="namespace">Its namespace, or null for the global one.</param>
	/// <param name="lines">
	/// Where the grammar's own C# came from, for the <c>#line</c> directives of §7.6. Null
	/// emits none, which is right for a caller with no file to point at.
	/// </param>
	public static string Emit(
		RecognitionGraph graph, string className, string? @namespace = null, ILineMap? lines = null)
	{
		if (graph is null)
			throw new ArgumentNullException(nameof(graph));

		var file    = new Writer(0);
		var scope   = new Stack<IDisposable>();
		var results = new ResultTypes(graph, className, @namespace);
		var machine = graph.Rules.Count > 0
			? new Machine(graph, results, lines, Streaming(graph))
			: null;

		// Every publication needs none of the three things the arena is for: no recursion,
		// no backtracking, no deferred construction. One disqualifying publication anywhere
		// and this stays false, and every line below runs exactly as it always has — see
		// docs/next.md, "Future optimization gate".
		var flat = machine is not null &&
			graph.Publications.Count > 0 &&
			graph.Recoveries.Count == 0 &&
			graph.Climbing.Count == 0 &&
			!Streaming(graph) &&
			graph.Publications.All(
				publication => machine.CanLower(publication.Rule, publication.Kind == PublishKind.Parse));

		file.Line("// <auto-generated/>");
		file.Line("#nullable enable");
		file.Line();

		// A block namespace rather than a file-scoped one: the consumer's language
		// version is unknown (.claude/rules/emitted-code.md).
		if (@namespace is not null)
			scope.Push(file.Block($"namespace {@namespace}"));

		// The grammar's own `@using` directives and no others. Everything this file
		// generates is written with `global::`; these are here for the C# the grammar
		// supplied, which was written expecting them (§1).
		if (graph.CSharpImports.Count > 0)
		{
			foreach (var import in graph.CSharpImports)
				file.Line($"using {import};");

			file.Line();
		}

		foreach (var name in className.Split('.'))
			scope.Push(file.Block($"partial class {name}"));

		foreach (var publication in graph.Publications)
		{
			EmitPublication(
				file,
				publication,
				results,
				graph.Climbing.ContainsKey(publication.Rule),
				Streams(graph, publication));

			file.Line();
		}

		foreach (var rule in results.Built)
		{
			EmitResultType(file, graph, results, rule);
			file.Line();
		}

		foreach (var rule in graph.Rules)
		{
			if (!graph.Types.ContainsKey(rule))
				continue;

			foreach (var factory in FactoriesOf(graph, results, rule))
			{
				EmitFactory(file, graph, rule, factory, results, lines);
				file.Line();
			}
		}

		if (machine is not null)
			foreach (var rule in graph.Rules)
				if (RecoveryIn(graph, results, rule) is { } recoveryFound)
				{
					var (_, recovery, slot) = recoveryFound;

					if (recovery.Factory is not null && slot >= 0)
						EmitRecoveryFactory(file, results, rule, MethodOf(rule), recovery, graph, slot);
				}

		const string engine = "Recognize_DotGram";
		var continuationProbes = new Dictionary<(RuleSymbol Rule, int Stage), (string Name, int Entry)>();
		var streamedParts = new Dictionary<(RuleSymbol Rule, int Stage), (string Name, int Entry)>();
		var streamedSyncs = new Dictionary<RuleSymbol, (string Name, int Entry)>();
		var streamedRules = new HashSet<RuleSymbol>();

		if (flat)
		{
			var rendered = new HashSet<(RuleSymbol Rule, bool Whole)>();

			foreach (var publication in graph.Publications)
			{
				var whole = publication.Kind == PublishKind.Parse;

				if (!rendered.Add((publication.Rule, whole)))
					continue;

				var wrapperName = whole ? WholeOf(publication.Rule) : MethodOf(publication.Rule);
				var flatName    = MethodOf(publication.Rule) + (whole ? "_Whole" : "") + "_Flat";

				file.Write(machine!.RenderFlat(publication.Rule, flatName, whole));
				file.Line();
				file.Write(machine.RenderFlatWrapper(publication.Rule, wrapperName, flatName));
				file.Line();
			}
		}

		if (machine is not null && !flat)
		{
			foreach (var publication in graph.Publications)
			{
				machine.Register(publication.Rule, publication.Kind == PublishKind.Parse);

				if (publication.Kind != PublishKind.Parse || !Streams(graph, publication) ||
					StagesOf(graph, publication.Rule) is not { } stages)
					continue;

				for (var stage = 0; stage < stages.Count; stage++)
				{
					if (stages[stage].Rule is { } stagedRule)
					{
						streamedRules.Add(stagedRule);
						machine.Register(stagedRule, whole: false);
					}
					else
					{
						var part = WholeOf(publication.Rule) + "_Part" + stage;
						streamedParts[(publication.Rule, stage)] =
							(part, machine.Register(stages[stage].Node));
					}

					if (!stages[stage].Repeated || continuationProbes.ContainsKey((publication.Rule, stage)))
						continue;

					var suffix = new List<Node>(stages.Count - stage - 1);

					for (var after = stage + 1; after < stages.Count; after++)
						suffix.Add(stages[after].Node);

					var continuation = suffix.Count switch
					{
						0 => new Node.Empty(),
						1 => suffix[0],
						_ => new Node.Sequence(suffix),
					};
					var probe = WholeOf(publication.Rule) + "_Continue" + stage;

					continuationProbes[(publication.Rule, stage)] =
						(probe, machine.Register(continuation));
				}

				if (RecoveryIn(graph, results, publication.Rule) is { } recoveryFound &&
					!streamedSyncs.ContainsKey(publication.Rule))
				{
					var sync = WholeOf(publication.Rule) + "_Sync";
					streamedSyncs[publication.Rule] =
						(sync, machine.Register(recoveryFound.Recovery.Sync));
				}
			}

			file.Write(machine.RenderEngine(engine));
			file.Line();

			var wrappers = new HashSet<(RuleSymbol Rule, bool Whole)>();

			foreach (var publication in graph.Publications)
			{
				var whole = publication.Kind == PublishKind.Parse;

				if (!wrappers.Add((publication.Rule, whole)))
					continue;

				file.Write(machine.RenderWrapper(
					publication.Rule,
					whole ? WholeOf(publication.Rule) : MethodOf(publication.Rule),
					engine,
					whole));
				file.Line();
			}

			if (graph.Publications.Count == 0)
				foreach (var rule in graph.Rules)
				{
					file.Write(machine.RenderWrapper(rule, MethodOf(rule), engine, whole: false));
					file.Line();
				}

			foreach (var rule in streamedRules)
				if (wrappers.Add((rule, false)))
				{
					file.Write(machine.RenderWrapper(rule, MethodOf(rule), engine, whole: false));
					file.Line();
				}

			foreach (var probe in continuationProbes.Values)
			{
				file.Write(Machine.RenderProbe(
					probe.Name, engine, probe.Entry, graph.Climbing.Count > 0));
				file.Line();
			}

			foreach (var probe in streamedParts.Values)
			{
				file.Write(Machine.RenderProbe(
					probe.Name, engine, probe.Entry, graph.Climbing.Count > 0));
				file.Line();
			}

			foreach (var probe in streamedSyncs.Values)
			{
				file.Write(Machine.RenderSyncProbe(
					probe.Name, engine, probe.Entry, graph.Climbing.Count > 0));
				file.Line();
			}
		}

		// `parse` demands the input end. Asking the rule and then checking would leave it
		// unable to go back for a longer match — the check has to be inside the machine,
		// where failing it is an ordinary failure and the stack still has somewhere to
		// resume. So the rule's body is compiled again, with end-of-input on the end.
		foreach (var publication in graph.Publications)
		{
			if (publication.Kind != PublishKind.Parse)
				continue;

			// §6.3 over a reader. The parts that are not calls — `eof`, a separator, the
			// trivia normalization inserted — have no recognizer of their own, so each gets
			// one: the driver runs them in order and they have to be runnable one at a time.
			if (Streams(graph, publication) && StagesOf(graph, publication.Rule) is { } stages)
			{
				var parts = new List<string>(stages.Count);

				for (var i = 0; i < stages.Count; i++)
				{
					if (stages[i].Rule is not null)
					{
						parts.Add("");

						continue;
					}

					parts.Add(streamedParts[(publication.Rule, i)].Name);
				}

				// What the repetition was told to do about a bad element, and where the
				// parse may pick up again — compiled here rather than inside a machine,
				// because in a stream it is the driver that steps over one.
				var found   = RecoveryIn(graph, results, publication.Rule);
				var sync    = (string?)null;
				var factory = MethodOf(publication.Rule) + "_Recover";

				if (found is not null)
					sync = streamedSyncs[publication.Rule].Name;

				EmitStreamingParse(
					file, graph, publication, results, stages, parts,
					found?.Recovery, sync, factory,
					stage => continuationProbes.TryGetValue((publication.Rule, stage), out var probe)
						? probe.Name
						: null);
				file.Line();
			}
		}

		if (machine is not null)
			foreach (var extra in machine.Extra)
			{
				file.Write(extra);
				file.Line();
			}
		if (UsesSourceSpan(graph))
		{
			file.Write(SourceSpanStruct);
			file.Line();
		}

		if (graph.Publications.Count > 0)
		{
			file.Write(MatchStruct);
			file.Line();
		}

		if (machine is not null)
		{
			file.Write(FailureStructWith(
				reach: graph.Recoveries.Count > 0 && Streaming(graph),
				starved: Streaming(graph),
				expected: true));
			file.Line();
		}

		if (Streaming(graph))
		{
			file.Write(WindowClass);
			file.Line();
			file.Write(LinesClass);
			file.Line();
		}

		if (Reporting(graph))
		{
			file.Write(RecoveredHook);
			file.Line();
		}

		if (Locating(graph))
		{
			file.Write(LocateHelper);
			file.Line();
		}

		if (machine is not null && !flat)
			file.Write(ParserRuntime(graph.Climbing.Count > 0, machine.Caches, machine.ValueTypes));

		while (scope.Count > 0)
			scope.Pop().Dispose();

		return file.ToString();
	}

	/// <summary>
	/// One directive (docs/syntax.md §6). <c>parse</c> makes an asserting method and an
	/// asking one; <c>find</c> makes a sequence.
	/// </summary>
	/// <remarks>
	/// No <c>out</c> parameters anywhere: what a match has to say goes in
	/// <see cref="MatchType"/>, where the next thing it has to say is a field rather than
	/// another parameter on every signature.
	/// </remarks>
	static void EmitPublication(
		Writer file, Publication publication, ResultTypes results, bool climbs, bool streams)
	{
		var method = publication.MethodName;
		var name   = publication.Rule.Name;
		var built  = results.QualifiedOf(publication.Rule);
		var value  = built ?? "string";
		var match  = $"{MatchType}<{value}>";

		// A rule that builds hands its value back through the recognizer; one that does
		// not leaves the extent it matched, and the text is cut from the input.
		// A rule of binding powers is asked at strength 0, which admits all of it (§4.3.1).
		var hands = (climbs ? ", 0" : "") +
			(built is null ? ", ref failure" : ", ref failure, out var recognized");

		string Recognized(string from, string to) =>
			built is null ? $"input.Substring({from}, {to})" : "recognized";

		if (publication.Kind == PublishKind.Find)
		{
			EmitFind(file, publication, method, name, value, match, hands, Recognized);

			if (streams)
			{
				file.Line();

				EmitStreamingFind(file, publication, method, name, match, hands, built is not null);
			}

			return;
		}

		file.Line($"/// <summary>Parses the whole input as <c>{name}</c>.</summary>");
		file.Line("/// <exception cref=\"global::System.FormatException\">");
		file.Line($"/// The input is not <c>{name}</c>. <c>Try{method}</c> answers instead.");
		file.Line("/// </exception>");

		using (file.Block($"public static {value} {method}(string input)"))
		{
			file.Line($"var match = Try{method}(input);");
			file.Line();
			file.Line("if (match.IsSuccess)");
			file.Then("return match.Value;");
			file.Line();
			file.Line("throw new global::System.FormatException(match.Error + \" at \" + match.Position.ToString());");
		}

		file.Line();
		file.Line($"/// <summary>Parses the whole input as <c>{name}</c>, answering rather than throwing.</summary>");

		using (file.Block($"public static {match} Try{method}(string input)"))
		{
			// Fully qualified, and as a static call rather than an extension method:
			// the emitted file carries no usings at all (.claude/rules/emitted-code.md).
			file.Line("var text    = global::System.MemoryExtensions.AsSpan(input);");

			// Carried through every recognizer this call reaches, so that what comes back
			// is the furthest the input was followed and not merely "no".
			file.Line($"var failure = new {FailureType}();");
			file.Line();
			file.Line($"var end = {WholeOf(publication.Rule)}(text, 0{hands});");
			file.Line();
			file.Line("if (end < 0)");
			using (file.Block(""))
			{
				file.Line("string message;");
				file.Line();
				file.Line("if (failure.Expected is { Count: 1 } one)");
				file.Then("message = \"Expected \" + one[0] + \".\";");
				file.Line("else if (failure.Expected is { Count: > 1 } many)");
				file.Then(
					"message = \"Expected \" + string.Join(\", \", many.GetRange(0, many.Count - 1)) + " +
					"\" or \" + many[many.Count - 1] + \".\";");
				file.Line("else if (failure.Position >= text.Length)");
				file.Then("message = \"Expected more input.\";");
				file.Line("else");
				file.Then($"message = \"Input does not match '{name}'.\";");
				file.Line();
				file.Line($"return {match}.Failed(message, failure.Position);");
			}
			file.Line();
			file.Line($"return {match}.Success({Recognized("0", "end")}, 0, end);");
		}
	}

	/// <summary>
	/// <c>find</c>: every occurrence, one at a time.
	/// </summary>
	/// <remarks>
	/// An iterator rather than an array, so that a document with a million occurrences
	/// costs one at a time — and so that "the first one" and "the ones that satisfy this"
	/// are LINQ's rather than three more directives. The span is made where it is passed
	/// and never held in a local, which is what lets this be an iterator at all.
	/// </remarks>
	static void EmitFind(
		Writer file, Publication publication, string method, string name,
		string value, string match, string hands, Func<string, string, string> recognized)
	{
		file.Line($"/// <summary>Every occurrence of <c>{name}</c>, in order, found as it is asked for.</summary>");

		using (file.Block(
			$"public static global::System.Collections.Generic.IEnumerable<{match}> {method}(string input)"))
		{
			using (file.Block("for (var start = 0; start <= input.Length; )"))
			{
				file.Line($"var failure = new {FailureType}();");
				file.Line();
				file.Line(
					$"var end = {MethodOf(publication.Rule)}(" +
					$"global::System.MemoryExtensions.AsSpan(input), start{hands});");
				file.Line();

				using (file.Block("if (end < 0)"))
				{
					file.Line("start++;");
					file.Line("continue;");
				}

				file.Line();
				file.Line($"yield return {match}.Success({recognized("start", "end - start")}, start, end - start);");
				file.Line();
				file.Line("// A rule that matches nothing would otherwise find it for ever.");
				file.Line("start = end > start ? end : start + 1;");
			}
		}
	}

	/// <summary>
	/// The type a rule's captures are built into: a constructor and a get-only property
	/// per capture, and nothing else.
	/// </summary>
	/// <remarks>
	/// <c>public</c>, unlike the support types of §6.1 — those are shared between
	/// assemblies and so have a version to skew, while this one is generated from the
	/// grammar it belongs to, in the assembly that uses it. That is what lets a published
	/// method hand it back.
	/// </remarks>
	static void EmitResultType(Writer file, RecognitionGraph graph, ResultTypes results, RuleSymbol rule)
	{
		var name    = results.NameOf(rule)!;
		var members = graph.Results[rule];

		string Type(ResultMember member) =>
			results.ValueOf(member.Rule) + (member.IsSequence ? "[]" : member.IsOptional ? "?" : "");

		file.Line($"/// <summary>What the rule <c>{rule.Name}</c> recognized.</summary>");

		using (file.Block($"public sealed class {name}"))
		{
			var parameters = members.Select(member => $"{Type(member)} {ResultTypes.ParameterOf(member)}");

			using (file.Block($"public {name}({string.Join(", ", parameters)})"))
				foreach (var member in members)
					file.Line($"{ResultTypes.PropertyOf(member, name)} = {ResultTypes.ParameterOf(member)};");

			foreach (var member in members)
			{
				file.Line();
				file.Line($"/// <summary>The <c>{member.Name}</c> capture.</summary>");
				file.Line($"public {Type(member)} {ResultTypes.PropertyOf(member, name)} {{ get; }}");
			}
		}
	}

	/// <summary>
	/// The methods a rule's <c>=&gt;</c> expressions become: the C# they named, with the
	/// captures as parameters.
	/// </summary>
	/// <remarks>
	/// <para>
	/// A method rather than an expression written where the value is assigned, and that
	/// is what makes the capture names usable at all — inside the machine they would have
	/// to dodge every local it has, and a capture called <c>p</c> or <c>state</c> would
	/// collide with the recognizer itself. Here they are parameters, in a scope of their
	/// own, named exactly as the grammar named them.
	/// </para>
	/// <para>
	/// One per alternative that carries a <c>=&gt;</c>, in the order they are written,
	/// which is the order the machine numbers them by.
	/// </para>
	/// </remarks>
	internal static IReadOnlyList<Machine.Factory> FactoriesOf(
		RecognitionGraph graph, ResultTypes results, RuleSymbol rule)
	{
		var name   = "Construct_" + IdentifierOf(rule);
		var fold   = graph.Folds.TryGetValue(rule, out var found0) ? found0 : null;
		var layout = LayoutOf(graph, results, rule);
		var found  = new List<Machine.Factory>();

		foreach (var node in Fold.Of(graph.Bodies[rule], fold))
		{
			if (node is not Node.Construct)
				continue;

			var from    = layout.Before(node);
			var to      = layout.After(node);
			var visible = new List<ResultMember>();

			// Only what this alternative could have captured, and optional only where this
			// alternative may skip it. A sibling's captures are neither its business nor
			// ever written when it is the one that matched.
			foreach (var member in graph.Results[rule])
			{
				var mine = new List<int>();

				foreach (var slot in member.Slots)
					if (slot >= from && slot < to)
						mine.Add(slot);

				if (mine.Count > 0)
					visible.Add(member with
					{
						Slots      = mine,
						IsOptional = !GrammarNormalizer.Writes(node, member.Name),
					});
			}

			found.Add(new Machine.Factory(
				node,
				found.Count == 0 ? name : name + "_" + found.Count,
				visible,
				fold is not null && fold.Accumulators.TryGetValue(node, out var accumulator)
					? accumulator
					: null));
		}

		return found;
	}

	/// <summary>Where a rule's captures are, with its fold loop known for what it is.</summary>
	static CaptureLayout LayoutOf(RecognitionGraph graph, ResultTypes results, RuleSymbol rule) =>
		CaptureLayout.Of(
			graph.Bodies[rule],
			other => results.QualifiedOf(other) is not null,
			graph.Folds.TryGetValue(rule, out var fold) ? fold.Loop : null);

	/// <summary>
	/// A line of the author's own C#, under a <c>#line</c> that points back at where they
	/// wrote it (§7.6).
	/// </summary>
	/// <remarks>
	/// <para>
	/// Everything else in this file is machine-written and an error in it is our bug. This
	/// is the exception: the text came from the grammar, the C# compiler will have things
	/// to say about it, and it must say them on the grammar's line. Without the directive
	/// the author is sent into a generated file they did not write and cannot edit.
	/// </para>
	/// <para>
	/// Padded out to the column too, and that is not decoration: an error under one
	/// argument of <c>@Add(l, r)</c> should sit under that argument. The line is written
	/// with no indent of its own so that the padding is the whole of the column.
	/// </para>
	/// <para>
	/// The plain form, not the span form C# 10 added: the consumer's language version is
	/// not ours to assume (.claude/rules/emitted-code.md).
	/// </para>
	/// </remarks>
	/// <remarks>
	/// Only an expression has text of its own; the four the language supplies are written
	/// by the cases above, which know what they are writing and where it is not from.
	/// </remarks>
	internal static void Handed(Writer file, ILineMap? lines, Node.Construct construct)
	{
		if (construct.How is Construction.Expression { Text: var text, At: var at })
			Handed(file, lines, at, text + ";");
	}

	internal static void Handed(Writer file, ILineMap? lines, int at, string text)
	{
		if (lines is null || at < 0 || !lines.TryMap(at, out var path, out var line, out var column))
		{
			file.Line("\t" + text);

			return;
		}

		file.Exactly($"#line {line.ToString(System.Globalization.CultureInfo.InvariantCulture)} \"{path}\"");
		file.Exactly(new string(' ', column - 1) + text);
		file.Exactly("#line default");
	}

	static void EmitFactory(
		Writer file, RecognitionGraph graph, RuleSymbol rule, Machine.Factory factory,
		ResultTypes results, ILineMap? lines)
	{
		var parameters = new List<string>();

		// What §8.2 supplies that a construction can want: what the rule matched, and where
		// it matched. Both are passed when the expression says so — a name found inside a
		// string literal costs an unused parameter, and reading it exactly would mean lexing
		// C# on this side. What it saves is not a parameter: the text is the whole of what
		// the rule matched, built as a string on every construction, and most expressions
		// want the captures inside rather than the run around them.
		if (WantsText(factory))
			parameters.Add("string parserText");

		if (Asks(factory, "parserSpan"))
			parameters.Add("SourceSpan parserSpan");

		// A fold step is handed the value built so far under the name it captured the
		// rule itself by (§4.3). It is not a capture any more — the rewrite took the call
		// away — so it is written in here rather than found among the members.
		if (factory.Accumulator is { Length: > 0 } accumulator)
			parameters.Add($"{graph.Types[rule]} {accumulator}");

		foreach (var member in factory.Members)
			if (member.Name != "parserText" && member.Name != factory.Accumulator)
				parameters.Add(
					results.ValueOf(member.Rule) +

					// A fold step is applied once per iteration and is handed that
					// iteration's captures, so what collects for the rule arrives here as
					// one of what it collected.
					(member.IsSequence && factory.Accumulator is null ? "[]" :
						member.IsOptional ? "?" : "") +

					" " + ResultTypes.ParameterOf(member));

		var head    = $"static {graph.Types[rule]} {factory.Method}({string.Join(", ", parameters)})";
		var summary = $"/// <summary>What <c>{rule.Name}</c> builds its value with";

		switch (((Node.Construct)factory.Of).How)
		{
			// The author's own C#, written under a `#line` pointing back at it (§7.6).
			case Construction.Expression:

				file.Line(summary + " (docs/syntax.md §7.3).</summary>");
				file.Line(head + " =>");
				Handed(file, lines, (Node.Construct)factory.Of);

				break;

			// §4.1 case 3: the value is one of the operands, handed back as it stands.
			case Construction.Operand:
			{
				var value = "default";

				foreach (var member in factory.Members)
					if (member.Name.StartsWith("item", StringComparison.Ordinal))
						value = ResultTypes.ParameterOf(member);

				file.Line(summary + ": what its operand was (§4.1 case 3).</summary>");
				file.Line(head + " =>");
				file.Line($"	{value};");

				break;
			}

			// §7.3's first way: the captures fill the declared type's constructor, in the
			// order the case carries.
			case Construction.Constructor(var order):
			{
				var arguments = new List<string>();

				foreach (var name in order)
					foreach (var member in factory.Members)
						if (member.Name == name)
							arguments.Add(ResultTypes.ParameterOf(member));

				file.Line(summary + " (§7.3).</summary>");
				file.Line(head + " =>");
				file.Line($"	new {graph.Types[rule]}({string.Join(", ", arguments)});");

				break;
			}

			// §7.3's second way: made, then written into. An object initializer rather than
			// assignments, because `init` and `required` can only be written in one.
			case Construction.Initializer(var bindings):
			{
				var written = new List<string>();

				foreach (var binding in bindings)
					foreach (var member in factory.Members)
						if (member.Name == binding.Capture)
							written.Add($"{binding.Property} = {ResultTypes.ParameterOf(member)}");

				file.Line(summary + " (§7.3).</summary>");
				file.Line(head + " =>");
				file.Line($"	new {graph.Types[rule]} {{ {string.Join(", ", written)} }};");

				break;
			}

			// §4.1 case 2: the grammar wrote no expression, so there is none to write out.
			// A body rather than an expression, because a repetition contributes an unknown
			// number of elements and an optional operand contributes none.
			case Construction.Sequence:
			{
				var element = graph.Types[rule].Substring(0, graph.Types[rule].Length - "[]".Length);

				file.Line($"/// <summary>Everything <c>{rule.Name}</c> is made of, in order (§4.1 case 2).</summary>");

				using (file.Block(head))
				{
					file.Line("var count = 0;");

					foreach (var member in factory.Members)
					{
						var value = ResultTypes.ParameterOf(member);

						if (member.IsSequence)
							file.Line($"if ({value} != null) count += {value}.Length;");
						else if (member.IsOptional)
							file.Line($"if ({value} != null) count++;");
						else
							file.Line("count++;");
					}

					file.Line();
					file.Line($"var items = new {element}[count];");
					file.Line("var at    = 0;");
					file.Line();

					foreach (var member in factory.Members)
					{
						var value = ResultTypes.ParameterOf(member);

						// A sequence capture already has its exact array. Copy it into this
						// rule's exact result rather than introducing a typed accumulator.
						if (member.IsSequence)
						{
							using (file.Block($"if ({value} != null)"))
							{
								file.Line($"global::System.Array.Copy({value}, 0, items, at, {value}.Length);");
								file.Line($"at += {value}.Length;");
							}
						}
						else if (member.IsOptional)
						{
							file.Line($"if ({value} != null)");
							file.Then($"items[at++] = ({element}){value};");
						}
						else
						{
							file.Line($"items[at++] = {value};");
						}
					}

					file.Line();
					file.Line("return items;");
				}

				break;
			}
		}
	}

	/// <summary>Whether a construction names one of the parameters §8.2 supplies.</summary>
	/// <summary>
	/// Whether a construction wants the text the rule matched — which it can say in two
	/// ways.
	/// </summary>
	/// <remarks>
	/// An expression says it by naming it, and that is the way there is a test for. The
	/// other, kept because <see cref="EmitFactory"/> has always left room for it, is a
	/// member of that name — how the forms of §7.3 that are not expressions would ask, if
	/// §7.3 matched a constructor against the supplied names as well as the captures. It
	/// does not today, so this arm is insurance rather than a feature.
	/// </remarks>
	internal static bool WantsText(Machine.Factory factory)
	{
		if (Asks(factory, "parserText"))
			return true;

		foreach (var member in factory.Members)
			if (member.Name == "parserText")
				return true;

		return false;
	}

	/// <summary>
	/// Whether a grammar names the one type §4.1 case 4 offers besides <c>string</c>.
	/// </summary>
	/// <remarks>
	/// Three ways to name it: a rule declaring it, a construction asking for the supplied
	/// <c>parserSpan</c>, and a <c>recover</c> factory, whose C# is written by the consumer
	/// and not read here. The last is taken on trust, which emits an unused type into a
	/// grammar that recovers and never asks — the direction that compiles.
	/// </remarks>
	static bool UsesSourceSpan(RecognitionGraph graph)
	{
		foreach (var type in graph.Types.Values)
			if (type == "SourceSpan")
				return true;

		foreach (var rule in graph.Rules)
			if (graph.Bodies.TryGetValue(rule, out var body))
				foreach (var node in NodeWalk.Descendants(body))
					if (node is Node.Construct { How: Construction.Expression { Text: var text } } &&
						text.Contains("parserSpan"))
					{
						return true;
					}

		return graph.Recoveries.Count > 0;
	}

	internal static bool Asks(Machine.Factory factory, string name) =>
		factory.Of is Node.Construct { How: Construction.Expression { Text: var text } } &&
		text.Contains(name);

	/// <summary>
	/// The repetition of a rule that was marked <c>recover</c>, the slot its elements
	/// collect into, and what it was told (§8.2).
	/// </summary>
	internal static (Node Repetition, Recovery Recovery, int Slot)? RecoveryIn(
		RecognitionGraph graph, ResultTypes results, RuleSymbol rule)
	{
		if (graph.Recoveries.Count == 0)
			return null;

		var layout = LayoutOf(graph, results, rule);

		return Find(graph.Bodies[rule], -1);

		// The capture is where a recovered element goes: the same sequence its successful
		// siblings collect into. It may be either side of the quantifier — `rows: Row*` is
		// `(rows: Row)*`, because a capture binds tighter (§10) — so both are looked at.
		(Node, Recovery, int)? Find(Node node, int slot)
		{
			if (node is Node.Repeat(var repeated, _, _) && graph.Recoveries.TryGetValue(node, out var recovery))
				return (node, recovery, slot >= 0 ? slot : repeated is Node.Capture ? layout.SlotOf(repeated) : -1);

			if (node is Node.Capture(_, var captured))
				return Find(captured, layout.SlotOf(node));

			foreach (var child in Children(node))
				if (Find(child, -1) is { } found)
					return found;

			return null;
		}
	}

	static IEnumerable<Node> Children(Node node) => node switch
	{
		Node.Sequence(var nodes)     => nodes,
		Node.Choice(var nodes)       => nodes,
		Node.Repeat(var body, _, _)  => [body],
		Node.Construct(var body, _)  => [body],
		Node.Atomic(var body)        => [body],
		_                            => [],
	};

	/// <summary>
	/// What a broken element becomes: the C# the <c>recover</c> named, with the extent it
	/// covered and where in the sequence it was.
	/// </summary>
	internal static void EmitRecoveryFactory(
		Writer file, ResultTypes results, RuleSymbol rule, string owner, Recovery recovery,
		RecognitionGraph graph, int slot)
	{
		var element    = LayoutOf(graph, results, rule).Slots[slot].Rule;
		var parameters = new List<string>();

		foreach (var name in recovery.Asks)
			parameters.Add(TypeOfSupplied(name) + " " + name);

		file.Line($"/// <summary>What <c>{rule.Name}</c> makes of an element it could not read.</summary>");
		file.Line(
			$"static {results.ValueOf(element)} {owner}_Recover({string.Join(", ", parameters)}) =>");
		file.Line("\t" + recovery.Factory + ";");
		file.Line();
	}

	/// <summary>Whether any <c>recover</c> in this grammar asked where its element was.</summary>
	/// <remarks>
	/// A <c>recover</c> without a <c>=&gt;</c> always asks: the hook it reports on takes
	/// the line and the column whether or not anybody implements it.
	/// </remarks>
	static bool Locating(RecognitionGraph graph)
	{
		foreach (var recovery in graph.Recoveries.Values)
		{
			if (recovery.Factory is null)
				return true;

			var asked = recovery.Asks;

			if (asked.Contains("parserLine") || asked.Contains("parserColumn"))
				return true;
		}

		return false;
	}

	/// <summary>Whether any <c>recover</c> in this grammar reports out of band (§8.3).</summary>
	static bool Reporting(RecognitionGraph graph)
	{
		foreach (var recovery in graph.Recoveries.Values)
			if (recovery.Factory is null)
				return true;

		return false;
	}

	/// <summary>
	/// The C# type of a name §8.2 supplies to a failure factory.
	/// </summary>
	/// <remarks>
	/// <c>position</c> is a <c>long</c> and everything else counting is an <c>int</c>,
	/// which is the frozen rule: an absolute offset is into the input, and an input may be
	/// a file larger than an <c>int</c> can index, while an extent is into a buffer and a
	/// buffer never is. A line number and an ordinal are counts of things in that file
	/// rather than positions in it, and nothing counts two billion lines.
	/// </remarks>
	static string TypeOfSupplied(string name) => name switch
	{
		"parserText" or "parserMessage" => "string",
		"parserSpan"                    => "SourceSpan",
		"parserPosition"                => "long",
		_                               => "int",
	};

	internal static string MethodOf(RuleSymbol rule) => "Recognize_" + IdentifierOf(rule);

	/// <summary>
	/// A rule's name as one C# identifier, unique across the grammar.
	/// </summary>
	/// <remarks>
	/// The short name is not unique and is not meant to be — shadowing is what a context
	/// is for, so a grammar with a <c>trivia</c> per context is the ordinary case rather
	/// than a clash. The contexts a rule is declared in are prefixed to tell them apart,
	/// named rather than numbered so that a reader of the generated code can still see
	/// which rule a method came from. The standard library's context is not an identifier
	/// and is left off: its names are fixed, and a grammar that shadows one of them takes
	/// the name with it.
	/// </remarks>
	internal static string IdentifierOf(RuleSymbol rule)
	{
		var name = rule.Name;

		for (var context = rule.Context; context is { Name.Length: > 0 }; context = context.Parent)
			if (IsIdentifier(context.Name))
				name = context.Name + "_" + name;

		return name;
	}

	static bool IsIdentifier(string name)
	{
		foreach (var c in name)
			if (!char.IsLetterOrDigit(c) && c != '_')
				return false;

		return true;
	}

	/// <summary>The recognizer that also insists the input ended — what `parse` calls.</summary>
	static string WholeOf(RuleSymbol rule) => MethodOf(rule) + "_Whole";

	internal static string Test(Node.Element element)
	{
		var tests = new List<string>();

		foreach (var range in element.Ranges)
			tests.Add(range.IsSingle
				? $"c == {Char(range.From)}"
				: $"(c >= {Char(range.From)} && c <= {Char(range.To)})");

		foreach (var category in element.Categories)
			// `\p{Lu}` is the regular-expression spelling; the enum member is
			// UppercaseLetter. `\p{L}` is not one category but five, so a group expands
			// into a test for each.
			foreach (var name in UnicodeCategories.Expand(category))
				tests.Add(
					"global::System.Globalization.CharUnicodeInfo.GetUnicodeCategory(c) == " +
					$"global::System.Globalization.UnicodeCategory.{name}");

		// §7.1's element predicate: `bool M(char c)` asks the same question about one item
		// that a range does, so it joins the set as one more test. Written as the grammar
		// wrote it — the grammar's own `@using` directives are in the file, which is what
		// they are there for — rather than qualified, which nothing here could do.
		foreach (var reference in element.References)
			if (reference is CSharpSymbol predicate)
				tests.Add($"{predicate.Name}(c)");

		// An empty set admits nothing, and its complement admits everything. Said as
		// constants rather than as `!(false)`, so the caller can drop the test — and with
		// it the character it would otherwise read and never look at.
		if (tests.Count == 0)
			return element.IsNegated ? "true" : "false";

		var test = string.Join(" || ", tests);

		return element.IsNegated ? $"!({test})" : $"({test})";
	}

	/// <summary>
	/// A char as a C# character literal.
	/// </summary>
	/// <remarks>
	/// Everything outside plain printable ASCII goes out as <c>\uXXXX</c>. Putting the
	/// character itself into the file would work for most of them and produce a source
	/// file with a raw control character in it for the rest — and the emitted text is
	/// read by people, not only by a compiler.
	/// </remarks>
	internal static string Char(char value) => value switch
	{
		'\''                         => @"'\''",
		'\\'                         => @"'\\'",
		>= ' ' and <= '~'            => $"'{value}'",
		'\0'                         => @"'\0'",
		'\a'                         => @"'\a'",
		'\b'                         => @"'\b'",
		'\f'                         => @"'\f'",
		'\n'                         => @"'\n'",
		'\r'                         => @"'\r'",
		'\t'                         => @"'\t'",
		'\v'                         => @"'\v'",
		_                            => $@"'\u{(int)value:X4}'",
	};
}
