using System;
using System.Collections.Generic;
using System.Text;

using DotGram.Grammar.Binding;
using DotGram.Grammar.Model;
using DotGram.Grammar.Parsing;

namespace DotGram.Grammar.Emit;

/// <summary>Indent-aware output. One per generated function, so nothing interleaves.</summary>
sealed class Writer(int depth)
{
	readonly StringBuilder _text = new();

	int _depth = depth;

	/// <summary>How far in the next line will be written — what a nested writer starts at.</summary>
	public int Depth => _depth;

	public void Line(string text = "")
	{
		if (text.Length == 0)
			_text.EndLine();
		else
			_text.Append('\t', _depth).AppendEndingWith(text);
	}

	/// <summary>A single indented line — the body of an <c>if</c> without braces.</summary>
	public void Then(string text)
	{
		_depth++;
		Line(text);
		_depth--;
	}

	public IDisposable Block(string header)
	{
		Line(header);
		Line("{");
		_depth++;

		return new Closer(this);
	}

	/// <summary>Indents what follows, without braces around it — a switch section.</summary>
	public IDisposable Indent()
	{
		_depth++;

		return new Outdenter(this);
	}

	public void Append(Writer other) => _text.Append(other._text);

	/// <summary>Writes text that is already laid out, each line at the current depth.</summary>
	public void Write(string text)
	{
		var written = new Writer(0);

		written._text.Append(text);

		// AppendIndented reads the text as lines, each closed by an ending. Text that
		// does not end with one — a raw string literal, say — would lose its last line.
		if (!text.EndsWith(Lines.Ending, StringComparison.Ordinal))
			written._text.Append(Lines.Ending);

		AppendIndented(written, 0);
	}

	/// <summary>Appends another writer's text, shifted in to this one's depth.</summary>
	public void AppendIndented(Writer other, int extra = 1)
	{
		var lines = other._text.ToString().Split([Lines.Ending], StringSplitOptions.None);

		// The text ends with an ending, so the split leaves a final empty piece that is
		// not a line at all.
		for (var i = 0; i < lines.Length - 1; i++)
			if (lines[i].Length > 0)
				_text.Append('\t', _depth + extra).AppendEndingWith(lines[i]);
			else
				_text.EndLine();
	}

	public override string ToString() => _text.ToString();

	sealed class Closer(Writer writer) : IDisposable
	{
		public void Dispose()
		{
			writer._depth--;
			writer.Line("}");
		}
	}

	sealed class Outdenter(Writer writer) : IDisposable
	{
		public void Dispose() => writer._depth--;
	}
}

/// <summary>
/// Turns a recognition graph into C#.
/// </summary>
/// <remarks>
/// <para>
/// One method per rule, and inside it one static local function per node. Every one of
/// them has the same shape — take the input and a position, return the new position or
/// -1 — so composing them is just calling them, and there is nothing to allocate,
/// nothing virtual, and no closure. Static local functions specifically, because a
/// closure cannot hold a <c>ReadOnlySpan</c>.
/// </para>
/// <para>
/// This is the fast path over the frozen subset of docs/implementation.md §11:
/// sequence, ordered choice, quantifiers, element sets, literals, rule calls. No
/// trivia, no result construction, no recovery yet — a rule's value is the text it
/// matched.
/// </para>
/// </remarks>
public static class CSharpEmitter
{
	/// <param name="graph">The normalized grammar.</param>
	/// <param name="className">
	/// The partial class the generated members go into. A nested host is named by its
	/// chain — <c>Outer.Inner</c> — and written back out nested.
	/// </param>
	/// <param name="namespace">Its namespace, or null for the global one.</param>
	public static string Emit(RecognitionGraph graph, string className, string? @namespace = null)
	{
		if (graph is null)
			throw new ArgumentNullException(nameof(graph));

		var file  = new Writer(0);
		var scope = new Stack<IDisposable>();

		file.Line("// <auto-generated/>");
		file.Line("#nullable enable");
		file.Line();

		// A block namespace rather than a file-scoped one: the consumer's language
		// version is unknown (.claude/rules/emitted-code.md).
		if (@namespace is not null)
			scope.Push(file.Block($"namespace {@namespace}"));

		foreach (var name in className.Split('.'))
			scope.Push(file.Block($"partial class {name}"));

		foreach (var publication in graph.Publications)
		{
			EmitPublication(file, publication);
			file.Line();
		}

		var needsStack = false;

		// `parse` demands the input end. Asking the rule and then checking would leave it
		// unable to go back for a longer match — the check has to be inside the machine,
		// where failing it is an ordinary failure and the stack still has somewhere to
		// resume. So the rule's body is compiled again, with end-of-input on the end.
		foreach (var publication in graph.Publications)
		{
			if (publication.Kind != PublishKind.Parse)
				continue;

			var whole = new Machine(WholeOf(publication.Rule));
			var body  = new Node.Sequence([graph.Bodies[publication.Rule], EndOfInput]);

			file.Write(whole.Render(whole.Compile(body, Machine.Accept)));
			file.Line();

			foreach (var extra in whole.Extra)
			{
				file.Write(extra);
				file.Line();
			}

			needsStack = true;
		}

		foreach (var rule in graph.Rules)
		{
			needsStack |= EmitRule(file, graph, rule);
			file.Line();
		}

		if (needsStack)
			file.Write(GrowHelper);

		while (scope.Count > 0)
			scope.Pop().Dispose();

		return file.ToString();
	}

	/// <summary>
	/// One directive, one pair of methods, in the shape of <c>int.Parse</c> /
	/// <c>int.TryParse</c> (docs/syntax.md §6).
	/// </summary>
	/// <remarks>
	/// A rule's value is still the text it matched, so everything here is <c>string</c>.
	/// When construction lands, only these signatures change — what they are built on,
	/// a recognizer returning an end position or -1, does not.
	/// </remarks>
	static void EmitPublication(Writer file, Publication publication)
	{
		var method   = publication.MethodName;
		var name     = publication.Rule.Name;
		var isAll    = publication.Kind == PublishKind.FindAll;
		var result   = isAll ? "string[]" : publication.Kind == PublishKind.Parse ? "string" : "string?";
		var outType  = isAll ? "string[]" : "string";
		var outName  = isAll ? "values" : "value";

		file.Line($"/// <summary>{Summary(publication.Kind, name)}</summary>");

		using (file.Block($"public static {result} {method}(string input)"))
		{
			file.Line($"if (Try{method}(input, out var {outName}, out var error, out var errorPosition))");
			file.Then($"return {outName};");
			file.Line();

			// Only `parse` throws: it is the one directive that asserts the input is this
			// rule, so failing it is an error rather than an answer of "no".
			if (publication.Kind == PublishKind.Parse)
				file.Line("throw new global::System.FormatException(error + \" at \" + errorPosition.ToString());");
			else
				file.Line(isAll ? "return new string[0];" : "return null;");
		}

		file.Line();

		using (file.Block(
			$"public static bool Try{method}(string input, out {outType} {outName}, out string? error, out int errorPosition)"))
		{
			// Fully qualified, and as a static call rather than an extension method:
			// the emitted file carries no usings at all (.claude/rules/emitted-code.md).
			file.Line("var text = global::System.MemoryExtensions.AsSpan(input);");
			file.Line();
			file.Line($"{outName} = {(isAll ? "new string[0]" : "\"\"")};");
			file.Line("error         = null;");
			file.Line("errorPosition = 0;");
			file.Line();

			switch (publication.Kind)
			{
				case PublishKind.Parse:
				case PublishKind.Match:

					// The difference between the two directives, and the whole of it: one
					// calls the recognizer that also insists the input ended.
					var entry = publication.Kind == PublishKind.Parse
						? WholeOf(publication.Rule)
						: MethodOf(publication.Rule);

					file.Line($"var end = {entry}(text, 0);");
					file.Line();

					using (file.Block("if (end < 0)"))
					{
						file.Line($"error = \"Input does not match '{name}'.\";");
						file.Line("return false;");
					}

					file.Line();
					file.Line("value = input.Substring(0, end);");
					file.Line("return true;");
					break;

				case PublishKind.Find:

					using (file.Block("for (var start = 0; start <= input.Length; start++)"))
					{
						file.Line($"var end = {MethodOf(publication.Rule)}(text, start);");
						file.Line();

						using (file.Block("if (end >= 0)"))
						{
							file.Line("value = input.Substring(start, end - start);");
							file.Line("return true;");
						}
					}

					file.Line();
					file.Line($"error = \"No occurrence of '{name}'.\";");
					file.Line("return false;");
					break;

				default:

					file.Line("var found = new global::System.Collections.Generic.List<string>();");
					file.Line();

					using (file.Block("for (var start = 0; start <= input.Length; )"))
					{
						file.Line($"var end = {MethodOf(publication.Rule)}(text, start);");
						file.Line();

						using (file.Block("if (end < 0)"))
						{
							file.Line("start++;");
							file.Line("continue;");
						}

						file.Line();
						file.Line("found.Add(input.Substring(start, end - start));");
						file.Line();
						file.Line("// A rule that matches nothing would otherwise find it for ever.");
						file.Line("start = end > start ? end : start + 1;");
					}

					file.Line();

					using (file.Block("if (found.Count == 0)"))
					{
						file.Line($"error = \"No occurrence of '{name}'.\";");
						file.Line("return false;");
					}

					file.Line();
					file.Line("values = found.ToArray();");
					file.Line("return true;");
					break;
			}
		}
	}

	static string Summary(PublishKind kind, string rule) => kind switch
	{
		PublishKind.Parse   => $"Parses the whole input as <c>{rule}</c>.",
		PublishKind.Match   => $"Matches <c>{rule}</c> at the start of the input.",
		PublishKind.Find    => $"Finds the first occurrence of <c>{rule}</c>.",
		_                   => $"Finds every non-overlapping occurrence of <c>{rule}</c>.",
	};

	/// <summary>One rule, and whether it needed the shared stack helper.</summary>
	static bool EmitRule(Writer file, RecognitionGraph graph, RuleSymbol rule)
	{
		var machine = new Machine(MethodOf(rule));
		var entry   = machine.Compile(graph.Bodies[rule], Machine.Accept);
		var text    = machine.Render(entry);

		foreach (var extra in machine.Extra)
		{
			file.Write(extra);
			file.Line();
		}

		file.Write(text);

		return machine.UsesStack || machine.Extra.Count > 0;
	}

	internal static string MethodOf(RuleSymbol rule) => $"Recognize_{rule.Name.Replace('.', '_')}";

	/// <summary>The recognizer that also insists the input ended — what `parse` calls.</summary>
	static string WholeOf(RuleSymbol rule) => MethodOf(rule) + "_Whole";

	/// <summary>
	/// End of input: the complement of everything, not present. The same node `eof`
	/// lowers to, built here rather than looked up so that a grammar which never
	/// mentions `eof` still gets one.
	/// </summary>
	static Node EndOfInput =>
		new Node.Lookahead(IsPositive: false, new Node.Element(IsNegated: true, [], [], []));

	/// <summary>
	/// Grows the backtracking stack. Emitted once per class, next to the recognizers
	/// that share it.
	/// </summary>
	internal const string GrowHelper = """
		static int[] Grow(global::System.Span<int> from)
		{
			var bigger = new int[from.Length * 2];

			from.CopyTo(bigger);

			return bigger;
		}
		""";

	internal static string Test(Node.Element element)
	{
		var tests = new List<string>();

		foreach (var range in element.Ranges)
			tests.Add(range.IsSingle
				? $"c == {Char(range.From)}"
				: $"(c >= {Char(range.From)} && c <= {Char(range.To)})");

		foreach (var category in element.Categories)
			// `\p{Lu}` is the regular-expression spelling; the enum member is
			// UppercaseLetter. `\p{L}` is not one category but five, so a group expands
			// into a test for each.
			foreach (var name in UnicodeCategories.Expand(category))
				tests.Add(
					"global::System.Globalization.CharUnicodeInfo.GetUnicodeCategory(c) == " +
					$"global::System.Globalization.UnicodeCategory.{name}");

		// An empty set admits nothing, and its complement admits everything. Said as
		// constants rather than as `!(false)`, so the caller can drop the test — and with
		// it the character it would otherwise read and never look at.
		if (tests.Count == 0)
			return element.IsNegated ? "true" : "false";

		var test = string.Join(" || ", tests);

		return element.IsNegated ? $"!({test})" : $"({test})";
	}

	/// <summary>
	/// A char as a C# character literal.
	/// </summary>
	/// <remarks>
	/// Everything outside plain printable ASCII goes out as <c>\uXXXX</c>. Putting the
	/// character itself into the file would work for most of them and produce a source
	/// file with a raw control character in it for the rest — and the emitted text is
	/// read by people, not only by a compiler.
	/// </remarks>
	internal static string Char(char value) => value switch
	{
		'\''                         => @"'\''",
		'\\'                         => @"'\\'",
		>= ' ' and <= '~'            => $"'{value}'",
		'\0'                         => @"'\0'",
		'\a'                         => @"'\a'",
		'\b'                         => @"'\b'",
		'\f'                         => @"'\f'",
		'\n'                         => @"'\n'",
		'\r'                         => @"'\r'",
		'\t'                         => @"'\t'",
		'\v'                         => @"'\v'",
		_                            => $@"'\u{(int)value:X4}'",
	};
}
