using System;

namespace DotGram.Grammar.Emit;

/// <summary>
/// Everything the generator emits before it has looked at anything: the attribute a
/// grammar is attached with, and the one type a generated parser needs that is worth
/// having once per assembly rather than once per host class.
/// </summary>
/// <remarks>
/// <para>
/// All of it <c>internal</c>, which is the whole of why .Gram needs no runtime assembly
/// and no way of finding one. An internal type is invisible across an assembly boundary,
/// so two assemblies each emitting <c>DotGram.SourceSpan</c> do not collide, do not have
/// to agree, and have nothing to version.
/// </para>
/// <para>
/// It was not always so. There used to be four support types here, emitted <c>public</c>
/// when an assembly declared <c>[assembly: GramRuntime]</c> so that others could bind to
/// them instead of emitting their own — which needed a probe for a type by name, three
/// emission modes, a diagnostic for two publishers, and reintroduced exactly the
/// generator-of-one-version, runtime-of-another skew that emitting into the consumer was
/// supposed to remove. Three of the four types were used by nothing at all, and the
/// fourth appears only in the private signature of a recovery factory. They are gone;
/// when a type genuinely has to cross a boundary, it can come back with a contract to
/// version and a reason to exist.
/// </para>
/// </remarks>
public static class SupportEmitter
{
	/// <summary>Emitted from post-initialization, in every assembly, unconditionally.</summary>
	/// <remarks>
	/// Before any compilation analysis, so that <c>[Gram]</c> can be written in source at
	/// all — the attribute has to exist before the code that uses it can be looked at.
	/// </remarks>
	public const string Attributes = """
		// <auto-generated/>
		#nullable enable

		namespace DotGram
		{
			/// <summary>Marks a partial class as the host of a grammar.</summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramAttribute : global::System.Attribute
			{
				public GramAttribute() { }

				/// <param name="source">
				/// A path to a .gram file, or the grammar text itself. A single-line value
				/// ending in ".gram" is a path; anything else is grammar text.
				/// </param>
				public GramAttribute(string source) => Source = source;

				public string? Source { get; }
			}

			/// <summary>
			/// Half-open range of the input: [Start, End).
			/// </summary>
			/// <remarks>
			/// What a <c>recover</c> factory asking for <c>span</c> is handed (docs/syntax.md
			/// §8.2). Ours rather than <c>System.Range</c> because a consumer building for an
			/// older framework very likely polyfills that one, and two definitions of it in a
			/// compilation is an error.
			/// </remarks>
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal readonly struct SourceSpan
			{
				public SourceSpan(int start, int length)
				{
					Start  = start;
					Length = length;
				}

				/// <summary>Where it begins.</summary>
				public int Start { get; }

				/// <summary>How much of the input it covers.</summary>
				public int Length { get; }

				/// <summary>One past the last item, so an empty span has End equal to Start.</summary>
				public int End => Start + Length;

				public override string ToString() => "[" + Start + ".." + End + ")";
			}
		}
		""";
}
