using System;

namespace DotGram.Grammar.Emit;

/// <summary>
/// Everything the generator emits before it has looked at anything: the attribute a
/// grammar is attached with, and the ones a grammar's author annotates it for tooling
/// with.
/// </summary>
/// <remarks>
/// <para>
/// All of it is <c>internal</c>, which is the whole of why .Gram needs no runtime assembly
/// and no way of finding one. An internal type is invisible across an assembly boundary,
/// so two assemblies each emitting <c>DotGram.GramAttribute</c> do not collide, do not
/// have to agree, and have nothing to version.
/// </para>
/// <para>
/// The tooling attributes are read rather than executed, and by name rather than by type
/// identity — an editor asking what language a referenced assembly's parser speaks looks
/// at metadata through Roslyn, where <c>internal</c> is visible, and never loads the
/// assembly to ask it (docs/DotGram_Tooling_Agent_Handoff.md §21, §26). That is what lets
/// each assembly carry its own copy of these and still be understood by one tool.
/// </para>
/// <para>
/// <c>SourceSpan</c> used to be here beside it, and for the same reason — but internal is
/// exactly what stopped a parser from handing one back, since an internal type cannot be
/// what a public method returns. It is now emitted into each host class instead, where it
/// is <c>public</c> and its name is the host's, so two of them still cannot collide and a
/// caller can be given one. That is the same trade the generated value types already make.
/// </para>
/// <para>
/// It was not always so. There used to be four support types here, emitted <c>public</c>
/// when an assembly declared <c>[assembly: GramRuntime]</c> so that others could bind to
/// them instead of emitting their own — which needed a probe for a type by name, three
/// emission modes, a diagnostic for two publishers, and reintroduced exactly the
/// generator-of-one-version, runtime-of-another skew that emitting into the consumer was
/// supposed to remove. Three of the four types were used by nothing at all, and the
/// fourth appears only in the private signature of a recovery factory. They are gone;
/// when a type genuinely has to cross a boundary, it can come back with a contract to
/// version and a reason to exist.
/// </para>
/// </remarks>
public static class SupportEmitter
{
	/// <summary>Emitted from post-initialization, in every assembly, unconditionally.</summary>
	/// <remarks>
	/// Before any compilation analysis, so that <c>[Gram]</c> can be written in source at
	/// all — the attribute has to exist before the code that uses it can be looked at.
	/// </remarks>
	public const string Attributes = """
		// <auto-generated/>
		#nullable enable

		namespace DotGram
		{
			/// <summary>Marks a partial class as the host of a grammar.</summary>
			/// <remarks>
			/// More than one may be written, and then all but one need a <c>Suffix</c>: each
			/// is a compilation of its own, in a nested class of that name and in a file of
			/// its own. That is how one host offers the same grammar compiled two ways —
			/// two carriers, say — for a caller to choose between.
			/// </remarks>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramAttribute : global::System.Attribute
			{
				public GramAttribute() { }

				/// <param name="source">
				/// A path to a .gram file, or the grammar text itself. A single-line value
				/// ending in ".gram" is a path; anything else is grammar text.
				/// </param>
				public GramAttribute(string source) => Source = source;

				public string? Source { get; }

				/// <summary>
				/// The name another grammar includes this one under, where that should not
				/// be the class's own.
				/// </summary>
				/// <remarks>
				/// One identifier, and not a namespace of the generated code — that is
				/// decided by where the host class is declared. This is the name written
				/// after `using` in a grammar that includes this one, and it defaults to
				/// the host's own so that following the `:` from the including class lands
				/// on the answer.
				/// </remarks>
				public string? IncludedAs { get; set; }

				/// <summary>
				/// The nested class this compilation goes into, where the host has more
				/// than one. One identifier; the host class itself where nothing is said.
				/// </summary>
				/// <remarks>
				/// Two compilations cannot share a scope — a file's support is written
				/// once and named for what it is — so the second gets a class, and its
				/// parse methods are reached through it: <c>Sql.Immediate.TryParseR</c>.
				/// What the host declares is still in reach from inside, a nested class
				/// reading the static members around it by their simple names.
				/// </remarks>
				public string? Suffix { get; set; }

				/// <summary>
				/// How large the parts of a divided recognizer are aimed to be, in the
				/// generator's estimate of basic blocks. Zero takes the measured default.
				/// </summary>
				/// <remarks>
				/// A recognizer too large for one method is written in several, and how
				/// large each should be was measured flat anywhere between sixty and two
				/// hundred and fifty — flat, but on grammars that are not yours. Set this
				/// where yours turns out to want something else.
				///
				/// It is a wish rather than a setting: every value generates a parser.
				/// Below one asks for the finest division there is, past the size of the
				/// recognizer asks for one part, and nothing written here can fail a
				/// build.
				/// </remarks>
				public int PartSize { get; set; }

				/// <summary>
				/// Compile as methods where the automaton is not needed. On unless set off;
				/// off keeps the automaton for every publication.
				/// </summary>
				public bool Direct { get; set; } = true;

				/// <summary>
				/// Read the input as tokens rather than as characters.
				/// </summary>
				/// <remarks>
				/// The grammar is cut in two: a lexical machine over characters that
				/// answers with token kinds, and the same syntactic machine over those
				/// (docs/lexical-adt-design.md). Nothing about the grammar changes and
				/// nothing about the published methods changes — they take a string and
				/// answer as they did.
				///
				/// Off by default and a request rather than a setting: a grammar that
				/// cannot be cut is compiled over characters and told why. What cannot
				/// be cut is a grammar with no trivia at all — a URL is characters and
				/// there is nothing to gain — one whose terminals are not regular
				/// languages, one that publishes `find`, and one whose `trivia` is not
				/// written in braces, since the seam is skipped by the scanner those
				/// braces ask for.
				///
				/// Worth it where the input is long or is refused: measured against the
				/// character machine on standard SQL, an accepted condition runs 1.05 to
				/// 2.45 times faster and a refused one 1.35 to 3.85, the gain growing
				/// with the input because the syntactic machine reads a fifth as many
				/// items and keeps a fifth as many ways back.
				/// </remarks>
				public bool Lexical { get; set; }

				/// <summary>
				/// How the reader carries what it has read until the constructions run.
				/// </summary>
				/// <remarks>
				/// The tape unless set, which keeps §7.3: a construction runs once, for the
				/// derivation that was accepted. The others are the author's to choose, and
				/// what each gives up is written on it. A grammar the chosen carrier cannot
				/// carry is compiled on the tape.
				/// </remarks>
				public GramCarrier Carrier { get; set; }

				/// <summary>
				/// How many stacks one parse may take beyond the one it began on.
				/// </summary>
				/// <remarks>
				/// A grammar that recurses on input the author did not write can be handed a
				/// thousand brackets. Where the stack it is reading on runs low the reading
				/// carries on over a stack of its own, and a reading deep enough to run that
				/// one low takes another — by default for as long as there is memory to take
				/// one with.
				///
				/// Set it to say how many is enough. Past that many the parse fails with
				/// `InsufficientExecutionStackException`, which is what it always did. Zero,
				/// the default, is no limit; one is a single extra stack; a reading that never
				/// goes deep takes none whatever this says.
				/// </remarks>
				public int Stacks { get; set; }

				/// <summary>
				/// An interface whose implementors are told where they were written.
				/// </summary>
				/// <remarks>
				/// Nothing written here changes what is read; it changes what a value knows
				/// about itself. Name an interface with a settable property called
				/// <c>Span</c>, and every rule whose value implements it is handed the range
				/// of input it was built from — the rule's own text, without the trivia
				/// around it, so that a comment falls between two of them rather than inside
				/// one.
				///
				/// What that buys is everything a parse cannot answer on its own: which
				/// characters a diagnostic is about, which node a comment belongs to, and
				/// what a formatter or a rewriter may leave alone. A grammar that says
				/// nothing here pays nothing — a recognizer wants no positions, and most
				/// grammars are recognizers.
				///
				/// The property is written once, by the reader, on a value it has just made
				/// and nothing has yet seen.
				/// </remarks>
				public global::System.Type? LocationType { get; set; }
			}

			/// <summary>How a generated reader carries what it has read (docs/next.md, the redesign).</summary>
			internal enum GramCarrier
			{
				/// <summary>Records on a tape, built into values once the parse is accepted. The default.</summary>
				Tape,

				/// <summary>
				/// No deferral: a construction runs the moment its alternative has been read,
				/// and one abandoned afterwards has already run. Once per derivation tried
				/// rather than once per derivation accepted — invisible to a pure allocation,
				/// visible to a counter. For factories the author knows to be pure.
				/// </summary>
				Immediate,

				/// <summary>
				/// Deferral without a tape: what a rule read is kept in a typed shape of
				/// its own, and the constructions run over those shapes once the parse is
				/// accepted. Keeps §7.3 as the tape does — a factory runs once per node of
				/// the accepted derivation — and pays for it in fields of a known type
				/// rather than in a log and a walk over it.
				/// </summary>
				/// <remarks>
				/// A grammar it cannot carry is compiled on the tape and told why. What it
				/// does not carry: a rule whose value is the extent it matched, a recovery,
				/// a mark (§7.8), and a rule read at a strength.
				/// </remarks>
				Mixed,
			}

			/// <summary>
			/// What a rule or a capture means, as a role rather than a colour: an editor's
			/// theme decides how an identifier looks, and this says only that something is
			/// one.
			/// </summary>
			internal enum GramClassification
			{
				Keyword,
				Identifier,
				Type,
				Variable,
				Function,
				Method,
				Property,
				Number,
				String,
				Comment,
				Operator,
				Punctuation,
				Namespace,
				Parameter,
				Label,
			}

			/// <summary>Names the language a grammar describes, for tooling to discover.</summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramLanguageAttribute : global::System.Attribute
			{
				/// <param name="id">
				/// A stable identifier for the language, unique to whoever owns it — a reverse
				/// domain name is the usual shape.
				/// </param>
				public GramLanguageAttribute(string id) => Id = id;

				public string Id { get; }

				/// <summary>File extensions this language claims, with the dot.</summary>
				public string[]? Extensions { get; set; }
			}

			/// <summary>
			/// Gives a rule or one of its captures a semantic role.
			/// </summary>
			/// <remarks>
			/// A rule's own classification is the default for every use of it; a capture's
			/// overrides that default where the two disagree. `Declaration.type` and
			/// `Declaration.name` may both be `Identifier` rules and mean different things.
			/// </remarks>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramClassifyAttribute : global::System.Attribute
			{
				/// <param name="target">
				/// A rule name — <c>Keyword</c> — or a capture of one — <c>Declaration.type</c>.
				/// </param>
				/// <param name="role">What it means, for an editor to present as it likes.</param>
				public GramClassifyAttribute(string target, GramClassification role)
				{
					Target = target;
					Role   = role;
				}

				public string             Target { get; }
				public GramClassification Role   { get; }
			}

			/// <summary>Declares a non-executing editor decision for a grammar guard.</summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramToolingGuardAttribute : global::System.Attribute
			{
				public GramToolingGuardAttribute(string expression, bool accepted)
				{
					Expression = expression;
					Accepted   = accepted;
				}

				public string Expression { get; }
				public bool Accepted { get; }
			}

			/// <summary>Maps an external recognizer to an equivalent grammar rule for editors.</summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramToolingExternalAttribute : global::System.Attribute
			{
				public GramToolingExternalAttribute(string method, string rule)
				{
					Method = method;
					Rule   = rule;
				}

				public string Method { get; }
				public string Rule { get; }
			}

			/// <summary>Locates the versioned language descriptor carried by a generated parser.</summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramLanguageDescriptorAttribute : global::System.Attribute
			{
				public GramLanguageDescriptorAttribute(
					int formatVersion,
					string languageId,
					string grammarHash,
					string sourcePayload,
					string entriesPayload)
				{
					FormatVersion = formatVersion;
					LanguageId    = languageId;
					GrammarHash   = grammarHash;
					SourcePayload  = sourcePayload;
					EntriesPayload = entriesPayload;
				}

				public GramLanguageDescriptorAttribute(
					int formatVersion,
					string languageId,
					string grammarHash,
					string sourcePayload,
					string entriesPayload,
					string classificationsPayload)
					: this(formatVersion, languageId, grammarHash, sourcePayload, entriesPayload) =>
					ClassificationsPayload = classificationsPayload;

				public GramLanguageDescriptorAttribute(
					int formatVersion,
					string languageId,
					string grammarHash,
					string sourcePayload,
					string entriesPayload,
					string classificationsPayload,
					string recognitionContractPayload)
					: this(formatVersion, languageId, grammarHash, sourcePayload, entriesPayload, classificationsPayload) =>
					RecognitionContractPayload = recognitionContractPayload;

				public int FormatVersion { get; }
				public string LanguageId { get; }
				public string GrammarHash { get; }
				public string SourcePayload { get; }
				public string EntriesPayload { get; }
				public string? ClassificationsPayload { get; }
				public string? RecognitionContractPayload { get; }
			}

		}
		""";
}
