using System;

namespace DotGram.Grammar.Emit;

/// <summary>
/// Everything the generator emits before it has looked at anything: the attribute a
/// grammar is attached with, and the ones a grammar's author annotates it for tooling
/// with.
/// </summary>
/// <remarks>
/// <para>
/// All of it is <c>internal</c>, which is the whole of why .Gram needs no runtime assembly
/// and no way of finding one. An internal type is invisible across an assembly boundary,
/// so two assemblies each emitting <c>DotGram.GramAttribute</c> do not collide, do not
/// have to agree, and have nothing to version.
/// </para>
/// <para>
/// The tooling attributes are read rather than executed, and by name rather than by type
/// identity — an editor asking what language a referenced assembly's parser speaks looks
/// at metadata through Roslyn, where <c>internal</c> is visible, and never loads the
/// assembly to ask it (docs/DotGram_Tooling_Agent_Handoff.md §21, §26). That is what lets
/// each assembly carry its own copy of these and still be understood by one tool.
/// </para>
/// <para>
/// <c>SourceSpan</c> used to be here beside it, and for the same reason — but internal is
/// exactly what stopped a parser from handing one back, since an internal type cannot be
/// what a public method returns. It is now emitted into each host class instead, where it
/// is <c>public</c> and its name is the host's, so two of them still cannot collide and a
/// caller can be given one. That is the same trade the generated value types already make.
/// </para>
/// <para>
/// It was not always so. There used to be four support types here, emitted <c>public</c>
/// when an assembly declared <c>[assembly: GramRuntime]</c> so that others could bind to
/// them instead of emitting their own — which needed a probe for a type by name, three
/// emission modes, a diagnostic for two publishers, and reintroduced exactly the
/// generator-of-one-version, runtime-of-another skew that emitting into the consumer was
/// supposed to remove. Three of the four types were used by nothing at all, and the
/// fourth appears only in the private signature of a recovery factory. They are gone;
/// when a type genuinely has to cross a boundary, it can come back with a contract to
/// version and a reason to exist.
/// </para>
/// </remarks>
public static class SupportEmitter
{
	/// <summary>Emitted from post-initialization, in every assembly, unconditionally.</summary>
	/// <remarks>
	/// Before any compilation analysis, so that <c>[Gram]</c> can be written in source at
	/// all — the attribute has to exist before the code that uses it can be looked at.
	/// </remarks>
	public const string Attributes = """
		// <auto-generated/>
		#nullable enable

		namespace DotGram
		{
			/// <summary>Marks a partial class as the host of a grammar.</summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramAttribute : global::System.Attribute
			{
				public GramAttribute() { }

				/// <param name="source">
				/// A path to a .gram file, or the grammar text itself. A single-line value
				/// ending in ".gram" is a path; anything else is grammar text.
				/// </param>
				public GramAttribute(string source) => Source = source;

				public string? Source { get; }
			}

			/// <summary>
			/// What a rule or a capture means, as a role rather than a colour: an editor's
			/// theme decides how an identifier looks, and this says only that something is
			/// one.
			/// </summary>
			internal enum GramClassification
			{
				Keyword,
				Identifier,
				Type,
				Variable,
				Function,
				Method,
				Property,
				Number,
				String,
				Comment,
				Operator,
				Punctuation,
				Namespace,
				Parameter,
				Label,
			}

			/// <summary>Names the language a grammar describes, for tooling to discover.</summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramLanguageAttribute : global::System.Attribute
			{
				/// <param name="id">
				/// A stable identifier for the language, unique to whoever owns it — a reverse
				/// domain name is the usual shape.
				/// </param>
				public GramLanguageAttribute(string id) => Id = id;

				public string Id { get; }

				/// <summary>File extensions this language claims, with the dot.</summary>
				public string[]? Extensions { get; set; }
			}

			/// <summary>
			/// Gives a rule or one of its captures a semantic role.
			/// </summary>
			/// <remarks>
			/// A rule's own classification is the default for every use of it; a capture's
			/// overrides that default where the two disagree. `Declaration.type` and
			/// `Declaration.name` may both be `Identifier` rules and mean different things.
			/// </remarks>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramClassifyAttribute : global::System.Attribute
			{
				/// <param name="target">
				/// A rule name — <c>Keyword</c> — or a capture of one — <c>Declaration.type</c>.
				/// </param>
				/// <param name="role">What it means, for an editor to present as it likes.</param>
				public GramClassifyAttribute(string target, GramClassification role)
				{
					Target = target;
					Role   = role;
				}

				public string             Target { get; }
				public GramClassification Role   { get; }
			}

			/// <summary>
			/// Associates this generated language with a user attribute that marks string
			/// parameters whose arguments are written in the language.
			/// </summary>
			[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal sealed class GramEmbeddedLanguageAttribute : global::System.Attribute
			{
				/// <param name="marker">An attribute type applied to DSL-bearing string parameters.</param>
				public GramEmbeddedLanguageAttribute(global::System.Type marker) => Marker = marker;

				public global::System.Type Marker { get; }
			}

		}
		""";
}
