using System;
using System.Collections.Generic;
using System.Text;

using DotGram.Grammar.Binding;
using DotGram.Grammar.Model;
using DotGram.Grammar.Parsing;

namespace DotGram.Grammar.Emit;

/// <summary>Indent-aware output. One per generated function, so nothing interleaves.</summary>
sealed class Writer(int depth)
{
	readonly StringBuilder _text = new();

	int _depth = depth;

	public void Line(string text = "")
	{
		if (text.Length == 0)
			_text.AppendLine();
		else
			_text.Append('\t', _depth).AppendLine(text);
	}

	/// <summary>A single indented line — the body of an <c>if</c> without braces.</summary>
	public void Then(string text)
	{
		_depth++;
		Line(text);
		_depth--;
	}

	public IDisposable Block(string header)
	{
		Line(header);
		Line("{");
		_depth++;

		return new Closer(this);
	}

	public void Append(Writer other) => _text.Append(other._text);

	public override string ToString() => _text.ToString();

	sealed class Closer(Writer writer) : IDisposable
	{
		public void Dispose()
		{
			writer._depth--;
			writer.Line("}");
		}
	}
}

/// <summary>
/// Turns a recognition graph into C#.
/// </summary>
/// <remarks>
/// <para>
/// One method per rule, and inside it one static local function per node. Every one of
/// them has the same shape — take the input and a position, return the new position or
/// -1 — so composing them is just calling them, and there is nothing to allocate,
/// nothing virtual, and no closure. Static local functions specifically, because a
/// closure cannot hold a <c>ReadOnlySpan</c>.
/// </para>
/// <para>
/// This is the fast path over the frozen subset of docs/implementation.md §11:
/// sequence, ordered choice, quantifiers, element sets, literals, rule calls. No
/// trivia, no result construction, no recovery yet — a rule's value is the text it
/// matched.
/// </para>
/// </remarks>
public static class CSharpEmitter
{
	/// <param name="graph">The normalized grammar.</param>
	/// <param name="className">
	/// The partial class the generated members go into. A nested host is named by its
	/// chain — <c>Outer.Inner</c> — and written back out nested.
	/// </param>
	/// <param name="namespace">Its namespace, or null for the global one.</param>
	public static string Emit(RecognitionGraph graph, string className, string? @namespace = null)
	{
		if (graph is null)
			throw new ArgumentNullException(nameof(graph));

		var file  = new Writer(0);
		var scope = new Stack<IDisposable>();

		file.Line("// <auto-generated/>");
		file.Line("#nullable enable");
		file.Line();

		// A block namespace rather than a file-scoped one: the consumer's language
		// version is unknown (.claude/rules/emitted-code.md).
		if (@namespace is not null)
			scope.Push(file.Block($"namespace {@namespace}"));

		foreach (var name in className.Split('.'))
			scope.Push(file.Block($"partial class {name}"));

		foreach (var publication in graph.Publications)
		{
			EmitPublication(file, publication);
			file.Line();
		}

		foreach (var rule in graph.Rules)
		{
			EmitRule(file, graph, rule);
			file.Line();
		}

		while (scope.Count > 0)
			scope.Pop().Dispose();

		return file.ToString();
	}

	/// <summary>
	/// One directive, one pair of methods, in the shape of <c>int.Parse</c> /
	/// <c>int.TryParse</c> (docs/syntax.md §6).
	/// </summary>
	/// <remarks>
	/// A rule's value is still the text it matched, so everything here is <c>string</c>.
	/// When construction lands, only these signatures change — what they are built on,
	/// a recognizer returning an end position or -1, does not.
	/// </remarks>
	static void EmitPublication(Writer file, Publication publication)
	{
		var method   = publication.MethodName;
		var name     = publication.Rule.Name;
		var isAll    = publication.Kind == PublishKind.FindAll;
		var result   = isAll ? "string[]" : publication.Kind == PublishKind.Parse ? "string" : "string?";
		var outType  = isAll ? "string[]" : "string";
		var outName  = isAll ? "values" : "value";

		file.Line($"/// <summary>{Summary(publication.Kind, name)}</summary>");

		using (file.Block($"public static {result} {method}(string input)"))
		{
			file.Line($"if (Try{method}(input, out var {outName}, out var error, out var errorPosition))");
			file.Then($"return {outName};");
			file.Line();

			// Only `parse` throws: it is the one directive that asserts the input is this
			// rule, so failing it is an error rather than an answer of "no".
			if (publication.Kind == PublishKind.Parse)
				file.Line("throw new global::System.FormatException(error + \" at \" + errorPosition.ToString());");
			else
				file.Line(isAll ? "return new string[0];" : "return null;");
		}

		file.Line();

		using (file.Block(
			$"public static bool Try{method}(string input, out {outType} {outName}, out string? error, out int errorPosition)"))
		{
			// Fully qualified, and as a static call rather than an extension method:
			// the emitted file carries no usings at all (.claude/rules/emitted-code.md).
			file.Line("var text = global::System.MemoryExtensions.AsSpan(input);");
			file.Line();
			file.Line($"{outName} = {(isAll ? "new string[0]" : "\"\"")};");
			file.Line("error         = null;");
			file.Line("errorPosition = 0;");
			file.Line();

			switch (publication.Kind)
			{
				case PublishKind.Parse:
				case PublishKind.Match:

					file.Line($"var end = {MethodOf(publication.Rule)}(text, 0);");
					file.Line();

					using (file.Block("if (end < 0)"))
					{
						file.Line($"error = \"Input does not match '{name}'.\";");
						file.Line("return false;");
					}

					file.Line();

					// The difference between the two directives, and the whole of it.
					if (publication.Kind == PublishKind.Parse)
					{
						using (file.Block("if (end != input.Length)"))
						{
							file.Line("error         = \"Unexpected input.\";");
							file.Line("errorPosition = end;");
							file.Line("return false;");
						}

						file.Line();
					}

					file.Line("value = input.Substring(0, end);");
					file.Line("return true;");
					break;

				case PublishKind.Find:

					using (file.Block("for (var start = 0; start <= input.Length; start++)"))
					{
						file.Line($"var end = {MethodOf(publication.Rule)}(text, start);");
						file.Line();

						using (file.Block("if (end >= 0)"))
						{
							file.Line("value = input.Substring(start, end - start);");
							file.Line("return true;");
						}
					}

					file.Line();
					file.Line($"error = \"No occurrence of '{name}'.\";");
					file.Line("return false;");
					break;

				default:

					file.Line("var found = new global::System.Collections.Generic.List<string>();");
					file.Line();

					using (file.Block("for (var start = 0; start <= input.Length; )"))
					{
						file.Line($"var end = {MethodOf(publication.Rule)}(text, start);");
						file.Line();

						using (file.Block("if (end < 0)"))
						{
							file.Line("start++;");
							file.Line("continue;");
						}

						file.Line();
						file.Line("found.Add(input.Substring(start, end - start));");
						file.Line();
						file.Line("// A rule that matches nothing would otherwise find it for ever.");
						file.Line("start = end > start ? end : start + 1;");
					}

					file.Line();

					using (file.Block("if (found.Count == 0)"))
					{
						file.Line($"error = \"No occurrence of '{name}'.\";");
						file.Line("return false;");
					}

					file.Line();
					file.Line("values = found.ToArray();");
					file.Line("return true;");
					break;
			}
		}
	}

	static string Summary(PublishKind kind, string rule) => kind switch
	{
		PublishKind.Parse   => $"Parses the whole input as <c>{rule}</c>.",
		PublishKind.Match   => $"Matches <c>{rule}</c> at the start of the input.",
		PublishKind.Find    => $"Finds the first occurrence of <c>{rule}</c>.",
		_                   => $"Finds every non-overlapping occurrence of <c>{rule}</c>.",
	};

	static void EmitRule(Writer file, RecognitionGraph graph, RuleSymbol rule)
	{
		var functions = new List<Writer>();
		var counter   = new Counter();
		var entry     = Compile(graph.Bodies[rule], functions, counter);

		using (file.Block($"static int {MethodOf(rule)}(global::System.ReadOnlySpan<char> text, int pos)"))
		{
			file.Line($"return {entry}(text, pos);");

			foreach (var function in functions)
			{
				file.Line();
				file.Append(function);
			}
		}
	}

	static string MethodOf(RuleSymbol rule) => $"Recognize_{rule.Name.Replace('.', '_')}";

	sealed class Counter
	{
		int _next;

		public int Next() => _next++;
	}

	// ── Nodes ────────────────────────────────────────────────────────────────────

	/// <summary>
	/// Emits one static local function for <paramref name="node"/> and returns its name.
	/// </summary>
	static string Compile(Node node, List<Writer> functions, Counter counter)
	{
		var name   = $"N{counter.Next()}";
		var writer = new Writer(1);

		// Reserved before the body is written, so nested functions can be appended
		// while this one is still open.
		functions.Add(writer);

		using (writer.Block($"static int {name}(global::System.ReadOnlySpan<char> text, int p)"))
			Write(writer, node, functions, counter);

		return name;
	}

	static void Write(Writer writer, Node node, List<Writer> functions, Counter counter)
	{
		switch (node)
		{
			case Node.Literal(var value):

				writer.Line($"if (p + {value.Length} > text.Length)");
				writer.Then("return -1;");
				writer.Line();

				for (var i = 0; i < value.Length; i++)
				{
					writer.Line($"if (text[p + {i}] != {Char(value[i])})");
					writer.Then("return -1;");
				}

				writer.Line();
				writer.Line($"return p + {value.Length};");
				break;

			case Node.Element element:

				writer.Line("if (p >= text.Length)");
				writer.Then("return -1;");
				writer.Line();
				writer.Line("var c = text[p];");
				writer.Line();
				writer.Line($"return {Test(element)} ? p + 1 : -1;");
				break;

			case Node.Sequence(var nodes):

				foreach (var child in nodes)
				{
					writer.Line($"p = {Compile(child, functions, counter)}(text, p);");
					writer.Line();
					writer.Line("if (p < 0)");
					writer.Then("return -1;");
					writer.Line();
				}

				writer.Line("return p;");
				break;

			case Node.Choice(var nodes):

				// Ordered choice backtracks fully: every alternative starts from the same
				// position and none of them commits (docs/syntax.md §10).
				for (var i = 0; i < nodes.Count; i++)
				{
					writer.Line($"var r{i} = {Compile(nodes[i], functions, counter)}(text, p);");
					writer.Line();
					writer.Line($"if (r{i} >= 0)");
					writer.Then($"return r{i};");
					writer.Line();
				}

				writer.Line("return -1;");
				break;

			case Node.Repeat(var repeated, var min, var max):

				var body = Compile(repeated, functions, counter);

				writer.Line("var count = 0;");
				writer.Line();

				using (writer.Block(max is null ? "while (true)" : $"while (count < {max})"))
				{
					writer.Line($"var next = {body}(text, p);");
					writer.Line();
					writer.Line("// A body that matched nothing would loop for ever; the grammar is");
					writer.Line("// checked for that, and this is the belt to its braces.");
					writer.Line("if (next < 0 || next == p)");
					writer.Then("break;");
					writer.Line();
					writer.Line("p = next;");
					writer.Line("count++;");
				}

				writer.Line();
				writer.Line($"return count >= {min} ? p : -1;");
				break;

			case Node.Call(var rule, _):
				writer.Line($"return {MethodOf(rule)}(text, p);");
				break;

			// Transparent for now: a rule's value is the text it matched, so a capture
			// and its construction have nothing to do yet.
			case Node.Capture(_, var captured):
				writer.Line($"return {Compile(captured, functions, counter)}(text, p);");
				break;

			case Node.Construct(var built, _):
				writer.Line($"return {Compile(built, functions, counter)}(text, p);");
				break;

			case Node.Lookahead(var positive, var ahead):

				writer.Line($"var matched = {Compile(ahead, functions, counter)}(text, p) >= 0;");
				writer.Line();
				writer.Line($"return matched == {(positive ? "true" : "false")} ? p : -1;");
				break;

			// A guard tests a value, and values do not exist yet.
			case Node.Guard:
			case Node.Empty:
				writer.Line("return p;");
				break;

			default:
				writer.Line("return -1;");
				break;
		}
	}

	static string Test(Node.Element element)
	{
		var tests = new List<string>();

		foreach (var range in element.Ranges)
			tests.Add(range.IsSingle
				? $"c == {Char(range.From)}"
				: $"(c >= {Char(range.From)} && c <= {Char(range.To)})");

		foreach (var category in element.Categories)
			tests.Add(
				"global::System.Globalization.CharUnicodeInfo.GetUnicodeCategory(c) == " +
				$"global::System.Globalization.UnicodeCategory.{category}");

		var test = tests.Count == 0 ? "false" : string.Join(" || ", tests);

		return element.IsNegated ? $"!({test})" : $"({test})";
	}

	static string Char(char value) => value switch
	{
		'\n' => @"'\n'",
		'\r' => @"'\r'",
		'\t' => @"'\t'",
		'\'' => @"'\''",
		'\\' => @"'\\'",
		_    => $"'{value}'",
	};
}
