// <auto-generated/>
#nullable enable

namespace DotGram.Snapshots
{
	partial class Csv
	{
		/// <summary>Everything <c>Csv</c> is made of, in order (§4.1 case 2).</summary>
		static string[] Construct_Csv(string parserText, string[] item0)
		{
			var count = 0;
			if (item0 != null) count += item0.Length;

			var items = new string[count];
			var at    = 0;

			if (item0 != null)
			{
				global::System.Array.Copy(item0, 0, items, at, item0.Length);
				at += item0.Length;
			}

			return items;
		}

		/// <summary>What <c>Row</c> builds its value with (docs/syntax.md §7.3).</summary>
		static string Construct_Row(string parserText, string name, int amount) =>
#line 23 "Csv.gram"
                                                            (name + "=" + amount);
#line default

		/// <summary>What <c>Name</c> builds its value with (docs/syntax.md §7.3).</summary>
		static string Construct_Name(string parserText, string text) =>
#line 25 "Csv.gram"
                                                                              (text);
#line default

		/// <summary>What <c>Amount</c> builds its value with (docs/syntax.md §7.3).</summary>
		static int Construct_Amount(string parserText, string digits) =>
#line 27 "Csv.gram"
                                        int.Parse(digits);
#line default

		static int Recognize_DotGram(global::System.ReadOnlySpan<char> text, int pos, int state, int rootRule, bool whole, bool materialize, ref Failure failure, out object? recognized)
		{
			recognized = null;

			Parser parser = null!;
			RentParser(ref parser);
			parser ??= new Parser();

			try
			{
				var entries = parser.Entries;
				var p       = pos;
				var call    = -1;
				var atomic  = -1;
				var repeat  = -1;
				var lookahead = -1;
				var c       = '\0';
				var capture3 = 0;
				var capture4 = 0;

				entries.Add(new ParserEntry(ParserEntry.Call, 1, pos, -1, -1, -1, -1, 0, rootRule));
				call = 0;
				goto Dispatch;

				S3:

				{
					Trace("enter Csv", 3, p, entries.Count);
					goto S20;
				}

				S4:

				{
					Trace("enter Row", 4, p, entries.Count);
					goto S34;
				}

				S5:

				{
					Trace("enter Name", 5, p, entries.Count);
					goto S44;
				}

				S6:

				{
					Trace("enter Amount", 6, p, entries.Count);
					goto S53;
				}

				S7:

				{
					Trace("enter eof", 7, p, entries.Count);
					goto S56;
				}

				S8:

				{
					Trace("enter eol", 8, p, entries.Count);
					goto S61;
				}

				S9:

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 0, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 0, p, entries.Count);
					goto Return;
				}

				S10:

				{
					global::System.Diagnostics.Debug.Assert(lookahead >= 0 && lookahead < entries.Count);
					var looked = entries[lookahead];
					global::System.Diagnostics.Debug.Assert(looked.Kind == ParserEntry.Lookahead);
					entries.RemoveRange(lookahead, entries.Count - lookahead);
					p         = looked.Position;
					call      = looked.CallIndex;
					atomic    = looked.AtomicIndex;
					repeat    = looked.RepeatIndex;
					lookahead = looked.LookaheadIndex;
					Trace("lookahead body matched", 9, p, entries.Count);
					goto Fail;
				}

				S11:

				{
					if (p >= text.Length) goto Fail;
					p++;
					goto S10;
				}

				S12:

				{
					var lookaheadIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Lookahead, 9, p, call, atomic, repeat, lookahead, 0));
					lookahead = lookaheadIndex;
					Trace("enter negative lookahead", 11, p, entries.Count);
					goto S11;
				}

				S13:

				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var finished = entries[repeat];
					global::System.Diagnostics.Debug.Assert(finished.Kind == ParserEntry.Repeat);
					var previousRepeat = finished.RepeatIndex;
					if (entries.Count == repeat + 1) entries.RemoveAt(repeat);
					repeat = previousRepeat;
					lookahead = finished.LookaheadIndex;
					Trace("leave repeat", 12, p, entries.Count);
					goto S12;
				}

				S14:

				{
					entries.Add(new ParserEntry(ParserEntry.Choice, 13, p, call, atomic, repeat, lookahead, 0));
					goto S19;
				}

				S15:

				{
					goto S14;
				}

				S16:

				{
					var repeatIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Repeat, 0, p, call, atomic, repeat, lookahead, 0));
					repeat = repeatIndex;
					Trace("enter repeat", 14, p, entries.Count);
					goto S14;
				}

				S17:

				{
					var capturedCall = entries.Count - 1;
					while (capturedCall >= 0 && !(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 1 && entries[capturedCall].Value == p)) capturedCall--;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 0, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 0, p, entries.Count);
					goto S15;
				}

				S18:

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 17, p, call, atomic, repeat, lookahead, 0, 1));
					call = callIndex;
					Trace("call Row", 4, p, entries.Count);
					goto S4;
				}

				S19:

				{
					goto S18;
				}

				S20:

				{
					goto S16;
				}

				S21:

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 0, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 0, p, entries.Count);
					goto Return;
				}

				S22:

				{
					if (p + 1 > text.Length) goto Fail;
					if (text[p + 0] != '\r') goto Fail;
					p += 1;
					goto S21;
				}

				S23:

				{
					if (p + 1 > text.Length) goto Fail;
					if (text[p + 0] != '\n') goto Fail;
					p += 1;
					goto S21;
				}

				S24:

				{
					entries.Add(new ParserEntry(ParserEntry.Choice, 22, p, call, atomic, repeat, lookahead, 0));
					Trace("push choice", 22, p, entries.Count);
					goto S23;
				}

				S25:

				{
					if (p + 2 > text.Length) goto Fail;
					if (text[p + 0] != '\r') goto Fail;
					if (text[p + 1] != '\n') goto Fail;
					p += 2;
					goto S21;
				}

				S26:

				{
					entries.Add(new ParserEntry(ParserEntry.Choice, 24, p, call, atomic, repeat, lookahead, 0));
					Trace("push choice", 24, p, entries.Count);
					goto S25;
				}

				S27:

				{
					var capturedCall = entries.Count - 1;
					while (capturedCall >= 0 && !(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p)) capturedCall--;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 2, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 2, p, entries.Count);
					goto S26;
				}

				S28:

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 27, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Amount", 6, p, entries.Count);
					goto S6;
				}

				S29:

				{
					goto S28;
				}

				S30:

				{
					if (p + 1 > text.Length) goto Fail;
					if (text[p + 0] != ',') goto Fail;
					p += 1;
					goto S29;
				}

				S31:

				{
					var capturedCall = entries.Count - 1;
					while (capturedCall >= 0 && !(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 2 && entries[capturedCall].Value == p)) capturedCall--;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 1, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 1, p, entries.Count);
					goto S30;
				}

				S32:

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 31, p, call, atomic, repeat, lookahead, 0, 2));
					call = callIndex;
					Trace("call Name", 5, p, entries.Count);
					goto S5;
				}

				S33:

				{
					goto S32;
				}

				S34:

				{
					goto S33;
				}

				S35:

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 0, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 0, p, entries.Count);
					goto Return;
				}

				S36:

				{
					global::System.Diagnostics.Debug.Assert(call >= 0 && call < entries.Count);
					var ruleStart = entries[call].Position;
					var guardCaptured0At = -1;
					for (var candidateAt = entries.Count - 1; candidateAt > call; candidateAt--)
					{
						var candidate = entries[candidateAt];
						if (candidate.Kind == ParserEntry.Capture && candidate.CallIndex == call && (candidate.State == 3))
						{
							guardCaptured0At = candidateAt;
							break;
						}
					}
					var guardCaptured0 = guardCaptured0At < 0 ? string.Empty : text.Slice(entries[guardCaptured0At].Position, entries[guardCaptured0At].Value - entries[guardCaptured0At].Position).ToString();
					if (!Recognize_DotGram_Guard0(text.Slice(ruleStart, p - ruleStart).ToString(), guardCaptured0)) goto Fail;
					goto S35;
				}

				S37:

				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var finished = entries[repeat];
					global::System.Diagnostics.Debug.Assert(finished.Kind == ParserEntry.Repeat);
					var previousRepeat = finished.RepeatIndex;
					if (entries.Count == repeat + 1) entries.RemoveAt(repeat);
					repeat = previousRepeat;
					lookahead = finished.LookaheadIndex;
					Trace("leave repeat", 36, p, entries.Count);
					goto S36;
				}

				S38:

				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var repeating = entries[repeat];
					global::System.Diagnostics.Debug.Assert(repeating.Kind == ParserEntry.Repeat);
					if (repeating.Value >= 1)
						entries.Add(new ParserEntry(ParserEntry.Choice, 37, p, call, atomic, repeat, lookahead, 0));
					goto S43;
				}

				S39:

				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var repeated = entries[repeat];
					entries[repeat] = new ParserEntry(ParserEntry.Repeat, 0, repeated.Position, repeated.CallIndex, repeated.AtomicIndex, repeated.RepeatIndex, repeated.LookaheadIndex, repeated.Value + 1);
					goto S38;
				}

				S40:

				{
					var repeatIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Repeat, 0, p, call, atomic, repeat, lookahead, 0));
					repeat = repeatIndex;
					Trace("enter repeat", 38, p, entries.Count);
					goto S38;
				}

				S41:

				{
					entries.Add(new ParserEntry(ParserEntry.Capture, 3, capture3, call, atomic, repeat, lookahead, p));
					Trace("capture", 3, p, entries.Count);
					goto S39;
				}

				S42:

				{
					if (p >= text.Length) goto Fail;
					c = text[p];
					if (!(((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')))) goto Fail;
					p++;
					goto S41;
				}

				S43:

				{
					capture3 = p;
					goto S42;
				}

				S44:

				{
					goto S40;
				}

				S45:

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 0, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 0, p, entries.Count);
					goto Return;
				}

				S46:

				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var finished = entries[repeat];
					global::System.Diagnostics.Debug.Assert(finished.Kind == ParserEntry.Repeat);
					var previousRepeat = finished.RepeatIndex;
					if (entries.Count == repeat + 1) entries.RemoveAt(repeat);
					repeat = previousRepeat;
					lookahead = finished.LookaheadIndex;
					Trace("leave repeat", 45, p, entries.Count);
					goto S45;
				}

				S47:

				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var repeating = entries[repeat];
					global::System.Diagnostics.Debug.Assert(repeating.Kind == ParserEntry.Repeat);
					if (repeating.Value >= 1)
						entries.Add(new ParserEntry(ParserEntry.Choice, 46, p, call, atomic, repeat, lookahead, 0));
					goto S52;
				}

				S48:

				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var repeated = entries[repeat];
					entries[repeat] = new ParserEntry(ParserEntry.Repeat, 0, repeated.Position, repeated.CallIndex, repeated.AtomicIndex, repeated.RepeatIndex, repeated.LookaheadIndex, repeated.Value + 1);
					goto S47;
				}

				S49:

				{
					var repeatIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Repeat, 0, p, call, atomic, repeat, lookahead, 0));
					repeat = repeatIndex;
					Trace("enter repeat", 47, p, entries.Count);
					goto S47;
				}

				S50:

				{
					entries.Add(new ParserEntry(ParserEntry.Capture, 4, capture4, call, atomic, repeat, lookahead, p));
					Trace("capture", 4, p, entries.Count);
					goto S48;
				}

				S51:

				{
					if (p >= text.Length) goto Fail;
					c = text[p];
					if (!(((c >= '0' && c <= '9')))) goto Fail;
					p++;
					goto S50;
				}

				S52:

				{
					capture4 = p;
					goto S51;
				}

				S53:

				{
					goto S49;
				}

				S54:

				{
					global::System.Diagnostics.Debug.Assert(lookahead >= 0 && lookahead < entries.Count);
					var looked = entries[lookahead];
					global::System.Diagnostics.Debug.Assert(looked.Kind == ParserEntry.Lookahead);
					entries.RemoveRange(lookahead, entries.Count - lookahead);
					p         = looked.Position;
					call      = looked.CallIndex;
					atomic    = looked.AtomicIndex;
					repeat    = looked.RepeatIndex;
					lookahead = looked.LookaheadIndex;
					Trace("lookahead body matched", 0, p, entries.Count);
					goto Fail;
				}

				S55:

				{
					if (p >= text.Length) goto Fail;
					p++;
					goto S54;
				}

				S56:

				{
					var lookaheadIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Lookahead, 0, p, call, atomic, repeat, lookahead, 0));
					lookahead = lookaheadIndex;
					Trace("enter negative lookahead", 55, p, entries.Count);
					goto S55;
				}

				S57:

				{
					if (p + 1 > text.Length) goto Fail;
					if (text[p + 0] != '\r') goto Fail;
					p += 1;
					goto Return;
				}

				S58:

				{
					if (p + 1 > text.Length) goto Fail;
					if (text[p + 0] != '\n') goto Fail;
					p += 1;
					goto Return;
				}

				S59:

				{
					entries.Add(new ParserEntry(ParserEntry.Choice, 57, p, call, atomic, repeat, lookahead, 0));
					Trace("push choice", 57, p, entries.Count);
					goto S58;
				}

				S60:

				{
					if (p + 2 > text.Length) goto Fail;
					if (text[p + 0] != '\r') goto Fail;
					if (text[p + 1] != '\n') goto Fail;
					p += 2;
					goto Return;
				}

				S61:

				{
					entries.Add(new ParserEntry(ParserEntry.Choice, 59, p, call, atomic, repeat, lookahead, 0));
					Trace("push choice", 59, p, entries.Count);
					goto S60;
				}

				Return:
				global::System.Diagnostics.Debug.Assert(call >= 0 && call < entries.Count);
				var returned = entries[call];
				global::System.Diagnostics.Debug.Assert(returned.Kind == ParserEntry.Call || returned.Kind == ParserEntry.Completed);
				state = returned.State;
				var previousCall = returned.CallIndex;
				repeat = returned.RepeatIndex;
				lookahead = returned.LookaheadIndex;

				if (returned.RuleIndex >= 0)
				{
					entries[call] = new ParserEntry(ParserEntry.Completed, returned.State, returned.Position, returned.CallIndex, returned.AtomicIndex, returned.RepeatIndex, returned.LookaheadIndex, p, returned.RuleIndex);
				}
				else if (entries.Count == call + 1)
					entries.RemoveAt(call);

				call = previousCall;
				Trace("return", state, p, entries.Count);
				goto Dispatch;

				Accept:
				if (whole && p != text.Length) goto Fail;
				if (materialize)
				{
					if (rootRule >= 0)
					{

						var values = parser.Materialization(entries.Count);
						var links  = parser.MaterializationLinks(entries.Count);

						for (var derivationAt = 0; derivationAt < entries.Count; derivationAt++)
						{
							var derivation = entries[derivationAt];
							if (derivation.CallIndex >= 0 && (derivation.Kind == ParserEntry.Capture || derivation.Kind == ParserEntry.RuleCapture || derivation.Kind == ParserEntry.Construct))
							{
								links[entries.Count + derivationAt] = links[derivation.CallIndex];
								links[derivation.CallIndex] = derivationAt;
							}
						}

						values[0] = parser;
						for (var ownerAt = 0; ownerAt < entries.Count; ownerAt++)
						{
							if (!global::System.Object.ReferenceEquals(values[ownerAt], parser)) continue;
							for (var capturedAt = links[ownerAt]; capturedAt >= 0; capturedAt = links[entries.Count + capturedAt])
							{
								var candidate = entries[capturedAt];
								if (candidate.Kind == ParserEntry.RuleCapture)
									values[candidate.Position] = parser;
							}
						}
						for (var completedAt = entries.Count - 1; completedAt >= 0; completedAt--)
						{
							var completed = entries[completedAt];
							if (completed.Kind != ParserEntry.Completed || !global::System.Object.ReferenceEquals(values[completedAt], parser)) continue;
							switch (completed.RuleIndex)
							{
								case 0:
								{
									var captured0Count = 0;
									for (var capturedAt0 = links[completedAt]; capturedAt0 >= 0; capturedAt0 = links[entries.Count + capturedAt0])
									{
										var candidate = entries[capturedAt0];
										if (candidate.Kind == ParserEntry.RuleCapture && candidate.CallIndex == completedAt && (candidate.State == 0)) captured0Count++;
									}
									var captured0 = new string[captured0Count];
									var captured0Item = captured0Count;
									for (var capturedAt0 = links[completedAt]; capturedAt0 >= 0; capturedAt0 = links[entries.Count + capturedAt0])
									{
										var candidate = entries[capturedAt0];
										if (candidate.Kind == ParserEntry.RuleCapture && candidate.CallIndex == completedAt && (candidate.State == 0))
										{
											captured0[--captured0Item] = (string)values[candidate.Position]!;
										}
									}

									var chosen = -1;
									for (var chosenAt = links[completedAt]; chosenAt >= 0; chosenAt = links[entries.Count + chosenAt])
									{
										var candidate = entries[chosenAt];
										if (candidate.Kind == ParserEntry.Construct && candidate.CallIndex == completedAt)
										{
											chosen = candidate.State;
											break;
										}
									}
									global::System.Diagnostics.Debug.Assert(chosen >= 0);
									switch (chosen)
									{
										case 0:
											values[completedAt] = Construct_Csv(text.Slice(completed.Position, completed.Value - completed.Position).ToString(), captured0!);
											break;
									}
									break;
								}
								case 1:
								{
									var captured0At = -1;
									for (var capturedAt0 = links[completedAt]; capturedAt0 >= 0; capturedAt0 = links[entries.Count + capturedAt0])
									{
										var candidate = entries[capturedAt0];
										if (candidate.Kind == ParserEntry.RuleCapture && candidate.CallIndex == completedAt && (candidate.State == 1))
										{
											captured0At = candidate.Position;
											break;
										}
									}
									global::System.Diagnostics.Debug.Assert(captured0At >= 0);
									var captured0 = (string)values[captured0At]!;

									var captured1At = -1;
									for (var capturedAt1 = links[completedAt]; capturedAt1 >= 0; capturedAt1 = links[entries.Count + capturedAt1])
									{
										var candidate = entries[capturedAt1];
										if (candidate.Kind == ParserEntry.RuleCapture && candidate.CallIndex == completedAt && (candidate.State == 2))
										{
											captured1At = candidate.Position;
											break;
										}
									}
									global::System.Diagnostics.Debug.Assert(captured1At >= 0);
									var captured1 = (int)values[captured1At]!;

									var chosen = -1;
									for (var chosenAt = links[completedAt]; chosenAt >= 0; chosenAt = links[entries.Count + chosenAt])
									{
										var candidate = entries[chosenAt];
										if (candidate.Kind == ParserEntry.Construct && candidate.CallIndex == completedAt)
										{
											chosen = candidate.State;
											break;
										}
									}
									global::System.Diagnostics.Debug.Assert(chosen >= 0);
									switch (chosen)
									{
										case 0:
											values[completedAt] = Construct_Row(text.Slice(completed.Position, completed.Value - completed.Position).ToString(), captured0!, captured1!);
											break;
									}
									break;
								}
								case 2:
								{
									var captured0From = -1;
									var captured0To   = -1;
									for (var capturedAt0 = links[completedAt]; capturedAt0 >= 0; capturedAt0 = links[entries.Count + capturedAt0])
									{
										var candidate = entries[capturedAt0];
										if (candidate.Kind == ParserEntry.Capture && candidate.CallIndex == completedAt && (candidate.State == 3))
										{
											if (captured0To < 0)
												captured0To = candidate.Value;
											captured0From = candidate.Position;
										}
									}
									var captured0 = captured0From < 0 ? string.Empty : text.Slice(captured0From, captured0To - captured0From).ToString();

									var chosen = -1;
									for (var chosenAt = links[completedAt]; chosenAt >= 0; chosenAt = links[entries.Count + chosenAt])
									{
										var candidate = entries[chosenAt];
										if (candidate.Kind == ParserEntry.Construct && candidate.CallIndex == completedAt)
										{
											chosen = candidate.State;
											break;
										}
									}
									global::System.Diagnostics.Debug.Assert(chosen >= 0);
									switch (chosen)
									{
										case 0:
											values[completedAt] = Construct_Name(text.Slice(completed.Position, completed.Value - completed.Position).ToString(), captured0!);
											break;
									}
									break;
								}
								case 3:
								{
									var captured0From = -1;
									var captured0To   = -1;
									for (var capturedAt0 = links[completedAt]; capturedAt0 >= 0; capturedAt0 = links[entries.Count + capturedAt0])
									{
										var candidate = entries[capturedAt0];
										if (candidate.Kind == ParserEntry.Capture && candidate.CallIndex == completedAt && (candidate.State == 4))
										{
											if (captured0To < 0)
												captured0To = candidate.Value;
											captured0From = candidate.Position;
										}
									}
									var captured0 = captured0From < 0 ? string.Empty : text.Slice(captured0From, captured0To - captured0From).ToString();

									var chosen = -1;
									for (var chosenAt = links[completedAt]; chosenAt >= 0; chosenAt = links[entries.Count + chosenAt])
									{
										var candidate = entries[chosenAt];
										if (candidate.Kind == ParserEntry.Construct && candidate.CallIndex == completedAt)
										{
											chosen = candidate.State;
											break;
										}
									}
									global::System.Diagnostics.Debug.Assert(chosen >= 0);
									switch (chosen)
									{
										case 0:
											values[completedAt] = Construct_Amount(text.Slice(completed.Position, completed.Value - completed.Position).ToString(), captured0!);
											break;
									}
									break;
								}
							}
						}
						recognized = values[0];
					}
				}
				return p;

				Fail:
				if (lookahead < 0 && p > failure.Position)
					failure.Position = p;
				Trace("fail", state, p, entries.Count);

				while (entries.Count > 0)
				{
					var last = entries.Count - 1;
					var entry = entries[last];
					entries.RemoveAt(last);

					if (entry.Kind == ParserEntry.Choice)
					{
						state  = entry.State;
						p      = entry.Position;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						Trace("resume", state, p, entries.Count);
						goto Dispatch;
					}
					if (entry.Kind == ParserEntry.Capture || entry.Kind == ParserEntry.Construct || entry.Kind == ParserEntry.RuleCapture)
						continue;

					if (entry.Kind == ParserEntry.Call || entry.Kind == ParserEntry.Completed)
					{
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						p      = entry.Position;
					}
					else if (entry.Kind == ParserEntry.Atomic)
					{
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
					}
					else if (entry.Kind == ParserEntry.Repeat)
					{
						p      = entry.Position;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
					}
					else

					{
						global::System.Diagnostics.Debug.Assert(entry.Kind == ParserEntry.Lookahead);
						p         = entry.Position;
						call      = entry.CallIndex;
						atomic    = entry.AtomicIndex;
						repeat    = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;

						if (entry.Value == 0)

						{
							state = entry.State;
							if (entry.RuleIndex >= 0)
							{
								entries.Add(new ParserEntry(ParserEntry.Capture, entry.RuleIndex, p, call, atomic, repeat, lookahead, p));
								Trace("capture negative lookahead", entry.RuleIndex, p, entries.Count);
							}
							Trace("negative lookahead succeeds", state, p, entries.Count);
							goto Dispatch;
						}
					}
				}

				return -1;

				Dispatch:
				switch (state)
				{
					case 0: goto Return;
					case 1: goto Accept;
					case 2:   goto Fail;
					case 3: goto S3;
					case 4: goto S4;
					case 5: goto S5;
					case 6: goto S6;
					case 7: goto S7;
					case 8: goto S8;
					case 9: goto S9;
					case 10: goto S10;
					case 11: goto S11;
					case 12: goto S12;
					case 13: goto S13;
					case 14: goto S14;
					case 15: goto S15;
					case 16: goto S16;
					case 17: goto S17;
					case 18: goto S18;
					case 19: goto S19;
					case 20: goto S20;
					case 21: goto S21;
					case 22: goto S22;
					case 23: goto S23;
					case 24: goto S24;
					case 25: goto S25;
					case 26: goto S26;
					case 27: goto S27;
					case 28: goto S28;
					case 29: goto S29;
					case 30: goto S30;
					case 31: goto S31;
					case 32: goto S32;
					case 33: goto S33;
					case 34: goto S34;
					case 35: goto S35;
					case 36: goto S36;
					case 37: goto S37;
					case 38: goto S38;
					case 39: goto S39;
					case 40: goto S40;
					case 41: goto S41;
					case 42: goto S42;
					case 43: goto S43;
					case 44: goto S44;
					case 45: goto S45;
					case 46: goto S46;
					case 47: goto S47;
					case 48: goto S48;
					case 49: goto S49;
					case 50: goto S50;
					case 51: goto S51;
					case 52: goto S52;
					case 53: goto S53;
					case 54: goto S54;
					case 55: goto S55;
					case 56: goto S56;
					case 57: goto S57;
					case 58: goto S58;
					case 59: goto S59;
					case 60: goto S60;
					case 61: goto S61;
					default: goto Fail;
				}
			}
			finally

			{
				parser.Reset();
				ReturnParser(parser);
			}
		}

		static int Recognize_Csv(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out string[] value)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 3, 0, false, true, ref failure, out recognized);
			value = end < 0 ? default! : (string[])recognized!;
			return end;
		}

		static int Recognize_Row(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out string value)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 4, 1, false, true, ref failure, out recognized);
			value = end < 0 ? default! : (string)recognized!;
			return end;
		}

		static int Recognize_Name(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out string value)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 5, 2, false, true, ref failure, out recognized);
			value = end < 0 ? default! : (string)recognized!;
			return end;
		}

		static int Recognize_Amount(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out int value)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 6, 3, false, true, ref failure, out recognized);
			value = end < 0 ? default! : (int)recognized!;
			return end;
		}

		static int Recognize_eof(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 7, -1, false, true, ref failure, out recognized);
			return end;
		}

		static int Recognize_eol(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 8, -1, false, true, ref failure, out recognized);
			return end;
		}

		static bool Recognize_DotGram_Guard0(string parserText, string text) =>
#line 25 "Csv.gram"
                                                      (text.Length <= 16);
#line default

		/// <summary>Where a match got before it gave up, and why.</summary>
		struct Failure
		{
			/// <summary>
			/// The furthest position the input was followed to. Zero on a match that
			/// succeeded without ever backtracking, and meaningless unless one failed.
			/// </summary>
			public int Position;
		}

		private sealed class Parser
		{
			internal readonly ParserArena Entries = new ParserArena();
			object?[] _values = global::System.Array.Empty<object?>();
			int[] _links = global::System.Array.Empty<int>();
			int _valuesUsed;

			internal object?[] Materialization(int count)
			{
				if (_values.Length < count)
					global::System.Array.Resize(ref _values, count);

				_valuesUsed = count;

				return _values;
			}

			internal int[] MaterializationLinks(int count)
			{
				if (_links.Length < count * 2)
					global::System.Array.Resize(ref _links, count * 2);

				for (var i = 0; i < count; i++)
					_links[i] = -1;

				return _links;
			}

			internal void Reset()
			{
				Entries.Clear();
				global::System.Array.Clear(_values, 0, _valuesUsed);
				_valuesUsed = 0;
			}
		}

		private sealed class ParserArena
		{
			ParserEntry[] _items = global::System.Array.Empty<ParserEntry>();

			internal int Count { get; private set; }

			internal ParserEntry this[int index]
			{
				get => _items[index];
				set => _items[index] = value;
			}

			internal void Add(ParserEntry entry)
			{
				if (Count == _items.Length)
					global::System.Array.Resize(ref _items, Count == 0 ? 16 : Count * 2);

				_items[Count++] = entry;
			}

			internal void RemoveAt(int index)
			{
				var after = Count - index - 1;

				if (after > 0)
					global::System.Array.Copy(_items, index + 1, _items, index, after);

				Count--;
			}

			internal void RemoveRange(int index, int count)
			{
				if (count == 0)
					return;

				var after = Count - index - count;

				if (after > 0)
					global::System.Array.Copy(_items, index + count, _items, index, after);

				Count -= count;
			}

			internal void Clear()
			{
				Count = 0;
			}
		}

		private readonly struct ParserEntry
		{
			internal const int Choice = 1;
			internal const int Call   = 2;
			internal const int Atomic = 3;
			internal const int Repeat = 4;
			internal const int Lookahead = 5;
			internal const int Capture = 6;
			internal const int Construct = 7;
			internal const int Completed = 8;
			internal const int RuleCapture = 9;
			internal const int Dead = 10;
			internal const int Recovery = 11;
			internal const int PendingRecovery = 12;
			internal const int Run = 13;

			internal ParserEntry(
				int kind, int state, int position, int callIndex, int atomicIndex,
				int repeatIndex, int lookaheadIndex, int value, int ruleIndex = -1)
			{
				Kind        = kind;
				State       = state;
				Position    = position;
				CallIndex   = callIndex;
				AtomicIndex = atomicIndex;
				RepeatIndex = repeatIndex;
				LookaheadIndex = lookaheadIndex;
				Value       = value;
				RuleIndex   = ruleIndex;
			}

			internal int Kind        { get; }
			internal int State       { get; }
			internal int Position    { get; }
			internal int CallIndex   { get; }
			internal int AtomicIndex { get; }
			internal int RepeatIndex { get; }
			internal int LookaheadIndex { get; }
			internal int Value       { get; }
			internal int RuleIndex   { get; }
		}

		static partial void RentParser(ref Parser parser);
		static partial void ReturnParser(Parser parser);

		[global::System.Diagnostics.Conditional("DOTGRAM_TRACE")]
		static void Trace(string action, int state, int position, int arena)
		{
			global::System.Diagnostics.Debug.WriteLine(
				".Gram " + action + " state=" + state.ToString() +
				" position=" + position.ToString() + " arena=" + arena.ToString());
		}
	}
}
