// <auto-generated/>
#nullable enable

namespace DotGram.Snapshots
{
	partial class Csv
	{
		static string[] Construct_Csv(string[] item0) =>
			item0 ?? global::System.Array.Empty<string>();

		static string Construct_Row(string name, int amount) =>
#line 23 "Csv.gram"
                                                            (name + "=" + amount);
#line default

		static string Construct_Name(string text) =>
#line 25 "Csv.gram"
                                                                              (text);
#line default

		static int Construct_Amount(string digits) =>
#line 27 "Csv.gram"
                                        int.Parse(digits);
#line default

		static int Recognize_DotGram(global::System.ReadOnlySpan<char> text, int pos, int state, int rootRule, bool whole, bool materialize, ref Failure failure, out object? recognized)
		{
			recognized = null;

			Parser parser = null!;
			RentParser(ref parser);
			var lent = parser != null;
			parser ??= Recycled();

			try
			{
				var entries = parser.Entries;
				var p       = pos;
				var call    = -1;
				var atomic  = -1;
				var repeat  = -1;
				var lookahead = -1;
				var c       = '\0';
				string[]? expected = null;
				var turn0 = 0;
				var completedCall = -1;
				var capture5 = 0;

				entries.Add(new ParserEntry(ParserEntry.Call, 1, pos, -1, -1, -1, -1, 0, rootRule));
				call = 0;
				Trace("enter", state, p, entries.Count, text, "");
				Dispatch:
				switch (state)
				{
					case 0: goto Return;
					case 1: goto Accept;
					case 2:   expected = null; goto Fail;
					case 3: goto S3;
					case 4: goto S4;
					case 5: goto S5;
					case 6: goto S6;
					case 7: goto S7;
					case 8: goto S8;
					case 9: goto S9;
					case 10: goto S10;
					case 11: goto S11;
					case 12: goto S12;
					case 13: goto S13;
					case 14: goto S14;
					case 15: goto S15;
					case 16: goto S16;
					case 17: goto S17;
					case 18: goto S18;
					case 19: goto S19;
					case 20: goto S20;
					case 21: goto S21;
					case 22: goto S22;
					case 23: goto S23;
					case 24: goto S24;
					case 25: goto S25;
					case 26: goto S26;
					case 27: goto S27;
					case 28: goto S28;
					case 29: goto S29;
					case 30: goto S30;
					default: expected = null; goto Fail;
				}

				S3:
				{
					var scanned = Scan_eof(text, p);
					if (scanned < 0)
					{
						p = -1 - scanned;
						expected = ExpectedSet_DotGram(0);
						goto Fail;
					}
					p = scanned;
					goto Return;
				}

				S4:
				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var finished = entries[repeat];
					global::System.Diagnostics.Debug.Assert(finished.Kind == ParserEntry.Repeat);
					var previousRepeat = finished.RepeatIndex;
					if (entries.Count == repeat + 1) entries.RemoveAt(repeat);
					repeat = previousRepeat;
					lookahead = finished.LookaheadIndex;
					Trace("leave repeat", 3, p, entries.Count, text, "Csv");
					goto S3;
				}

				S5:
				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var repeating = entries[repeat];
					global::System.Diagnostics.Debug.Assert(repeating.Kind == ParserEntry.Repeat);
					{
						entries.Add(new ParserEntry(ParserEntry.LoopExit, 4, p, call, atomic, repeat, lookahead, 0));
						entries[repeat] = new ParserEntry(ParserEntry.Repeat, 0, repeating.Position, repeating.CallIndex, repeating.AtomicIndex, repeating.RepeatIndex, repeating.LookaheadIndex, repeating.Value, p);
						Trace("stand exit", 4, p, entries.Count, text, "Csv");
					}
				}

				S6:
				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 20, p, call, atomic, repeat, lookahead, 0, 1));
					call = callIndex;
					Trace("call Row", 7, p, entries.Count, text, "Csv");
				}

				S7:
				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 13, p, call, atomic, repeat, lookahead, 0, 2));
					call = callIndex;
					Trace("call Name", 8, p, entries.Count, text, "Row");
				}

				S8:
				{
					entries.Add(new ParserEntry(ParserEntry.CaptureOpen, 3, p, call, atomic, repeat, lookahead, 0));
					Trace("open capture", 3, p, entries.Count, text, "Name");
				}

				S9:
				{
					if ((uint)p >= (uint)text.Length)
					{
						expected = ExpectedSet_DotGram(7);
						goto Fail;
					}
					c = text[p];
					if (!(((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))))
					{
						expected = ExpectedSet_DotGram(7);
						goto Fail;
					}
					p++;
				}

				S10:
				{
					if ((uint)p >= (uint)text.Length)
					{
						expected = ExpectedSet_DotGram(7);
						goto S11;
					}
					c = text[p];
					if (!(((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))))
					{
						expected = ExpectedSet_DotGram(7);
						goto S11;
					}
					p++;
					goto S10;
				}

				S11:
				{
					var closed  = 0;
					var openedAt = entries.Count - 1;

					for (; openedAt >= 0; openedAt--)
					{
						var opened = entries[openedAt];

						if (opened.State != 3) continue;

						if (opened.Kind == ParserEntry.Capture)
						{
							closed++;
							continue;
						}

						if (opened.Kind != ParserEntry.CaptureOpen)
							continue;

						if (closed == 0)
							break;

						closed--;
					}

					global::System.Diagnostics.Debug.Assert(openedAt >= 0);
					entries.Add(new ParserEntry(ParserEntry.Capture, 3, entries[openedAt].Position, call, atomic, repeat, lookahead, p));
					Trace("capture", 3, p, entries.Count, text, "Name");
				}

				S12:
				{
					global::System.Diagnostics.Debug.Assert(call >= 0 && call < entries.Count);
					var ruleStart = entries[call].Position;
					var guardCaptured0At = -1;
					for (var candidateAt = entries.Count - 1; candidateAt > call; candidateAt--)
					{
						var candidate = entries[candidateAt];
						if (candidate.Kind == ParserEntry.Capture && candidate.CallIndex == call && (candidate.State == 3))
						{
							guardCaptured0At = candidateAt;
							break;
						}
					}
					var guardCaptured0 = guardCaptured0At < 0 ? string.Empty : text.Slice(entries[guardCaptured0At].Position, entries[guardCaptured0At].Value - entries[guardCaptured0At].Position).ToString();
					if (!Recognize_DotGram_Guard0(guardCaptured0)) { expected = null; goto Fail; }
					goto Return;
				}

				S13:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 2 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 1, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 1, p, entries.Count, text, "Row");
				}

				S14:
				{
					if ((uint)p >= (uint)text.Length || text[p] != ',')
					{
						expected = ExpectedSet_DotGram(6);
						goto Fail;
					}
					p += 1;
				}

				S15:
				{
					capture5 = p;
				}

				S16:
				{
					if ((uint)p >= (uint)text.Length)
					{
						expected = ExpectedSet_DotGram(5);
						goto Fail;
					}
					c = text[p];
					if (!(((c >= '0' && c <= '9'))))
					{
						expected = ExpectedSet_DotGram(5);
						goto Fail;
					}
					p++;
				}

				S17:
				{
					if ((uint)p >= (uint)text.Length)
					{
						expected = ExpectedSet_DotGram(5);
						goto S18;
					}
					c = text[p];
					if (!(((c >= '0' && c <= '9'))))
					{
						expected = ExpectedSet_DotGram(5);
						goto S18;
					}
					p++;
					goto S17;
				}

				S18:
				{
					entries.Add(new ParserEntry(ParserEntry.Capture, 5, capture5, call, atomic, repeat, lookahead, p));
					Trace("capture", 5, p, entries.Count, text, "Row");
				}

				S19:
				{
					if (text.Length - p >= 2 && global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 2), global::System.MemoryExtensions.AsSpan("\r\n")))
					{
						p += 2;
						goto Return;
					}
					if ((uint)p < (uint)text.Length && text[p] == '\n')
					{
						p += 1;
						goto Return;
					}
					if ((uint)p < (uint)text.Length && text[p] == '\r')
					{
						p += 1;
						goto Return;
					}
					expected = ExpectedSet_DotGram(1);
					p = Recognize_DotGram_Sharpen0(text, p, ref expected);
					goto Fail;
				}

				S20:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 1 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 0, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 0, p, entries.Count, text, "Csv");
					goto S5;
				}

				S21:
				{
					var repeatIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Repeat, 0, p, call, atomic, repeat, lookahead, 0));
					repeat = repeatIndex;
					Trace("enter repeat", 5, p, entries.Count, text, "Csv");
					goto S5;
				}

				S22:
				{
					if ((uint)p < (uint)text.Length)
					{
						c = text[p];
						if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')) goto S21;
					}
					goto S3;
				}

				S23:
				{
					var closed  = 0;
					var openedAt = entries.Count - 1;

					for (; openedAt >= 0; openedAt--)
					{
						var opened = entries[openedAt];

						if (opened.State != 4) continue;

						if (opened.Kind == ParserEntry.Capture)
						{
							closed++;
							continue;
						}

						if (opened.Kind != ParserEntry.CaptureOpen)
							continue;

						if (closed == 0)
							break;

						closed--;
					}

					global::System.Diagnostics.Debug.Assert(openedAt >= 0);
					entries.Add(new ParserEntry(ParserEntry.Capture, 4, entries[openedAt].Position, call, atomic, repeat, lookahead, p));
					Trace("capture", 4, p, entries.Count, text, "Amount");
					goto Return;
				}

				S24:
				{
					if ((uint)p >= (uint)text.Length)
					{
						expected = ExpectedSet_DotGram(5);
						goto S23;
					}
					c = text[p];
					if (!(((c >= '0' && c <= '9'))))
					{
						expected = ExpectedSet_DotGram(5);
						goto S23;
					}
					p++;
					goto S24;
				}

				S25:
				{
					if ((uint)p >= (uint)text.Length)
					{
						expected = ExpectedSet_DotGram(5);
						goto Fail;
					}
					c = text[p];
					if (!(((c >= '0' && c <= '9'))))
					{
						expected = ExpectedSet_DotGram(5);
						goto Fail;
					}
					p++;
					goto S24;
				}

				S26:
				{
					entries.Add(new ParserEntry(ParserEntry.CaptureOpen, 4, p, call, atomic, repeat, lookahead, 0));
					Trace("open capture", 4, p, entries.Count, text, "Amount");
					goto S25;
				}

				S27:
				{
					p = turn0;
					goto Return;
				}

				S28:
				{
					p = turn0;
					expected = ExpectedSet_DotGram(0);
					goto Fail;
				}

				S29:
				{
					if ((uint)p >= (uint)text.Length)
					{
						expected = ExpectedSet_DotGram(8);
						goto S27;
					}
					p++;
					goto S28;
				}

				S30:
				{
					turn0 = p;
					goto S29;
				}

				Return:
				global::System.Diagnostics.Debug.Assert(call >= 0 && call < entries.Count);
				var returned = entries[call];
				global::System.Diagnostics.Debug.Assert(returned.Kind == ParserEntry.Call || returned.Kind == ParserEntry.Completed);
				state = returned.State;
				var previousCall = returned.CallIndex;
				completedCall = call;
				repeat = returned.RepeatIndex;
				lookahead = returned.LookaheadIndex;

				if (returned.RuleIndex >= 0)
				{
					entries[call] = new ParserEntry(ParserEntry.Completed, returned.State, returned.Position, returned.CallIndex, returned.AtomicIndex, returned.RepeatIndex, returned.LookaheadIndex, p, returned.RuleIndex);
				}
				else if (entries.Count == call + 1)
					entries.RemoveAt(call);

				call = previousCall;
				Trace("return", state, p, entries.Count, text, "");
				goto Dispatch;

				Accept:
				if (whole && p != text.Length) { expected = ExpectedSet_DotGram(0); goto Fail; }
				if (materialize)
				{
					if (rootRule >= 0)
					{
						var values = parser.Materialization(entries.Count);
						var values0 = parser.Materialization0();
						var values1 = parser.Materialization1();
						var values2 = parser.Materialization2();
						Materialize_DotGram(text, parser, entries);
						switch (rootRule)
						{
							case 0:
								recognized = values0[0];
								break;
							case 1:
								recognized = values1[0];
								break;
							case 2:
								recognized = values1[0];
								break;
							case 3:
								recognized = values2[0];
								break;
							default:
								recognized = values[0];
								break;
						}
					}
				}
				return p;

				Fail:
				if (lookahead < 0 && p > failure.Position)
				{
					failure.Position = p;
					failure.Expected = expected;
					failure.ExpectedMore?.Clear();
				}
				else if (lookahead < 0 && p == failure.Position && expected != null)
				{
					(failure.ExpectedMore ??= new global::System.Collections.Generic.List<string[]>()).Add(expected);
				}
				Trace("fail", state, p, entries.Count, text, "");

				while (entries.Count > 0)
				{
					var last = entries.Count - 1;
					var entry = entries[last];
					entries.RemoveAt(last);

					if (entry.Kind == ParserEntry.Choice)
					{
						state  = entry.State;
						p      = entry.Position;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						Trace("resume", state, p, entries.Count, text, "");
						goto Dispatch;
					}
					if (entry.Kind == ParserEntry.LoopExit)
					{
						if (entry.RepeatIndex < 0 || entries[entry.RepeatIndex].Kind != ParserEntry.Repeat || entries[entry.RepeatIndex].RuleIndex != entry.Position)
							continue;

						state  = entry.State;
						p      = entry.Position;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						Trace("resume exit", state, p, entries.Count, text, "");
						goto Dispatch;
					}
					if (entry.Kind == ParserEntry.Capture || entry.Kind == ParserEntry.Construct || entry.Kind == ParserEntry.RuleCapture || entry.Kind == ParserEntry.CaptureOpen)
						continue;

					if (entry.Kind == ParserEntry.Call || entry.Kind == ParserEntry.Completed)
					{
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						p      = entry.Position;
					}
					else if (entry.Kind == ParserEntry.Atomic)
					{
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
					}
					else if (entry.Kind == ParserEntry.Repeat)
					{
						p      = entry.Position;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
					}
					else
					{
						global::System.Diagnostics.Debug.Assert(entry.Kind == ParserEntry.Lookahead);
						p         = entry.Position;
						call      = entry.CallIndex;
						atomic    = entry.AtomicIndex;
						repeat    = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;

						if (entry.Value == 0)
						{
							state = entry.State;
							if (entry.RuleIndex >= 0)
							{
								entries.Add(new ParserEntry(ParserEntry.Capture, entry.RuleIndex, p, call, atomic, repeat, lookahead, p));
								Trace("capture negative lookahead", entry.RuleIndex, p, entries.Count, text, "");
							}
							Trace("negative lookahead succeeds", state, p, entries.Count, text, "");
							goto Dispatch;
						}
					}
				}

				return -1;
			}
			finally
			{
				parser.Reset();
				if (lent) ReturnParser(parser); else Recycle(parser);
			}
		}

		static int Scan_eof(global::System.ReadOnlySpan<char> text, int pos)
		{
			var p = pos;
			var mark0 = 0;

			mark0 = p;
			if ((uint)p >= (uint)text.Length) goto L0_absent;
			p++;
			p = mark0;
			goto Refuse;
			L0_absent: ;

			return p;

			Refuse:
			return -1 - p;
		}

		static int Recognize_Csv(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out string[] value)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 22, 0, false, true, ref failure, out recognized);
			value = end < 0 ? default! : (string[])recognized!;
			return end;
		}

		static int Recognize_Row(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out string value)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 7, 1, false, true, ref failure, out recognized);
			value = end < 0 ? default! : (string)recognized!;
			return end;
		}

		static int Recognize_Name(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out string value)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 8, 2, false, true, ref failure, out recognized);
			value = end < 0 ? default! : (string)recognized!;
			return end;
		}

		static int Recognize_Amount(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out int value)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 26, 3, false, true, ref failure, out recognized);
			value = end < 0 ? default! : (int)recognized!;
			return end;
		}

		static int Recognize_eof(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 30, -1, false, true, ref failure, out recognized);
			return end;
		}

		static int Recognize_eol(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure)
		{
			object? recognized;
			var end = Recognize_DotGram(text, pos, 19, -1, false, true, ref failure, out recognized);
			return end;
		}

		static int Recognize_DotGram_Sharpen0(global::System.ReadOnlySpan<char> text, int p, ref string[]? expected)
		{
			if ((uint)p < (uint)text.Length && text[p] == '\r')
			{
				p += 1;
				expected = ExpectedSet_DotGram(2);
				if ((uint)p < (uint)text.Length && text[p] == '\n')
				{
					p += 1;
					expected = ExpectedSet_DotGram(3);
				}
			}
			else if ((uint)p < (uint)text.Length && text[p] == '\n')
			{
				p += 1;
				expected = ExpectedSet_DotGram(4);
			}
			return p;
		}

		static bool Recognize_DotGram_Guard0(string text) =>
#line 25 "Csv.gram"
                                                      (text.Length <= 16);
#line default

		static void Materialize_DotGram(global::System.ReadOnlySpan<char> text, Parser parser, ParserArena entries)
		{
			var values = parser.Materialization(entries.Count);
			var values0 = parser.Materialization0();
			var values1 = parser.Materialization1();
			var values2 = parser.Materialization2();
			var linkHeads = parser.MaterializationHeads();
			var linkNexts = parser.MaterializationNexts();

			for (var derivationAt = parser.LinkedUpTo; derivationAt < entries.Count; derivationAt++)
			{
				var derivation = entries[derivationAt];
				if (derivation.CallIndex >= 0 && (derivation.Kind == ParserEntry.Capture || derivation.Kind == ParserEntry.RuleCapture || derivation.Kind == ParserEntry.Construct))
				{
					linkNexts[derivationAt] = linkHeads[derivation.CallIndex];
					linkHeads[derivation.CallIndex] = derivationAt;
				}
			}
			parser.LinkedUpTo = entries.Count;

			values[0] = parser;

			var owners     = parser.MaterializationOwners();
			var ownerCount = 0;

			owners[ownerCount++] = 0;

			for (var ownerIndex = 0; ownerIndex < ownerCount; ownerIndex++)
			{
				var ownerAt = owners[ownerIndex];

				for (var capturedAt = linkHeads[ownerAt]; capturedAt >= 0; capturedAt = linkNexts[capturedAt])
				{
					var candidate = entries[capturedAt];

					if (candidate.Kind == ParserEntry.RuleCapture && !global::System.Object.ReferenceEquals(values[candidate.Position], parser))
					{
						values[candidate.Position] = parser;
						owners[ownerCount++] = candidate.Position;
					}
				}
			}

			for (var ownerIndex = ownerCount - 1; ownerIndex >= 0; ownerIndex--)
			{
				var completedAt = owners[ownerIndex];
				var completed = entries[completedAt];
				if (completed.Kind != ParserEntry.Completed || !global::System.Object.ReferenceEquals(values[completedAt], parser)) continue;
				switch (completed.RuleIndex)
				{
					case 0:
					{
						var captured0Count = 0;
						for (var capturedAt0 = linkHeads[completedAt]; capturedAt0 >= 0; capturedAt0 = linkNexts[capturedAt0])
						{
							var candidate = entries[capturedAt0];
							if (candidate.Kind == ParserEntry.RuleCapture && candidate.CallIndex == completedAt && (candidate.State == 0)) captured0Count++;
						}
						var captured0 = (captured0Count == 0 ? global::System.Array.Empty<string>() : new string[captured0Count]);
						var captured0Item = captured0Count;
						for (var capturedAt0 = linkHeads[completedAt]; capturedAt0 >= 0; capturedAt0 = linkNexts[capturedAt0])
						{
							var candidate = entries[capturedAt0];
							if (candidate.Kind == ParserEntry.RuleCapture && candidate.CallIndex == completedAt && (candidate.State == 0))
							{
								captured0[--captured0Item] = values1[candidate.Position];
							}
						}

						values0[completedAt] = Construct_Csv(captured0!);
						break;
					}
					case 1:
					{
						var captured0At = -1;
						var captured1_0From = -1;
						var captured1_0To   = -1;
						for (var capturedAt = linkHeads[completedAt]; capturedAt >= 0; capturedAt = linkNexts[capturedAt])
						{
							var candidate = entries[capturedAt];

							switch (candidate.State)
							{
								case 1:
									if (candidate.Kind == ParserEntry.RuleCapture && candidate.CallIndex == completedAt && captured0At < 0)
										captured0At = candidate.Position;
									break;
								case 5:
									if (candidate.Kind == ParserEntry.Capture && candidate.CallIndex == completedAt)
									{
										if (captured1_0To < 0)
											captured1_0To = candidate.Value;
										captured1_0From = candidate.Position;
									}
									break;
							}
						}

						global::System.Diagnostics.Debug.Assert(captured0At >= 0);
						var captured0 = values1[captured0At];

						global::System.Diagnostics.Debug.Assert(captured1_0From >= 0);
						var captured1 = Construct_Amount(captured1_0From < 0 ? string.Empty : text.Slice(captured1_0From, captured1_0To - captured1_0From).ToString());

						values1[completedAt] = Construct_Row(captured0!, captured1!);
						break;
					}
					case 2:
					{
						var captured0From = -1;
						var captured0To   = -1;
						for (var capturedAt = linkHeads[completedAt]; capturedAt >= 0; capturedAt = linkNexts[capturedAt])
						{
							var candidate = entries[capturedAt];

							switch (candidate.State)
							{
								case 3:
									if (candidate.Kind == ParserEntry.Capture && candidate.CallIndex == completedAt)
									{
										if (captured0To < 0)
											captured0To = candidate.Value;
										captured0From = candidate.Position;
									}
									break;
							}
						}

						#if DEBUG
						if (captured0From >= 0 && captured0To < captured0From)
							throw new global::System.InvalidOperationException("DotGram invariant: capture 'text' of rule 'Name' has its end before its start (" + captured0From.ToString() + ".." + captured0To.ToString() + "). This is a generator defect; please report the grammar.");
						#endif
						var captured0 = captured0From < 0 ? string.Empty : text.Slice(captured0From, captured0To - captured0From).ToString();

						values1[completedAt] = Construct_Name(captured0!);
						break;
					}
					case 3:
					{
						var captured0From = -1;
						var captured0To   = -1;
						for (var capturedAt = linkHeads[completedAt]; capturedAt >= 0; capturedAt = linkNexts[capturedAt])
						{
							var candidate = entries[capturedAt];

							switch (candidate.State)
							{
								case 4:
									if (candidate.Kind == ParserEntry.Capture && candidate.CallIndex == completedAt)
									{
										if (captured0To < 0)
											captured0To = candidate.Value;
										captured0From = candidate.Position;
									}
									break;
							}
						}

						#if DEBUG
						if (captured0From >= 0 && captured0To < captured0From)
							throw new global::System.InvalidOperationException("DotGram invariant: capture 'digits' of rule 'Amount' has its end before its start (" + captured0From.ToString() + ".." + captured0To.ToString() + "). This is a generator defect; please report the grammar.");
						#endif
						var captured0 = captured0From < 0 ? string.Empty : text.Slice(captured0From, captured0To - captured0From).ToString();

						values2[completedAt] = Construct_Amount(captured0!);
						break;
					}
				}
			}
		}

		struct Failure
		{
			public int Position;

			// Nothing assigns this here: every test in this grammar wants one character.
			// A field nothing assigns is CS0649 in somebody else's build, which for one
			// that treats warnings as errors is a broken compilation of a file they did
			// not write.
			#pragma warning disable 0649
			public int OutOfInput;
			#pragma warning restore 0649

			public string[]? Expected;

			public global::System.Collections.Generic.List<string[]>? ExpectedMore;
		}

		private sealed class Parser
		{
			internal readonly ParserArena Entries = new ParserArena();
			object?[] _values = global::System.Array.Empty<object?>();
			string[][] _values0 = global::System.Array.Empty<string[]>();
			string[] _values1 = global::System.Array.Empty<string>();
			int[] _values2 = global::System.Array.Empty<int>();
			int[] _linkHeads = global::System.Array.Empty<int>();
			int[] _linkNexts = global::System.Array.Empty<int>();

			int[] _owners = global::System.Array.Empty<int>();
			internal int LinkedUpTo;
			int _valuesUsed;

			internal object?[] Materialization(int count)
			{
				// Doubled, not sized to fit exactly: a `when` guard calls this once per
				// evaluation, and a repeated record with a guard inside the repeat would
				// otherwise pay for a fresh copy of the whole table on every turn, turning
				// an O(n) parse back into the O(n^2) the incremental materializer exists to
				// avoid.
				if (_values.Length < count)
					global::System.Array.Resize(ref _values, global::System.Math.Max(count, _values.Length * 2));
				if (_values0.Length < count)
					global::System.Array.Resize(ref _values0, global::System.Math.Max(count, _values0.Length * 2));
				if (_values1.Length < count)
					global::System.Array.Resize(ref _values1, global::System.Math.Max(count, _values1.Length * 2));
				if (_values2.Length < count)
					global::System.Array.Resize(ref _values2, global::System.Math.Max(count, _values2.Length * 2));

				// Grown here, alongside the value table, rather than where the links are
				// read — a guard that finds everything it needs already built calls this
				// and nothing else, and a link table sized only where it is read would fall
				// out of step with `_valuesUsed`, which is exactly what Reset and Truncate
				// walk off the end of.
				Grow(ref _linkHeads, count);
				Grow(ref _linkNexts, count);

				// No `Grow`: nothing here is carried between calls, so a plain resize is
				// what it needs and the -1 fill would be work for nobody.
				if (_owners.Length < count)
					global::System.Array.Resize(ref _owners, global::System.Math.Max(count, _owners.Length * 2));

				_valuesUsed = count;

				return _values;
			}

			internal string[][] Materialization0() { return _values0; }
			internal string[] Materialization1() { return _values1; }
			internal int[] Materialization2() { return _values2; }

			internal int[] MaterializationHeads() => _linkHeads;
			internal int[] MaterializationNexts() => _linkNexts;
			internal int[] MaterializationOwners() => _owners;

			// Grown, not rebuilt: a link written for an index below `count` on an earlier,
			// smaller call is still the answer for that index, and re-zeroing it would erase
			// it. Only the newly reachable slots need a fresh -1.
			static void Grow(ref int[] links, int count)
			{
				if (links.Length < count)
				{
					var from = links.Length;

					global::System.Array.Resize(ref links, global::System.Math.Max(count, from * 2));

					for (var i = from; i < links.Length; i++)
						links[i] = -1;
				}
			}

			internal void Reset()
			{
				Entries.Clear();
				global::System.Array.Clear(_values, 0, _valuesUsed);
				global::System.Array.Clear(_values0, 0, global::System.Math.Min(_valuesUsed, _values0.Length));
				global::System.Array.Clear(_values1, 0, global::System.Math.Min(_valuesUsed, _values1.Length));
				global::System.Array.Clear(_values2, 0, global::System.Math.Min(_valuesUsed, _values2.Length));

				// A rule call that captures nothing this parse never writes its own head, so
				// whatever a previous parse through the same pooled slot left there has to be
				// cleared here instead — otherwise a lookup falls through to a stale chain from
				// an earlier parse, one that can splice into a cycle once enough reuse has
				// pointed two heads at each other.
				for (var i = 0; i < _valuesUsed; i++)
				{
					_linkHeads[i] = -1;
					_linkNexts[i] = -1;
				}

				_valuesUsed = 0;
				LinkedUpTo = 0;
			}
		}

		private sealed class ParserArena
		{
			ParserEntry[] _items = global::System.Array.Empty<ParserEntry>();

			internal int Count { get; private set; }

			internal int Capacity { get { return _items.Length; } }

			internal ParserEntry this[int index]
			{
				get => _items[index];
				set => _items[index] = value;
			}

			internal void Add(ParserEntry entry)
			{
				if (Count == _items.Length)
					global::System.Array.Resize(ref _items, Count == 0 ? 16 : Count * 2);

				_items[Count++] = entry;
			}

			internal void RemoveAt(int index)
			{
				var after = Count - index - 1;

				if (after > 0)
					global::System.Array.Copy(_items, index + 1, _items, index, after);

				Count--;
			}

			internal void RemoveRange(int index, int count)
			{
				if (count == 0)
					return;

				var after = Count - index - count;

				if (after > 0)
					global::System.Array.Copy(_items, index + count, _items, index, after);

				Count -= count;
			}

			internal void Clear()
			{
				Count = 0;
			}
		}

		private readonly struct ParserEntry
		{
			internal const int Choice = 1;
			internal const int Call   = 2;
			internal const int Atomic = 3;
			internal const int Repeat = 4;
			internal const int Lookahead = 5;
			internal const int Capture = 6;
			internal const int Construct = 7;
			internal const int Completed = 8;
			internal const int RuleCapture = 9;
			internal const int Dead = 10;
			internal const int Recovery = 11;
			internal const int PendingRecovery = 12;
			internal const int Run = 13;

			internal const int LoopExit = 14;

			internal const int TurnDone = 15;

			internal const int CaptureOpen = 16;

			internal const int StateSet = 17;

			internal const int StateEnd = 18;

			internal ParserEntry(
				int kind, int state, int position, int callIndex, int atomicIndex,
				int repeatIndex, int lookaheadIndex, int value, int ruleIndex = -1)
			{
				Kind        = kind;
				State       = state;
				Position    = position;
				CallIndex   = callIndex;
				AtomicIndex = atomicIndex;
				RepeatIndex = repeatIndex;
				LookaheadIndex = lookaheadIndex;
				Value       = value;
				RuleIndex   = ruleIndex;
			}

			internal int Kind        { get; }
			internal int State       { get; }
			internal int Position    { get; }
			internal int CallIndex   { get; }
			internal int AtomicIndex { get; }
			internal int RepeatIndex { get; }
			internal int LookaheadIndex { get; }
			internal int Value       { get; }
			internal int RuleIndex   { get; }
		}

		static partial void RentParser(ref Parser parser);
		static partial void ReturnParser(Parser parser);

		[global::System.ThreadStatic]
		static Parser? _spareParser;

		[global::System.ThreadStatic]
		static Parser?[]? _deeperParsers;

		[global::System.ThreadStatic]
		static int _deeperParserCount;

		const int KeptEntries = 65536;

		[global::System.ThreadStatic]
		static Parser? _largeParser;

		[global::System.ThreadStatic]
		static int _largeParserIdle;

		[global::System.ThreadStatic]
		static global::System.WeakReference<Parser>? _largeParserLetGo;

		[global::System.ThreadStatic]
		static int _spareParserIdle;

		[global::System.ThreadStatic]
		static global::System.WeakReference<Parser>? _spareParserLetGo;

		const int LargeParserIdle = 8;

		const int SpareParserIdle = 8;

		static Parser Recycled()
		{
			var spare = _spareParser;

			if (spare != null)
				_spareParser = null;
			else if (_deeperParserCount > 0)
			{
				spare = _deeperParsers![--_deeperParserCount]!;
				_deeperParsers![_deeperParserCount] = null;
			}
			else if (_largeParser != null)
			{
				spare = _largeParser;
				_largeParser = null;
			}
			else if (_largeParserLetGo != null && _largeParserLetGo.TryGetTarget(out var letGo))
			{
				spare = letGo;
				_largeParserLetGo.SetTarget(null!);
			}
			else if (_spareParserLetGo != null && _spareParserLetGo.TryGetTarget(out var letGoSpare))
			{
				spare = letGoSpare;
				_spareParserLetGo.SetTarget(null!);
			}
			else
				return new Parser();
			return spare;
		}

		static void Recycle(Parser parser)
		{
			if (parser.Entries.Capacity > KeptEntries)
			{
				if (_largeParser != null && !ReferenceEquals(_largeParser, parser))
					(_largeParserLetGo ??= new global::System.WeakReference<Parser>(_largeParser)).SetTarget(_largeParser);

				// The same question the ordinary slot asks below: is the room far larger than the
				// use. The bound decides which slot holds the arena, not whether to keep it.
				if (parser.Entries.Capacity <= 4 * parser.Entries.Count)
					_largeParserIdle = 0;
				else if (++_largeParserIdle >= LargeParserIdle)
				{
					(_largeParserLetGo ??= new global::System.WeakReference<Parser>(parser)).SetTarget(parser);
					_largeParser = null;
					_largeParserIdle = 0;

					return;
				}

				_largeParser = parser;

				return;
			}

			// The ordinary slot lets go by the rule the parked one uses. Room and use are the
			// list's own two numbers, which is as commensurable as it gets; four times and not
			// twice because a list grows by doubling, so one doubling is ordinary slack.
			if (parser.Entries.Capacity <= 4 * parser.Entries.Count)
				_spareParserIdle = 0;
			else if (++_spareParserIdle >= SpareParserIdle)
			{
				(_spareParserLetGo ??= new global::System.WeakReference<Parser>(parser)).SetTarget(parser);
				_spareParserIdle = 0;

				return;
			}

			if (_spareParser == null)
				_spareParser = parser;
			else if (_deeperParserCount < 3)
				(_deeperParsers ??= new Parser?[3])[_deeperParserCount++] = parser;
		}

		[global::System.Diagnostics.Conditional("DOTGRAM_STEPS")]
		static void Trace(string action, int state, int position, int arena)
		{
			global::System.Console.Error.WriteLine(
				".Gram " + action + " state=" + state.ToString() +
				" at " + position.ToString() + " arena=" + arena.ToString());
		}

		[global::System.Diagnostics.Conditional("DOTGRAM_STEPS")]
		static void Trace(
			string action, int state, int position, int arena,
			global::System.ReadOnlySpan<char> text, string rule)
		{
			var from   = position > 16 ? position - 16 : 0;
			var to     = position + 16 < text.Length ? position + 16 : text.Length;
			var window =
				(from < position && position <= text.Length ? text.Slice(from, position - from).ToString() : "") +
				"^" +
				(position >= 0 && position < to ? text.Slice(position, to - position).ToString() : "");

			window = window
				.Replace("\r", "\\r")
				.Replace("\n", "\\n")
				.Replace("\t", "\\t");

			global::System.Console.Error.WriteLine(
				".Gram " + action + (rule.Length > 0 ? " in " + rule : "") +
				" state=" + state.ToString() + " at " + position.ToString() +
				" \"" + window + "\" arena=" + arena.ToString());
		}

		// The sets a refusal names, by number: built the first time a refusal asks for one, never in the
		// type's initializer, and then the same array for as long as the process lives, because refusals
		// tell sets apart by reference.
		static string[]?[]? ExpectedBuilt_DotGram;
		static string[]? ExpectedItems_DotGram;
		static int[]? ExpectedStarts_DotGram;

		static string[] ExpectedSet_DotGram(int id)
		{
			var built = ExpectedBuilt_DotGram;

			if (built != null)
			{
				var set = built[id];

				if (set != null)
					return set;
			}

			return ExpectedDecoded_DotGram(id);
		}

		static string[] ExpectedDecoded_DotGram(int id)
		{
			var data = "ACGJLNPRTBADBCDCBDBBBCBEBFBGBH";
			var built = ExpectedBuilt_DotGram ?? global::System.Threading.Interlocked.CompareExchange(ref ExpectedBuilt_DotGram, new string[]?[9], null) ?? ExpectedBuilt_DotGram!;
			var items = ExpectedItems_DotGram ?? global::System.Threading.Interlocked.CompareExchange(ref ExpectedItems_DotGram, new string[]
				{
					"end of input",
					"\"\\r\\n\"",
					"'\\n'",
					"'\\r'",
					"['0'..'9']",
					"','",
					"['A'..'Z' | 'a'..'z']",
					"[^ ]",
				}, null) ?? ExpectedItems_DotGram!;
			var starts = ExpectedStarts_DotGram;
			var at = 0;
			int value;

			if (starts == null)
			{
				starts = new int[9];

				for (var i = 0; i < starts.Length; i++)
				{
					value = 0;
					while (data[at] >= 0x60)
						value = value << 5 | data[at++] & 0x1F;
					value = (value << 5 | data[at++] & 0x1F) - 1;
					starts[i] = value;
				}

				for (var i = 0; i < starts.Length; i++)
					starts[i] += at;

				starts = global::System.Threading.Interlocked.CompareExchange(ref ExpectedStarts_DotGram, starts, null) ?? starts;
			}

			at = starts[id];
			value = 0;
			while (data[at] >= 0x60)
				value = value << 5 | data[at++] & 0x1F;
			value = (value << 5 | data[at++] & 0x1F) - 1;

			var set = new string[value];

			for (var i = 0; i < set.Length; i++)
			{
				value = 0;
				while (data[at] >= 0x60)
					value = value << 5 | data[at++] & 0x1F;
				value = (value << 5 | data[at++] & 0x1F) - 1;
				set[i] = items[value];
			}

			return global::System.Threading.Interlocked.CompareExchange(ref built[id], set, null) ?? set;
		}
	}
}
