// <auto-generated/>
#nullable enable

namespace DotGram.Snapshots
{
	partial class Feed
	{
		/// <summary>Parses the whole input as <c>Feed</c>.</summary>
		public static string ParseFeed(string input)
		{
			if (TryParseFeed(input, out var value, out var error, out var errorPosition))
				return value;

			throw new global::System.FormatException(error + " at " + errorPosition.ToString());
		}

		public static bool TryParseFeed(string input, out string value, out string? error, out int errorPosition)
		{
			var text = global::System.MemoryExtensions.AsSpan(input);

			value = "";
			error         = null;
			errorPosition = 0;

			var end = Recognize_Feed(text, 0);

			if (end < 0)
			{
				error = "Input does not match 'Feed'.";
				return false;
			}

			if (end != input.Length)
			{
				error         = "Unexpected input.";
				errorPosition = end;
				return false;
			}

			value = input.Substring(0, end);
			return true;
		}

		/// <summary>Matches <c>Row</c> at the start of the input.</summary>
		public static string? MatchRow(string input)
		{
			if (TryMatchRow(input, out var value, out var error, out var errorPosition))
				return value;

			return null;
		}

		public static bool TryMatchRow(string input, out string value, out string? error, out int errorPosition)
		{
			var text = global::System.MemoryExtensions.AsSpan(input);

			value = "";
			error         = null;
			errorPosition = 0;

			var end = Recognize_Row(text, 0);

			if (end < 0)
			{
				error = "Input does not match 'Row'.";
				return false;
			}

			value = input.Substring(0, end);
			return true;
		}

		/// <summary>Finds the first occurrence of <c>Name</c>.</summary>
		public static string? FindName(string input)
		{
			if (TryFindName(input, out var value, out var error, out var errorPosition))
				return value;

			return null;
		}

		public static bool TryFindName(string input, out string value, out string? error, out int errorPosition)
		{
			var text = global::System.MemoryExtensions.AsSpan(input);

			value = "";
			error         = null;
			errorPosition = 0;

			for (var start = 0; start <= input.Length; start++)
			{
				var end = Recognize_Name(text, start);

				if (end >= 0)
				{
					value = input.Substring(start, end - start);
					return true;
				}
			}

			error = "No occurrence of 'Name'.";
			return false;
		}

		/// <summary>Finds every non-overlapping occurrence of <c>Row</c>.</summary>
		public static string[] AllRows(string input)
		{
			if (TryAllRows(input, out var values, out var error, out var errorPosition))
				return values;

			return new string[0];
		}

		public static bool TryAllRows(string input, out string[] values, out string? error, out int errorPosition)
		{
			var text = global::System.MemoryExtensions.AsSpan(input);

			values = new string[0];
			error         = null;
			errorPosition = 0;

			var found = new global::System.Collections.Generic.List<string>();

			for (var start = 0; start <= input.Length; )
			{
				var end = Recognize_Row(text, start);

				if (end < 0)
				{
					start++;
					continue;
				}

				found.Add(input.Substring(start, end - start));

				// A rule that matches nothing would otherwise find it for ever.
				start = end > start ? end : start + 1;
			}

			if (found.Count == 0)
			{
				error = "No occurrence of 'Row'.";
				return false;
			}

			values = found.ToArray();
			return true;
		}

		static int Recognize_Feed(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				p = N1(text, p);

				if (p < 0)
					return -1;

				p = N2(text, p);

				if (p < 0)
					return -1;

				p = N4(text, p);

				if (p < 0)
					return -1;

				p = N5(text, p);

				if (p < 0)
					return -1;

				return p;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Header(text, p);
			}

			static int N2(global::System.ReadOnlySpan<char> text, int p)
			{
				while (true)
				{
					var next = N3(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
				}

				return p;
			}

			static int N3(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Row(text, p);
			}

			static int N4(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Trailer(text, p);
			}

			static int N5(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_eof(text, p);
			}
		}

		static int Recognize_Header(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				p = N1(text, p);

				if (p < 0)
					return -1;

				p = N2(text, p);

				if (p < 0)
					return -1;

				p = N3(text, p);

				if (p < 0)
					return -1;

				p = N4(text, p);

				if (p < 0)
					return -1;

				return p;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != 'H')
					return -1;

				return p + 1;
			}

			static int N2(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Sep(text, p);
			}

			static int N3(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Date(text, p);
			}

			static int N4(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_eol(text, p);
			}
		}

		static int Recognize_Row(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				p = N1(text, p);

				if (p < 0)
					return -1;

				p = N2(text, p);

				if (p < 0)
					return -1;

				p = N3(text, p);

				if (p < 0)
					return -1;

				p = N4(text, p);

				if (p < 0)
					return -1;

				p = N5(text, p);

				if (p < 0)
					return -1;

				p = N6(text, p);

				if (p < 0)
					return -1;

				return p;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != 'R')
					return -1;

				return p + 1;
			}

			static int N2(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Sep(text, p);
			}

			static int N3(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Name(text, p);
			}

			static int N4(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Sep(text, p);
			}

			static int N5(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Amount(text, p);
			}

			static int N6(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_eol(text, p);
			}
		}

		static int Recognize_Trailer(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				p = N1(text, p);

				if (p < 0)
					return -1;

				p = N2(text, p);

				if (p < 0)
					return -1;

				p = N3(text, p);

				if (p < 0)
					return -1;

				p = N4(text, p);

				if (p < 0)
					return -1;

				return p;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != 'T')
					return -1;

				return p + 1;
			}

			static int N2(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Sep(text, p);
			}

			static int N3(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Count(text, p);
			}

			static int N4(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_eol(text, p);
			}
		}

		static int Recognize_Sep(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != '|')
					return -1;

				return p + 1;
			}
		}

		static int Recognize_Digit(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p >= text.Length)
					return -1;

				var c = text[p];

				return ((c >= '0' && c <= '9')) ? p + 1 : -1;
			}
		}

		static int Recognize_Count(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (true)
				{
					var next = N1(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return count >= 1 ? p : -1;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Digit(text, p);
			}
		}

		static int Recognize_Date(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				p = N1(text, p);

				if (p < 0)
					return -1;

				p = N3(text, p);

				if (p < 0)
					return -1;

				p = N4(text, p);

				if (p < 0)
					return -1;

				p = N6(text, p);

				if (p < 0)
					return -1;

				p = N7(text, p);

				if (p < 0)
					return -1;

				return p;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (count < 4)
				{
					var next = N2(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return count >= 4 ? p : -1;
			}

			static int N2(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Digit(text, p);
			}

			static int N3(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != '-')
					return -1;

				return p + 1;
			}

			static int N4(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (count < 2)
				{
					var next = N5(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return count >= 2 ? p : -1;
			}

			static int N5(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Digit(text, p);
			}

			static int N6(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != '-')
					return -1;

				return p + 1;
			}

			static int N7(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (count < 2)
				{
					var next = N8(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return count >= 2 ? p : -1;
			}

			static int N8(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Digit(text, p);
			}
		}

		static int Recognize_Amount(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				p = N1(text, p);

				if (p < 0)
					return -1;

				p = N3(text, p);

				if (p < 0)
					return -1;

				p = N5(text, p);

				if (p < 0)
					return -1;

				return p;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (count < 1)
				{
					var next = N2(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return p;
			}

			static int N2(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != '-')
					return -1;

				return p + 1;
			}

			static int N3(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (true)
				{
					var next = N4(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return count >= 1 ? p : -1;
			}

			static int N4(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Digit(text, p);
			}

			static int N5(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (count < 1)
				{
					var next = N6(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return p;
			}

			static int N6(global::System.ReadOnlySpan<char> text, int p)
			{
				p = N7(text, p);

				if (p < 0)
					return -1;

				p = N8(text, p);

				if (p < 0)
					return -1;

				return p;
			}

			static int N7(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != '.')
					return -1;

				return p + 1;
			}

			static int N8(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (count < 2)
				{
					var next = N9(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return count >= 2 ? p : -1;
			}

			static int N9(global::System.ReadOnlySpan<char> text, int p)
			{
				return Recognize_Digit(text, p);
			}
		}

		static int Recognize_Name(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				var count = 0;

				while (true)
				{
					var next = N1(text, p);

					// A body that matched nothing would loop for ever; the grammar is
					// checked for that, and this is the belt to its braces.
					if (next < 0 || next == p)
						break;

					p = next;
					count++;
				}

				return count >= 1 ? p : -1;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p >= text.Length)
					return -1;

				var c = text[p];

				return !(c == '\n' || c == '\r' || c == '|') ? p + 1 : -1;
			}
		}

		static int Recognize_eof(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				var matched = N1(text, p) >= 0;

				return matched ? -1 : p;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p >= text.Length)
					return -1;

				return p + 1;
			}
		}

		static int Recognize_eol(global::System.ReadOnlySpan<char> text, int pos)
		{
			return N0(text, pos);

			static int N0(global::System.ReadOnlySpan<char> text, int p)
			{
				var r0 = N1(text, p);

				if (r0 >= 0)
					return r0;

				var r1 = N2(text, p);

				if (r1 >= 0)
					return r1;

				var r2 = N3(text, p);

				if (r2 >= 0)
					return r2;

				return -1;
			}

			static int N1(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 2 > text.Length)
					return -1;

				if (text[p + 0] != '\r')
					return -1;
				if (text[p + 1] != '\n')
					return -1;

				return p + 2;
			}

			static int N2(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != '\n')
					return -1;

				return p + 1;
			}

			static int N3(global::System.ReadOnlySpan<char> text, int p)
			{
				if (p + 1 > text.Length)
					return -1;

				if (text[p + 0] != '\r')
					return -1;

				return p + 1;
			}
		}

	}
}
