// <auto-generated/>
#nullable enable

namespace DotGram.Snapshots
{
	partial class Lexical
	{
		static partial class Chained
		{
			/// <summary>Parses the whole input as <c>Program</c>.</summary>
			/// <exception cref="global::System.FormatException">
			/// The input is not <c>Program</c>. <c>TryParseProgram</c> answers instead.
			/// </exception>
			public static string[] ParseProgram(string input)
			{
				var match = TryParseProgram(input);

				if (match.IsSuccess)
					return match.Value;

				throw new global::System.FormatException(match.Error + " at " + match.Position.ToString());
			}

			/// <summary>Parses the whole input as <c>Program</c>, answering rather than throwing.</summary>
			public static Match<string[]> TryParseProgram(string input)
			{
				var source = input;
				var tokens = Tokenize_DotGram(source);

				var starts  = tokens.Starts;
				var lengths = tokens.Lengths;
				var count   = tokens.Count;

				if (tokens.Stopped >= 0)
				{
					var at = tokens.Stopped;

					Recycle_DotGram(tokens);

					var stopped = at < source.Length ? source[at] : '\0';

					return Match<string[]>.Failed(Outcome.NoMatch, at >= source.Length ? "Expected more input." : "Unexpected character '" + (global::System.Char.IsControl(stopped) || stopped == '\'' || stopped == '\\' ? "\\u" + ((int)stopped).ToString("X4", global::System.Globalization.CultureInfo.InvariantCulture) : stopped.ToString()) + "'.", at, null, null);
				}

				var text    = new global::System.ReadOnlySpan<char>(tokens.Kinds, 0, count);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Program_Whole(text, 0, ref failure, out var recognized, source, starts, lengths);

				if (end < 0)
				{
					failure = new Failure();
					end     = Recognize_Program_Whole(text, 0, ref failure, out recognized, source, starts, lengths);
				}

				if (end < 0)
				{
					var starved = failure.OutOfInput == failure.Position + 1 || failure.Position >= text.Length;

					var otherwise = starved
						? "Expected more input."
						: "Input does not match 'Program'.";

					var at = failure.Position < count ? starts[failure.Position] : tokens.Stopped >= 0 ? tokens.Stopped : source.Length;

					Recycle_DotGram(tokens);

					return Match<string[]>.Failed(starved ? Outcome.Starved : Outcome.NoMatch, otherwise, at, failure.Expected, failure.ExpectedMore);
				}

				var whole = recognized;
				var over  = end == 0 ? 0 : starts[end - 1] + lengths[end - 1];

				Recycle_DotGram(tokens);

				return Match<string[]>.Success(whole, 0, over);
			}

			/// <summary>Parses the whole input as <c>Program</c>, answering only whether it is one.</summary>
			/// <remarks>
			/// Nothing is said about a refusal: <c>TryParseProgram</c> returning a match says where and why.
			/// </remarks>
			public static bool TryParseProgram(string input, out string[] value)
			{
				var source = input;
				var tokens = Tokenize_DotGram(source);

				var starts  = tokens.Starts;
				var lengths = tokens.Lengths;
				var count   = tokens.Count;

				if (tokens.Stopped >= 0)
				{
					Recycle_DotGram(tokens);

					value = default!;
					return false;
				}

				var text    = new global::System.ReadOnlySpan<char>(tokens.Kinds, 0, count);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Program_Whole(text, 0, ref failure, out var recognized, source, starts, lengths);

				if (end < 0)
				{
					Recycle_DotGram(tokens);

					value = default!;
					return false;
				}

				value = recognized;

				Recycle_DotGram(tokens);

				return true;
			}

			/// <summary>Reads a <c>Program</c> beginning at <paramref name="at"/>.</summary>
			/// <remarks>
			/// The input is not required to end there: what comes back says where the
			/// reading began and how far it got, so a caller may go on from it. A position
			/// is an offset into the text, and a reading begins at a token, so it begins at the first one at or after it.
			/// </remarks>
			public static Match<string[]> TryParseProgram(string input, int at)
			{
				var source = input;
				var tokens = Tokenized_DotGram(source);

				var starts  = tokens.Starts;
				var lengths = tokens.Lengths;
				var count   = tokens.Count;

				var from = TokenAt_DotGram(starts, count, at);

				if (from < 0)
				{

					return Match<string[]>.Failed(Outcome.Starved, "Expected more input.", source.Length, null, null);
				}

				var text    = new global::System.ReadOnlySpan<char>(tokens.Kinds, 0, count);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Program(text, from, ref failure, out var recognized, source, starts, lengths);

				if (end < 0)
				{
					failure = new Failure();
					end     = Recognize_Program(text, from, ref failure, out recognized, source, starts, lengths);
				}

				var began = starts[from];

				if (end < 0)
				{
					var starved = failure.OutOfInput == failure.Position + 1 || failure.Position >= text.Length;

					var otherwise = starved
						? "Expected more input."
						: "Input does not match 'Program'.";

					var halted = failure.Position < count ? starts[failure.Position] : tokens.Stopped >= 0 ? tokens.Stopped : source.Length;


					return Match<string[]>.Failed(starved ? Outcome.Starved : Outcome.NoMatch, otherwise, halted, failure.Expected, failure.ExpectedMore);
				}

				var whole = recognized;
				var over  = end == 0 ? 0 : starts[end - 1] + lengths[end - 1];


				return Match<string[]>.Success(whole, began, over - began);
			}

			/// <summary>Reads a <c>Program</c> at <paramref name="at"/>, answering only whether one is there.</summary>
			/// <remarks>
			/// Nothing is said about a refusal: <c>TryParseProgram</c> returning a match says where and why.
			/// On a reading, <paramref name="at"/> moves to the end of what was read; on a
			/// refusal it stays where it was.
			/// </remarks>
			public static bool TryParseProgram(string input, ref int at, out string[] value)
			{
				if (at < 0 || at > input.Length)
					throw new global::System.ArgumentOutOfRangeException(nameof(at));

				var source = input;
				var tokens = Tokenized_DotGram(source);

				var starts  = tokens.Starts;
				var lengths = tokens.Lengths;
				var count   = tokens.Count;

				var from = TokenAt_DotGram(starts, count, at);

				if (from < 0)
				{

					value = default!;
					return false;
				}

				var text    = new global::System.ReadOnlySpan<char>(tokens.Kinds, 0, count);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Program(text, from, ref failure, out var recognized, source, starts, lengths);

				if (end < 0)
				{

					value = default!;
					return false;
				}

				var began = starts[from];

				value = recognized;
				at = end == 0 ? 0 : starts[end - 1] + lengths[end - 1];


				return true;
			}

			/// <summary>Reads a <c>Program</c> inside a window of the input.</summary>
			/// <remarks>
			/// The reading begins at <paramref name="at"/> and sees no character from
			/// <c>at + length</c> on; it is not required to reach that far, and what comes back
			/// says how far it got. Positions are offsets into the whole input. Only the window is cut into tokens, so a reading may begin where no token of
			/// the whole input does, and a character no token begins with ends the tokens
			/// there rather than refusing the reading.
			/// </remarks>
			public static Match<string[]> TryParseProgram(string input, int at, int length)
			{
				if (at < 0 || length < 0 || at > input.Length - length)
				{
					return Match<string[]>.Failed(Outcome.NoMatch, "The window " + at.ToString() + ".." + (at + length).ToString() + " is outside the input.", at, null, null);
				}

				var source = input;
				var tokens = Tokenize_DotGram(source, at, at + length);

				var starts  = tokens.Starts;
				var lengths = tokens.Lengths;
				var count   = tokens.Count;

				var text    = new global::System.ReadOnlySpan<char>(tokens.Kinds, 0, count);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Program(text, 0, ref failure, out var recognized, source, starts, lengths);

				if (end < 0)
				{
					failure = new Failure();
					end     = Recognize_Program(text, 0, ref failure, out recognized, source, starts, lengths);
				}

				var began = count > 0 ? starts[0] : at;

				if (end < 0)
				{
					var starved = failure.OutOfInput == failure.Position + 1 || failure.Position >= text.Length;

					var otherwise = starved
						? "Expected more input."
						: "Input does not match 'Program'.";

					var halted = failure.Position < count ? starts[failure.Position] : tokens.Stopped >= 0 ? tokens.Stopped : at + length;

					Recycle_DotGram(tokens);

					return Match<string[]>.Failed(starved ? Outcome.Starved : Outcome.NoMatch, otherwise, halted, failure.Expected, failure.ExpectedMore);
				}

				var whole = recognized;
				var over  = end == 0 ? 0 : starts[end - 1] + lengths[end - 1];

				Recycle_DotGram(tokens);

				return Match<string[]>.Success(whole, began, over - began);
			}

			/// <summary>Reads a <c>Program</c> at <paramref name="at"/>, answering only whether one is there.</summary>
			/// <remarks>
			/// Nothing is said about a refusal: <c>TryParseProgram</c> returning a match says where and why.
			/// On a reading, <paramref name="at"/> moves to the end of what was read; on a
			/// refusal it stays where it was.
			/// </remarks>
			public static bool TryParseProgram(string input, ref int at, int length, out string[] value)
			{
				if (at < 0 || length < 0 || at > input.Length - length)
					throw new global::System.ArgumentOutOfRangeException(nameof(at));

				var source = input;
				var tokens = Tokenize_DotGram(source, at, at + length);

				var starts  = tokens.Starts;
				var lengths = tokens.Lengths;
				var count   = tokens.Count;

				var text    = new global::System.ReadOnlySpan<char>(tokens.Kinds, 0, count);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Program(text, 0, ref failure, out var recognized, source, starts, lengths);

				if (end < 0)
				{
					Recycle_DotGram(tokens);

					value = default!;
					return false;
				}

				var began = count > 0 ? starts[0] : at;

				value = recognized;
				at = end == 0 ? 0 : starts[end - 1] + lengths[end - 1];

				Recycle_DotGram(tokens);

				return true;
			}

			/// <summary>Everything <c>Program</c> is made of, in order (§4.1 case 2).</summary>
			static string[] Construct_Program(string[] item0) =>
				item0 ?? new string[0];

			/// <summary>What <c>Statement</c> builds its value with (docs/syntax.md §7.3).</summary>
			static string Construct_Statement(string name, string value) =>
#line 29 "Lexical.gram"
                                                                                   (name + "=" + value);
#line default

			/// <summary>What <c>Expression</c> builds its value with (docs/syntax.md §7.3).</summary>
			static string Construct_Expression(string left, string right) =>
#line 32 "Lexical.gram"
                                                      (left + "+" + right);
#line default

			/// <summary>What <c>Expression</c> builds its value with (docs/syntax.md §7.3).</summary>
			static string Construct_Expression_1(string left) =>
				(left);

			/// <summary>What <c>Expression</c> builds its value with (docs/syntax.md §7.3).</summary>
			static string Construct_Expression_2(string named) =>
#line 34 "Lexical.gram"
                                                      (named);
#line default

			/// <summary>The readers of the grammar, and what they all read from, in one place: a call between them passes a position and nothing else.</summary>
			private ref struct Reader_DotGram
			{
				readonly global::System.ReadOnlySpan<char> text;
				internal Failure failure;
				const Ways? ways = null;
				readonly ImmediateValues values;
				readonly string parserSource;
				readonly int[] parserStarts;
				readonly int[] parserLengths;
				internal string[] last0;
				internal string last1;

				internal Reader_DotGram(global::System.ReadOnlySpan<char> text, ImmediateValues values, string parserSource, int[] parserStarts, int[] parserLengths)
				{
					this.text    = text;
					this.failure = default;
					this.values = values;
					this.parserSource = parserSource;
					this.parserStarts = parserStarts;
					this.parserLengths = parserLengths;
					this.last0 = default!;
					this.last1 = default!;
				}

				/// <summary><c>Program</c>, read by a method of its own.</summary>
				public int Read_Program(int pos)
				{
					var p = pos;
					var c = '\0';
					var rb_1 = values.Count1;
					while (true)
					{
						if ((uint)p >= (uint)text.Length)
							break;

						c = text[p];

						if (!(c == '\u0001'))
						{
							break;
						}

						var rr0_1 = values.Count1;

						var q0 = Read_Program_Part0(p, rb_1);

						if (q0 < 0 || q0 == p)
						{
							values.Count1 = rr0_1;
							break;
						}

						p = q0;
					}
					var rr1_1 = values.Count1;
					failure.Looking++;
					var q1 = Read_Program_Part1(p, rb_1);
					failure.Looking--;

					values.Count1 = rr1_1;

					if (q1 >= 0)
						return -1;
					last0 = Construct_Program(values.Take1(rb_1)!);
					return p;
				}

				/// <summary>One alternative of <c>Program</c>, read where it stood.</summary>
				public int Read_Program_Part0(int pos, int refs_1)
				{
					var p = pos;
					var q0 = Read_Statement(p);
					if (q0 < 0) return -1;
					p = q0;
					values.Push1(last1);
					return p;
				}

				/// <summary>One alternative of <c>Program</c>, read where it stood.</summary>
				public int Read_Program_Part1(int pos, int refs_1)
				{
					var p = pos;
					var c = '\0';
					if ((uint)p >= (uint)text.Length)
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected1);
						return -1;
					}
					c = text[p];
					p++;
					return p;
				}

				/// <summary><c>Statement</c>, read by a method of its own.</summary>
				public int Read_Statement(int pos)
				{
					var p = pos;
					var c = '\0';
					var a0 = -1;
					var b0 = -1;
					string r1 = default!;
					if ((uint)p >= (uint)text.Length || text[p] != '\u0001')
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected5);
						return -1;
					}
					p += 1;
					a0 = p;
					if ((uint)p >= (uint)text.Length)
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected4);
						return -1;
					}
					c = text[p];
					if (!(((c >= '\u0001' && c <= '\u0002'))))
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected4);
						return -1;
					}
					p++;
					b0 = p;
					if ((uint)p >= (uint)text.Length || text[p] != '\u0004')
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected3);
						return -1;
					}
					p += 1;
					var q0 = Read_Expression(p);
					if (q0 < 0) return -1;
					p = q0;
					r1 = last1;
					if ((uint)p >= (uint)text.Length || text[p] != '\u0005')
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected2);
						return -1;
					}
					p += 1;
					last1 = Construct_Statement((a0 < 0 ? string.Empty : Text_DotGram(parserSource, parserStarts, parserLengths, a0, b0 - a0))!, r1!);
					return p;
				}

				/// <summary><c>Expression</c>, read by a method of its own.</summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				public int Read_Expression(int pos)
				{
					var p = pos;
					var c = '\0';
					var a0 = -1;
					var b0 = -1;
					var a2 = -1;
					var b2 = -1;
					if ((uint)p >= (uint)text.Length)
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected8);
						return -1;
					}
					c = text[p];
					switch (c)
					{
						case '\u0001': case '\u0002':
							{
								a2 = p;
								p++;
								b2 = p;
								last1 = Construct_Expression_2((a2 < 0 ? null : Text_DotGram(parserSource, parserStarts, parserLengths, a2, b2 - a2))!);
								break;
							}
						case '\u0003':
							{
								a0 = p;
								p += 1;
								b0 = p;
								var q0 = Read_Expression_Part0(p, a0, b0);
								if (q0 < 0)
								{
									last1 = Construct_Expression_1((a0 < 0 ? null : Text_DotGram(parserSource, parserStarts, parserLengths, a0, b0 - a0))!);
									q0 = p;
								}
								p = q0;
								break;
							}
						default:
							if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected8);
							return -1;
					}
					return p;
				}

				/// <summary>One alternative of <c>Expression</c>, read where it stood.</summary>
				public int Read_Expression_Part0(int pos, int a0, int b0)
				{
					var p = pos;
					var a1 = -1;
					var b1 = -1;
					if ((uint)p >= (uint)text.Length || text[p] != '\u0006')
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected7);
						return -1;
					}
					p += 1;
					a1 = p;
					if ((uint)p >= (uint)text.Length || text[p] != '\u0003')
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected6);
						return -1;
					}
					p += 1;
					b1 = p;
					last1 = Construct_Expression((a0 < 0 ? null : Text_DotGram(parserSource, parserStarts, parserLengths, a0, b0 - a0))!, (a1 < 0 ? null : Text_DotGram(parserSource, parserStarts, parserLengths, a1, b1 - a1))!);
					return p;
				}

				/// <summary>What <c>Program</c> is read by, whichever stack it is read on.</summary>
				public int Recognize_Program_Whole_Read(int pos)
				{
					var p = pos;
					var rb_1 = values.Count1;
					var q0 = Read_Program(p);
					if (q0 < 0) return -1;
					p = q0;
					if (p != text.Length)
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, null);
						return -1;
					}
					return p;
				}

				/// <summary>What <c>Program</c> is read by, whichever stack it is read on.</summary>
				public int Recognize_Program_Read(int pos)
				{
					var p = pos;
					var rb_1 = values.Count1;
					var q0 = Read_Program(p);
					if (q0 < 0) return -1;
					p = q0;
					return p;
				}

			}

			/// <summary>The whole input as <c>Program</c>, read by methods.</summary>
			static int Recognize_Program_Whole(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out string[] value, string parserSource, int[] parserStarts, int[] parserLengths)
			{
				var values = ImmediateValues.Rent();

				try
				{
					var reader = new Reader_DotGram(text, values, parserSource, parserStarts, parserLengths);

					reader.failure = failure;

					var end = reader.Recognize_Program_Whole_Read(pos);

					failure = reader.failure;

					if (end < 0)
					{
						value = default!;

						return end;
					}

					value = reader.last0;

					return end;
				}
				finally
				{
					ImmediateValues.Return(values);
				}
			}

			/// <summary>The whole input as <c>Program</c>, read by methods.</summary>
			static int Recognize_Program(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out string[] value, string parserSource, int[] parserStarts, int[] parserLengths)
			{
				var values = ImmediateValues.Rent();

				try
				{
					var reader = new Reader_DotGram(text, values, parserSource, parserStarts, parserLengths);

					reader.failure = failure;

					var end = reader.Recognize_Program_Read(pos);

					failure = reader.failure;

					if (end < 0)
					{
						value = default!;

						return end;
					}

					value = reader.last0;

					return end;
				}
				finally
				{
					ImmediateValues.Return(values);
				}
			}



				/// <summary>The strings of one character, made once each rather than per cut.</summary>
				/// <remarks>
				/// Filled where it is missed. Two threads that miss the same character write
				/// the same string, so the race is between two answers that are equal.
				/// </remarks>
				static readonly string[] Letters_DotGram = new string[128];

				/// <summary>The token beginning at a character offset, or -1 where none does.</summary>
				/// <remarks>
				/// A position is a character offset to a caller holding the text and a token to the
				/// machine reading it, and this is where the two meet: a reading asked to begin
				/// somewhere has to begin at a token. Binary, because the starts are ordered and a
				/// caller with several places to read from would otherwise walk the whole array for
				/// each of them.
				/// </remarks>
				static int TokenAt_DotGram(int[] starts, int count, int at)
				{
					var low  = 0;
					var high = count - 1;

					while (low <= high)
					{
						var middle = low + ((high - low) >> 1);
						var began  = starts[middle];

						if (began == at)
							return middle;

						if (began < at)
							low = middle + 1;
						else
							high = middle - 1;
					}

					// Where none begins there, the first one after it: `low` is where the search
					// ended, and the count where nothing is left to read.
					return low < count ? low : -1;
				}

				/// <summary>The text a run of tokens came from.</summary>
				static string Text_DotGram(string source, int[] starts, int[] lengths, int from, int length)
				{
					if (length <= 0)
						return string.Empty;

					var began = starts[from];
					var ended = starts[from + length - 1] + lengths[from + length - 1];

					if (ended - began == 1 && source[began] < 128)
					{
						var one = source[began];

						return Letters_DotGram[one] ??= source.Substring(began, 1);
					}

					return source.Substring(began, ended - began);
				}

			static string[]? Recognize_DotGram_Expected0_Built;
			static string[] Recognize_DotGram_Expected0 => Recognize_DotGram_Expected0_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected0_Built, new string[] { "?![^ ]" }, null) ?? Recognize_DotGram_Expected0_Built!;

			static string[]? Recognize_DotGram_Expected1_Built;
			static string[] Recognize_DotGram_Expected1 => Recognize_DotGram_Expected1_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected1_Built, new string[] { "Name", "Number", "'='", "';'", "'+'" }, null) ?? Recognize_DotGram_Expected1_Built!;

			static string[]? Recognize_DotGram_Expected2_Built;
			static string[] Recognize_DotGram_Expected2 => Recognize_DotGram_Expected2_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected2_Built, new string[] { "';'" }, null) ?? Recognize_DotGram_Expected2_Built!;

			static string[]? Recognize_DotGram_Expected3_Built;
			static string[] Recognize_DotGram_Expected3 => Recognize_DotGram_Expected3_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected3_Built, new string[] { "'='" }, null) ?? Recognize_DotGram_Expected3_Built!;

			static string[]? Recognize_DotGram_Expected4_Built;
			static string[] Recognize_DotGram_Expected4 => Recognize_DotGram_Expected4_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected4_Built, new string[] { "Name" }, null) ?? Recognize_DotGram_Expected4_Built!;

			static string[]? Recognize_DotGram_Expected5_Built;
			static string[] Recognize_DotGram_Expected5 => Recognize_DotGram_Expected5_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected5_Built, new string[] { "\"let\"" }, null) ?? Recognize_DotGram_Expected5_Built!;

			static string[]? Recognize_DotGram_Expected6_Built;
			static string[] Recognize_DotGram_Expected6 => Recognize_DotGram_Expected6_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected6_Built, new string[] { "Number" }, null) ?? Recognize_DotGram_Expected6_Built!;

			static string[]? Recognize_DotGram_Expected7_Built;
			static string[] Recognize_DotGram_Expected7 => Recognize_DotGram_Expected7_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected7_Built, new string[] { "'+'" }, null) ?? Recognize_DotGram_Expected7_Built!;

			static string[]? Recognize_DotGram_Expected8_Built;
			static string[] Recognize_DotGram_Expected8 => Recognize_DotGram_Expected8_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected8_Built, new string[] { "Name", "Number" }, null) ?? Recognize_DotGram_Expected8_Built!;

			/// <summary>What kind of answer a publication gave (docs/syntax.md §7.5).</summary>
			public enum Outcome
			{
				/// <summary>The input matched, and <c>Value</c> holds what it built.</summary>
				Success,

				/// <summary>The input was there and did not fit.</summary>
				NoMatch,

				/// <summary>The input ran out where more was needed.</summary>
				Starved,
			}

			/// <summary>What a publication answers with: the value, or why there is none.</summary>
			public readonly struct Match<T>
			{
				/// <summary>What would have fit at the furthest position, or null.</summary>
				private readonly string[]? _expected;

				/// <summary>The arrays that tied with it, or null where none did.</summary>
				private readonly global::System.Collections.Generic.List<string[]>? _tied;

				/// <summary>
				/// What <c>Error</c> says when nothing named what would have fit. A literal
				/// chosen where the match failed, so naming it costs nothing.
				/// </summary>
				private readonly string? _otherwise;

				private Match(
					Outcome outcome, T value, long position, int length,
					string[]? expected, global::System.Collections.Generic.List<string[]>? tied,
					string? otherwise)
				{
					Outcome    = outcome;
					Value      = value;
					Position   = position;
					Length     = length;
					_expected  = expected;
					_tied      = tied;
					_otherwise = otherwise;
				}

				/// <summary>Whether there is a value.</summary>
				public bool IsSuccess { get { return Outcome == Outcome.Success; } }

				/// <summary>
				/// Which kind of answer this is: the value, input that did not fit, or input
				/// that ran out (docs/syntax.md §7.5).
				/// </summary>
				public Outcome Outcome { get; }

				/// <summary>What was recognized. Meaningless unless <c>IsSuccess</c>.</summary>
				public T Value { get; }

				/// <summary>
				/// Why nothing was recognized, or null.
				/// </summary>
				/// <remarks>
				/// Built where it is asked for rather than where the match failed, and built
				/// again on each ask. A caller that only wants to know whether the input
				/// matched pays for none of it, which is most callers and every one in a loop
				/// over input that is expected to fail sometimes.
				/// </remarks>
				public string? Error
				{
					get
					{
						if (IsSuccess)
							return null;

						var expected = _expected;

						if (_tied != null)
						{
							var total = expected == null ? 0 : expected.Length;

							foreach (var each in _tied)
								total += each.Length;

							var merged = new string[total];
							var at     = 0;

							if (expected != null)
							{
								expected.CopyTo(merged, 0);
								at = expected.Length;
							}

							foreach (var each in _tied)
							{
								each.CopyTo(merged, at);
								at += each.Length;
							}

							expected = merged;
						}

						if (expected == null || expected.Length == 0)
							return _otherwise;

						// A rule that says what its own refusal says (docs/syntax.md §4's `on
						// fail`) writes it as one item, marked with a character no grammar can
						// write. Where one stands here it is the whole answer: the author took
						// the wording, and what else could have stood here is not it.
						for (var i = 0; i < expected.Length; i++)
							if (expected[i].Length > 0 && expected[i][0] == '\u0000')
								return expected[i].Substring(1);

						// Two sites may ask for the same thing — a literal written in two rules,
						// or the `<` that opens a type argument list in more than one — and a
						// reader is owed one mention of it rather than one per site. Copied
						// rather than compacted where it stands: without a tie this array is the
						// one the generator declared `static readonly`, and rewriting that would
						// change what every later failure says.
						if (expected.Length > 1)
						{
							var unique = new string[expected.Length];
							var kept   = 0;

							for (var i = 0; i < expected.Length; i++)
							{
								var seen = false;

								for (var j = 0; j < kept; j++)
									if (string.Equals(
											unique[j], expected[i], global::System.StringComparison.Ordinal))
									{
										seen = true;
										break;
									}

								if (!seen)
									unique[kept++] = expected[i];
							}

							if (kept < expected.Length)
							{
								expected = new string[kept];
								global::System.Array.Copy(unique, expected, kept);
							}
						}

						if (expected.Length == 1)
							return "Expected " + expected[0] + ".";

						return "Expected " +
							string.Join(", ", expected, 0, expected.Length - 1) +
							" or " + expected[expected.Length - 1] + ".";
					}
				}

				/// <summary>
				/// Where the match began, or how far the input could be followed before it
				/// failed. An offset into the whole input, so a <c>long</c>: an input may be a
				/// file larger than an <c>int</c> can index (docs/syntax.md §6.3).
				/// </summary>
				public long Position { get; }

				/// <summary>
				/// How much was matched, in input items, and zero when nothing was. An extent
				/// into a buffer rather than an offset into the input, so an <c>int</c>.
				/// </summary>
				public int Length { get; }

				internal static Match<T> Success(T value, long position, int length)
				{
					return new Match<T>(Outcome.Success, value, position, length, null, null, null);
				}

				internal static Match<T> Failed(
					Outcome outcome, string otherwise, long position, string[]? expected,
					global::System.Collections.Generic.List<string[]>? tied)
				{
					return new Match<T>(outcome, default!, position, 0, expected, tied, otherwise);
				}
			}

			/// <summary>Where a match got before it gave up, and why.</summary>
			struct Failure
			{
				/// <summary>
				/// The furthest position the input was followed to. Zero on a match that
				/// succeeded without ever backtracking, and meaningless unless one failed.
				/// </summary>
				public int Position;

				/// <summary>
				/// Where something wanted more input than remained, one past the position, or
				/// zero — what <c>Outcome</c> tells "the input ran out" from "the input did
				/// not fit" by (§7.5).
				/// </summary>
				/// <remarks>
				/// <para>
				/// A position rather than a flag, and written straight here rather than
				/// threaded through <c>Fail:</c> like <c>Expected</c>: what the boundary asks
				/// is whether the <em>furthest</em> failure ran out, so a room check that
				/// failed somewhere the parse later got past answers by not matching
				/// <c>Position</c>. Nothing has to be adopted, nothing has to be cleared, and
				/// the automaton's own unwinding is untouched — which is why this costs a
				/// store on a failure path and nothing anywhere else.
				/// </para>
				/// <para>
				/// One past, because a zeroed struct has to mean "nowhere" and zero is a
				/// position. Only a test wanting more than one character writes it: one
				/// wanting a single character can only fail for want of room at the very end
				/// of the input, which the boundary reads off <c>Position</c> itself.
				/// </para>
				/// </remarks>
				// Nothing assigns this here: every test in this grammar wants one character.
				// A field nothing assigns is CS0649 in somebody else's build, which for one
				// that treats warnings as errors is a broken compilation of a file they did
				// not write.
				#pragma warning disable 0649
				public int OutOfInput;
				#pragma warning restore 0649

				/// <summary>
				/// What would have fit at the furthest position, or null. Meaningless unless
				/// the match failed. A reference into one of the generator's own arrays, not
				/// a copy of it.
				/// </summary>
				public string[]? Expected;

				/// <summary>
				/// A second array and beyond, where more than one terminal tied for the
				/// furthest position. Null until an actual tie needs one, and emptied rather
				/// than dropped when the furthest position moves on: a parse that ties once
				/// tends to tie again, and a list per tie was an allocation per operand.
				/// </summary>
				public global::System.Collections.Generic.List<string[]>? ExpectedMore;

				/// <summary>
				/// How many lookaheads the reading is inside. A refusal there is not the parse's —
				/// the look is read and given back whatever it says — so a reader records none
				/// while this is above zero, as the engine records none inside its own lookahead.
				/// </summary>
				public int Looking;

				/// <summary>
				/// Whether nothing reads what this failure would record, so nothing is recorded: a
				/// `find` trying each start, the lexer measuring or valuing a token again.
				/// </summary>
				public bool Quiet;
			}

			/// <summary>Which row of Scan_Running each state runs over.</summary>
			static readonly byte[] Scan_Runs =
			{
					0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
			};

			/// <summary>What each run carries on with, a row of 256 bytes each.</summary>
			static readonly byte[] Scan_Running =
			{
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
					1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
					1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
					0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
			};

			/// <summary>The kind each state accepts, one-based; 0 where it accepts none.</summary>
			static readonly int[] Scan_Accepts =
			{
					0, 6, 3, 5, 4, 2, 2, 3, 2, 2, 1,
			};

			/// <summary>Where each state goes, for the characters its row holds.</summary>
			static readonly short[] Scan_Cells =
			{
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1,
					-1, -1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, -1, 3, -1, 4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					5, -1, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 7, 7, 7, 7, 7, 7, 7,
					7, 7, 7, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, 8, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
					8, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, 8, -1, 8, 8, 8, 8, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
					8, 8, 8, 8, 8, 8, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
					-1, -1, -1, -1, -1, -1, -1, -1, -1, 8, -1, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
					8, 8, 8, 10, 8, 8, 8, 8, 8, 8, -1, -1, -1, -1, -1,
			};

			/// <summary>Each state's row: where it begins in the cells, how wide, and from
			/// which character.</summary>
			static readonly long[] Scan_States =
			{
					0, 128, 256, 128, 128, 384, 512, 256, 384, 640, 384,
			};


			/// <summary>
			/// One token: its kind by way of <paramref name="kind"/>, and where it ends.
			/// </summary>
			/// <remarks>
			/// Longest match. The machine is run until it can go no further and the last state
			/// that accepted is the answer, which is why a keyword beats the identifier it starts
			/// and <c>&gt;=</c> beats <c>&gt;</c> without either being written down as a rule.
			/// </remarks>
			/// <returns>Where the token ends, or <paramref name="pos"/> where none begins here.</returns>
			public static int Scan(global::System.ReadOnlySpan<char> text, int pos, out int kind)
			{
				var state = 0;
				var end   = pos;
				var found = 0;
				var p     = pos;

				while (p < text.Length)
				{
					var c    = text[p];
					var row  = Scan_States[state];
					var at   = c - (int)(row >> 32);
					int next;

					if ((uint)at < 128u)
						next = Scan_Cells[(int)row + at];
					else
					{
						next =
							Scan_Part0(state, c);
					}

					if (next < 0)
						goto Done;

					var again = next == state;

					state = next;
					p++;

					// A run of one class, which the row above already decided.
					if (again)
					{
						var over = Scan_Runs[state] << 8;

						while (p < text.Length)
						{
							var ahead = text[p];

							if (ahead > 255 || Scan_Running[over + ahead] == 0)
								break;

							p++;
						}
					}

					var accepts = Scan_Accepts[state];

					if (accepts != 0)
						(end, found) = (p, accepts);
				}

				Done:
				kind = found;

				return end;
			}

			/// <summary>Where states 0 to 10 go, or -1 for nowhere.</summary>
			static int Scan_Part0(int state, char c)
			{
				switch (state)
				{
					default: return -1;
				}
			}

			static string[]? Recognize_DotGram_Seam_Expected0_Built;
			static string[] Recognize_DotGram_Seam_Expected0 => Recognize_DotGram_Seam_Expected0_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Seam_Expected0_Built, new string[] { "['\\t'..'\\n' | '\\r' | ' ']" }, null) ?? Recognize_DotGram_Seam_Expected0_Built!;

			static string[]? Recognize_DotGram_Seam_Expected1_Built;
			static string[] Recognize_DotGram_Seam_Expected1 => Recognize_DotGram_Seam_Expected1_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Seam_Expected1_Built, new string[] { "\"--\"" }, null) ?? Recognize_DotGram_Seam_Expected1_Built!;

			static string[]? Recognize_DotGram_Seam_Expected2_Built;
			static string[] Recognize_DotGram_Seam_Expected2 => Recognize_DotGram_Seam_Expected2_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Seam_Expected2_Built, new string[] { "['\\t'..'\\n' | '\\r' | ' ' | '-']" }, null) ?? Recognize_DotGram_Seam_Expected2_Built!;

			static readonly byte[] Recognize_DotGram_Seam_Class0 = { 0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 };

			static readonly byte[] Recognize_DotGram_Seam_Class1 = { 0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 };

			/// <summary><c>trivia</c>, recognized with nothing written down.</summary>
			static int Scan_trivia_Seam(global::System.ReadOnlySpan<char> text, int pos)
			{
				var p = pos;
				var c = '\0';

				L0_turn:
				if ((uint)p >= (uint)text.Length) goto L1_done;
				c = text[p];
				if (!(c <= 255 && Recognize_DotGram_Seam_Class1[c] != 0)) goto L1_done;
				if (!(c <= 255 && Recognize_DotGram_Seam_Class0[c] != 0)) goto L3_or;
				p++;
				goto L0_turn;
				L3_or: ;
				if (text.Length - p < 2 || !global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 2), global::System.MemoryExtensions.AsSpan("--")))
					goto L1_done;
				p += 2;
				var found6 = global::System.MemoryExtensions.IndexOf(text.Slice(p), '\n');
				p = found6 < 0 ? text.Length : p + found6;
				goto L0_turn;
				L1_done:
				;

				return p;
			}

			/// <summary>What a tokenized parse reads: the kinds, and where each one was.</summary>
			/// <remarks>
			/// Three arrays and a count, kept for the next parse on this thread the way the
			/// parser itself is. Allocated afresh they were the whole of what a split grammar
			/// cost over a character one on a short input — three allocations sized to the
			/// input, against a parse that reads a dozen tokens.
			/// </remarks>
			/// <remarks>
			/// Sized by the tokens there turn out to be rather than by the characters there
			/// are. A token is several characters, so the input's length is a bound four or
			/// more times what a document needs: three and three-quarter megabytes of SQL
			/// asked for thirty-eight of arrays and used nine. The guess starts at a quarter
			/// of the input and doubles, which for ordinary text never grows at all.
			/// </remarks>
			sealed class Tokens_DotGram
			{
				internal char[] Kinds   = new char[0];
				internal int[]  Starts  = new int[0];
				internal int[]  Lengths = new int[0];
				internal int    Count;
				internal int    Stopped;

				/// <summary>What the last parse asked of this buffer: its room, in its own unit.</summary>
				/// <remarks>
				/// The arrays are sized from a GUESS at the token count, so their length is not a
				/// count of anything and cannot be held against Count: a document of long tokens
				/// guesses high and would read as idle on every parse of it, steady or not. What
				/// the guess WAS is the honest other side, and Room is where it is known.
				/// </remarks>
				internal int    Asked;

				internal void Room(int length)
				{
					Asked = length;

					if (Kinds.Length >= length)
						return;

					Kinds   = new char[length];
					Starts  = new int[length];
					Lengths = new int[length];
				}

				/// <summary>Room for one more, keeping what is already written.</summary>
				internal void Grow(int count)
				{
					if (Kinds.Length > count)
						return;

					var size = Kinds.Length < 16 ? 16 : Kinds.Length * 2;

					global::System.Array.Resize(ref Kinds,   size);
					global::System.Array.Resize(ref Starts,  size);
					global::System.Array.Resize(ref Lengths, size);
				}
			}

			/// <summary>The last set this thread used — one slot, taken out while in use.</summary>
			/// <remarks>
			/// Taken out rather than shared, so a parse reached from inside another — a guard
			/// that parses, a value that does — gets its own. Ordinary buffers are reused;
			/// stores exceeding the retained-capacity budget are left for collection.
			/// </remarks>
			[global::System.ThreadStatic]
			static Tokens_DotGram? _spareTokens;

			/// <summary>Spares below the one slot, for parses reached from inside others; made the first time one is.</summary>
			[global::System.ThreadStatic]
			static Tokens_DotGram?[]? _deeperTokens;

			[global::System.ThreadStatic]
			static int _deeperTokenCount;

			/// <summary>A buffer past the bound, kept while this thread keeps wanting it.</summary>
			[global::System.ThreadStatic]
			static Tokens_DotGram? _largeTokens;

			/// <summary>Parses in a row that did not use the room; at eight it is let go of.</summary>
			[global::System.ThreadStatic]
			static int _largeTokensIdle;

			/// <summary>And where it goes then: reachable until the memory is wanted elsewhere.</summary>
			[global::System.ThreadStatic]
			static global::System.WeakReference<Tokens_DotGram>? _largeTokensLetGo;

			/// <summary>Parses in a row that left most of the ordinary spare's room unused.</summary>
			[global::System.ThreadStatic]
			static int _spareTokensIdle;

			/// <summary>And where the ordinary spare goes when it has been too big for too long.</summary>
			[global::System.ThreadStatic]
			static global::System.WeakReference<Tokens_DotGram>? _spareTokensLetGo;

			static Tokens_DotGram Rented_DotGram()
			{
				var spare = _spareTokens;

				if (spare != null)
					_spareTokens = null;
				else if (_deeperTokenCount > 0)
				{
					spare = _deeperTokens![--_deeperTokenCount]!;
					_deeperTokens![_deeperTokenCount] = null;
				}
				else if (_largeTokens != null)
				{
					spare = _largeTokens;
					_largeTokens = null;
				}
				else if (_largeTokensLetGo != null && _largeTokensLetGo.TryGetTarget(out var letGo))
				{
					spare = letGo;
					_largeTokensLetGo.SetTarget(null!);
				}
				else if (_spareTokensLetGo != null && _spareTokensLetGo.TryGetTarget(out var letGoSpare))
				{
					spare = letGoSpare;
					_spareTokensLetGo.SetTarget(null!);
				}
				else
					return new Tokens_DotGram();

				return spare;
			}

			static void Recycle_DotGram(Tokens_DotGram tokens)
			{
				// Past the bound the buffer is not thrown away - that was a cliff and not a
				// bound: a document one token over rebuilt it on every parse. It goes to a slot
				// of its own, held while the work keeps wanting it and let go of afterwards.
				// Its three arrays hold numbers, so what the slot pins is numbers.
				if ((long)tokens.Kinds.Length + tokens.Starts.Length + tokens.Lengths.Length > 1048576)
				{
					if (_largeTokens != null && !ReferenceEquals(_largeTokens, tokens))
						(_largeTokensLetGo ??= new global::System.WeakReference<Tokens_DotGram>(_largeTokens)).SetTarget(_largeTokens);

					// The same question the ordinary slot asks below: is the room far larger than
					// the room this parse asked for. The bound decides which slot holds the buffer.
					if ((long)tokens.Kinds.Length <= 4L * tokens.Asked)
						_largeTokensIdle = 0;
					else if (++_largeTokensIdle >= 8)
					{
						(_largeTokensLetGo ??= new global::System.WeakReference<Tokens_DotGram>(tokens)).SetTarget(tokens);
						_largeTokens = null;
						_largeTokensIdle = 0;

						return;
					}

					_largeTokens = tokens;

					return;
				}

				// The ordinary slot lets go by the rule the parked one uses, and against the same
				// quantity: the room this parse asked for, which is what the arrays were sized
				// from. Held against Count instead, a document of long tokens reads as idle on
				// every parse of it, because the length of these arrays is a guess and not a count.
				if ((long)tokens.Kinds.Length <= 4L * tokens.Asked)
					_spareTokensIdle = 0;
				else if (++_spareTokensIdle >= 8)
				{
					(_spareTokensLetGo ??= new global::System.WeakReference<Tokens_DotGram>(tokens)).SetTarget(tokens);
					_spareTokensIdle = 0;

					return;
				}

				if (_spareTokens == null)
					_spareTokens = tokens;
				else if (_deeperTokenCount < 3)
					(_deeperTokens ??= new Tokens_DotGram?[3])[_deeperTokenCount++] = tokens;
			}

			/// <summary>The input as kinds, with where each one was.</summary>
			/// <remarks>
			/// The seam first and then a terminal, which is §4.5 read from the other side:
			/// trivia stands between operands, so between tokens is exactly where it stands.
			/// A character that begins no terminal stops the scan and is reported as where
			/// the input stopped being this language.
			/// </remarks>

			/// <summary>The inputs whose kinds this thread still holds, and the kinds it holds for them.</summary>
			/// <remarks>
			/// A reading that begins where it is told cuts the whole input into kinds, and a host
			/// reading one value after another from one text would cut it again for every value:
			/// the text once per value is the square of the text. So the last cutting is kept and
			/// handed back where the next reading comes with the same string.
			/// </remarks>
			/// <remarks>
			/// Two of them, and not one. A host alternating between two documents would otherwise
			/// hold neither, and a parse reached from inside a factory of another — reading its own
			/// text — would push out the reading that called it and give the square back.
			/// </remarks>
			/// <remarks>
			/// The input is held weakly and the kinds strongly: the kinds are as long as the text,
			/// and a thread-static holding a document nobody else has is the leak this is not.
			/// Where the input is gone, so are its kinds, at the next reading that looks.
			/// A cutting that leaves a slot is let go of and never pooled: the reading it was
			/// cut for may still be holding it, and a pooled set is written over by the next.
			/// A string only: what a caller may write into between two readings — an array of
			/// bytes, a memory — would make a kept cutting a lie, so the byte forms keep none.
			/// </remarks>
			[global::System.ThreadStatic]
			static global::System.WeakReference<string>[]? _cutInputs;

			[global::System.ThreadStatic]
			static Tokens_DotGram?[]? _cutTokens;

			[global::System.ThreadStatic]
			static int _cutNext;

			/// <summary>The whole input as kinds, cut now or kept from the reading before this one.</summary>
			static Tokens_DotGram Tokenized_DotGram(string input)
			{
				var inputs = _cutInputs;
				var kept   = _cutTokens;

				if (inputs != null && kept != null)
				{
					for (var slot = 0; slot < inputs.Length; slot++)
					{
						var held = inputs[slot];

						if (held == null || kept[slot] == null)
							continue;

						if (!held.TryGetTarget(out var was))
						{
							// The text is gone and its kinds go with it — dropped and not pooled: a
							// reading that took these kinds may still be reading them.
							inputs[slot] = null!;
							kept[slot]   = null;

							continue;
						}

						if (ReferenceEquals(was, input))
							return kept[slot]!;
					}
				}

				var tokens = Tokenize_DotGram(input, 0, input.Length);

				inputs ??= _cutInputs = new global::System.WeakReference<string>[2];
				kept   ??= _cutTokens = new Tokens_DotGram?[2];

				var next = _cutNext;

				_cutNext = next + 1 == inputs.Length ? 0 : next + 1;

				// What was in the slot is let go of and not pooled. A reading that took it is
				// still holding it — this very cutting may be one its own factory asked for —
				// and a pooled set is written over by the next cutting, under the reading.
				inputs[next] = new global::System.WeakReference<string>(input);
				kept[next]   = tokens;

				return tokens;
			}

			static Tokens_DotGram Tokenize_DotGram(string input) => Tokenize_DotGram(input, 0, input.Length);

			/// <summary>The kinds between two offsets of the input, with where each one was.</summary>
			/// <remarks>
			/// What a reading over a window of the text reads. The characters past the window are
			/// not there for it — a token that would run over the edge ends at it — and the
			/// positions are still offsets into the whole input.
			/// </remarks>
			static Tokens_DotGram Tokenize_DotGram(string input, int from, int to)
			{
				var tokens = Rented_DotGram();

				tokens.Room((to - from) / 4 + 16);

				var text    = global::System.MemoryExtensions.AsSpan(input, 0, to);
				var kinds   = tokens.Kinds;
				var starts  = tokens.Starts;
				var lengths = tokens.Lengths;

				var count = 0;
				var p     = from;

				while (true)
				{
					var skipped = Scan_trivia_Seam(text, p);

					if (skipped > p)
						p = skipped;

					if (p >= text.Length)
						break;

					var end = Scan(text, p, out var kind);

					if (kind == 0 || end <= p)
					{
						tokens.Count   = count;
						tokens.Stopped = p;

						return tokens;
					}

					if (count == kinds.Length)
					{
						tokens.Grow(count);

						kinds   = tokens.Kinds;
						starts  = tokens.Starts;
						lengths = tokens.Lengths;
					}

					kinds  [count] = (char)kind;
					starts [count] = p;
					lengths[count] = end - p;
					count++;

					p = end;
				}

				tokens.Count   = count;
				tokens.Stopped = -1;

				return tokens;
			}

			/// <summary>The ways back still open in a direct parse (Machine.Direct.cs).</summary>
			/// <remarks>
			/// Two integers per way: the alternative in force, and the last one there is. A
			/// way whose two are equal is spent — it stays on the tape so that a replay reads
			/// the same decisions in the same places, and is never taken again.
			/// </remarks>
			sealed class Ways
			{
				internal int[] Items = new int[32];

				/// <summary>How many ways are on the tape.</summary>
				internal int Count;

				/// <summary>The next way a replay reads; equal to <see cref="Count"/> when nothing is being replayed.</summary>
				internal int Cursor;

				/// <summary>
				/// What was recognized, for building values with once the parse has accepted: one
				/// record per completed valued rule, written after its children, each starting
				/// with its own length so that a walk from the front steps from record to record.
				/// </summary>
				internal int[] Log = new int[64];

				/// <summary>How much of the log is written.</summary>
				internal int LogCount;

				/// <summary>How many records the log holds: the number the next one is given.</summary>
				/// <remarks>
				/// A record is named by its number and not by where it was written, so that the
				/// tables the walk builds into are as long as there are records and not as long as
				/// the log. On a real grammar that is four or five times shorter, which is the
				/// difference between a table that fits in the first cache and one that does not.
				/// </remarks>
				internal int Records;

				/// <summary>Which record finished most recently: the number a caller captures.</summary>
				internal int Last = -1;

				/// <summary>
				/// How much of the log the values built for a guard still stand for: a record
				/// below this that was built need not be built again, and one above it was
				/// written since — the log was put back past it and has grown again.
				/// </summary>
				internal int Built;

				/// <summary>
				/// How far up the log every record is already built, so that a guard asking again
				/// need not read the flags at all.
				/// </summary>
				/// <remarks>
				/// Stronger than <see cref="Built"/>, and not the same question. <c>Built</c> says the
				/// flags below it are not stale — a record below it may still be false. This says every
				/// record below it is true, which is what lets the scan be skipped rather than shortened.
				/// <para>
				/// It never runs ahead of <see cref="Built"/>, which is what keeps the clearing honest:
				/// the flags are cleared from <c>Built</c> upwards, so a watermark above it would claim
				/// records whose flags had just been wiped. It is raised only where <c>Built</c> is raised
				/// with it and lowered wherever <c>Built</c> is lowered, so the two move together.
				/// </para>
				/// </remarks>
				internal int AllBuilt;

				/// <summary>
				/// Captures collected while a rule runs and gathered into its record at the end:
				/// three integers each — the slot, and either a record and -1, or a start and end.
				/// </summary>
				internal int[] Refs = new int[48];

				/// <summary>How much of the side stack is in use.</summary>
				internal int RefsCount;

				/// <summary>Where the record being written begins, and which record it is.</summary>
				/// <remarks>
				/// Once it is closed, where the last one begins: a guard asking for the record it just
				/// captured is handed its place without a walk of the log to find it.
				/// </remarks>
				internal int Opened;
				int _number;

				[global::System.ThreadStatic]
				static Ways? _spare;

				/// <summary>Spares below the one slot, for parses reached from inside others; made the first time one is.</summary>
				[global::System.ThreadStatic]
				static Ways?[]? _deeper;

				[global::System.ThreadStatic]
				static int _deeperCount;

				/// <summary>A tape too large for the ordinary slot, kept while the work still wants it.</summary>
				[global::System.ThreadStatic]
				static Ways? _large;

				/// <summary>Parses in a row that did not use the room; at <c>LargeIdle</c> it is let go of.</summary>
				[global::System.ThreadStatic]
				static int _largeIdle;

				/// <summary>And where it goes then: reachable while nothing else wants the memory.</summary>
				[global::System.ThreadStatic]
				static global::System.WeakReference<Ways>? _largeLetGo;

				/// <summary>Parses in a row that left most of the ordinary spare's room unused.</summary>
				[global::System.ThreadStatic]
				static int _spareIdle;

				/// <summary>And where the ordinary spare goes when it has been too big for too long.</summary>
				[global::System.ThreadStatic]
				static global::System.WeakReference<Ways>? _spareLetGo;

				/// <summary>
				/// Eight is a claim, not a taste: if eight parses in a row have not wanted the large
				/// tape, this thread's work has changed and the next parse is unlikely to want it
				/// either. Holding it through a few small parses costs the memory we were holding a
				/// moment ago anyway; holding it through a hundred would be hoarding.
				/// </summary>
				const int LargeIdle = 8;

				/// <summary>The same count for the ordinary slot, read the same way.</summary>
				const int SpareIdle = 8;

				internal static Ways Rent()
				{
					var spare = _spare;

					if (spare != null)
						_spare = null;
					else if (_deeperCount > 0)
					{
						spare = _deeper![--_deeperCount]!;
						_deeper![_deeperCount] = null;
					}
					else if (_large != null)
					{
						spare = _large;
						_large = null;
					}
					else if (_largeLetGo != null && _largeLetGo.TryGetTarget(out var letGo))
					{
						spare = letGo;
						_largeLetGo.SetTarget(null!);
					}
					else if (_spareLetGo != null && _spareLetGo.TryGetTarget(out var letGoSpare))
					{
						spare = letGoSpare;
						_spareLetGo.SetTarget(null!);
					}
					else
						return new Ways();
					spare.Count = 0;
					spare.Cursor = 0;
					spare.LogCount  = 0;
					spare.Records   = 0;
					spare.RefsCount = 0;
					spare.Last      = -1;
					spare.Built     = 0;
					spare.AllBuilt  = 0;

					return spare;
				}

				internal static void Return(Ways ways)
				{
					// Bound retained capacity, including an earlier parse's high-water size. Past it
					// the tape is not thrown away — that was a cliff rather than a bound: one entry
					// over and the next parse of a document that size grew everything again from
					// nothing, which cost twenty times the memory of a document a third smaller.
					// It goes to a slot of its own instead, held while the work keeps wanting it
					// (Return, LargeIdle) and let go of by the collector afterwards. Handing it to
					// ArrayPool<T>.Shared instead was considered and is not the same thing: that
					// pool's largest kept array is 2^20 elements, the very number this bound is
					// written in, so it would decline exactly these arrays and "pool it" would mean
					// "drop it" in more words.
					if ((long)ways.Items.Length + ways.Log.Length + ways.Refs.Length > 1048576)
					{
						if (_large != null && !ReferenceEquals(_large, ways))
							(_largeLetGo ??= new global::System.WeakReference<Ways>(_large)).SetTarget(_large);

						// The same question the ordinary slot asks below: is the room far larger than the
						// use. The bound decides which slot holds the tape, not whether to keep it.
						if (!((long)ways.Items.Length + ways.Log.Length + ways.Refs.Length
							> 4L * (ways.Count * 2L + ways.LogCount + ways.RefsCount)))
							_largeIdle = 0;
						else if (++_largeIdle >= LargeIdle)
						{
							(_largeLetGo ??= new global::System.WeakReference<Ways>(ways)).SetTarget(ways);
							_large = null;
							_largeIdle = 0;

							return;
						}

						_large = ways;

						return;
					}

					// The ordinary slot lets go by the rule the parked one uses, counted where a parse
					// ENDS and against what it used. Room and use are the two sums already written above:
					// every array here is indexed by the same thing, so the bound's capacities and the
					// release's counts are the same quantity twice. Four times and not twice because a
					// table grows to at least double: one doubling is the slack a steady workload leaves,
					// and two is a workload that has shrunk.
					if (!((long)ways.Items.Length + ways.Log.Length + ways.Refs.Length
						> 4L * (ways.Count * 2L + ways.LogCount + ways.RefsCount)))
						_spareIdle = 0;
					else if (++_spareIdle >= SpareIdle)
					{
						(_spareLetGo ??= new global::System.WeakReference<Ways>(ways)).SetTarget(ways);
						_spareIdle = 0;

						return;
					}

					if (_spare == null)
						_spare = ways;
					else if (_deeperCount < 3)
						(_deeper ??= new Ways?[3])[_deeperCount++] = ways;
				}

				/// <summary>Opens a way at the end of the tape, in force at its first alternative.</summary>
				internal int Open(int last) => Open(0, last);

				/// <summary>Opens a way at the end of the tape, in force at <paramref name="at"/>.</summary>
				internal int Open(int at, int last)
				{
					if (Count * 2 + 2 > Items.Length)
						global::System.Array.Resize(ref Items, Items.Length * 2);

					Items[Count * 2]     = at;
					Items[Count * 2 + 1] = last;
					Count++;
					Cursor = Count;

					return Count - 1;
				}

				/// <summary>
				/// Takes the latest way decided since <paramref name="segment"/> that still has an
				/// alternative left, drops everything decided after it, and sets the replay to
				/// begin at the segment. False when none is left, and then nothing moves.
				/// </summary>
				/// <remarks>
				/// Only what stands before the cursor is the construct's own. During a replay the
				/// tape past the cursor is the future — decisions of what comes after, waiting to
				/// be read again — and a construct that fails on the way there, exactly as it did
				/// the first time, must leave that future alone.
				/// </remarks>
				internal bool Retry(int segment)
				{
					for (var way = Cursor - 1; way >= segment; way--)
					{
						if (Items[way * 2] < Items[way * 2 + 1])
						{
							Items[way * 2]++;
							Count  = way + 1;
							Cursor = segment;

							return true;
						}
					}

					return false;
				}

				/// <summary>
				/// Moves a way on to its next alternative once the one in force is spent, and
				/// drops what that alternative decided: the next one starts from nothing.
				/// </summary>
				internal void Next(int way, int value)
				{
					Items[way * 2] = value;
					Count  = way + 1;
					Cursor = way + 1;
				}

				/// <summary>
				/// <see cref="Next(int, int)"/>, and the way now reaches <paramref name="last"/>:
				/// as far as the alternative it moved to could be mended from.
				/// </summary>
				internal void Next(int way, int value, int last)
				{
					Items[way * 2]     = value;
					Items[way * 2 + 1] = last;
					Count  = way + 1;
					Cursor = way + 1;
				}

				/// <summary>Spends every way decided since the segment, keeping its decision.</summary>
				internal void Seal(int segment)
				{
					for (var way = segment; way < Cursor; way++)
						Items[way * 2 + 1] = Items[way * 2];
				}

				/// <summary>
				/// Opens a record: its length is written when it ends.
				/// </summary>
				/// <remarks>
				/// One number says which rule wrote it and which of that rule's alternatives,
				/// because the walk at the end wants both together and asking twice cost a
				/// switch inside a switch — two jump tables where a record needs one.
				/// </remarks>
				/// <summary>
				/// Opens a record that stands nowhere in particular: where nothing a machine
				/// builds is a span of the input, and no factory it runs asks where it read,
				/// the two positions are two integers written and never looked at.
				/// </summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void Begin(int arm)
				{
					if (LogCount + 2 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 2);

					Opened = LogCount;
					_number = Records++;
					Log[LogCount++] = 0;
					Log[LogCount++] = arm;
				}

				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void Begin(int arm, int start, int end)
				{
					if (LogCount + 4 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 4);

					Opened = LogCount;
					_number = Records++;
					Log[LogCount++] = 0;
					Log[LogCount++] = arm;
					Log[LogCount++] = start;
					Log[LogCount++] = end;
				}

				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void Put(int value)
				{
					if (LogCount + 1 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 1);

					Log[LogCount++] = value;
				}

				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void Put(int a, int b)
				{
					if (LogCount + 2 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 2);

					Log[LogCount++] = a;
					Log[LogCount++] = b;
				}

				/// <summary>Closes the record: its length goes in front, and it becomes the last.</summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void End(int refs)
				{
					Log[Opened] = LogCount - Opened;
					Last         = _number;
					RefsCount    = refs;
				}

				/// <summary>
				/// The record closed, and named by where it stands rather than by its number:
				/// an extent is the one thing whose value is the record itself, read straight
				/// out of the log by whoever captured it, and never put in a table.
				/// </summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void EndAt(int refs)
				{
					Log[Opened] = LogCount - Opened;
					Last         = Opened;
					RefsCount    = refs;
				}

				/// <summary>
				/// A mark placed or taken away (docs/syntax.md §7.8): a record of its own in the
				/// log, so that what was put back with the log takes its marks with it. The kind
				/// is -1 where the mark opens and -2 where it closes; nothing captures one.
				/// </summary>
				internal void Mark(int kind, int site, int at)
				{
					if (LogCount + 5 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 5);

					Records++;

					Log[LogCount++] = 5;
					Log[LogCount++] = kind;
					Log[LogCount++] = site;
					Log[LogCount++] = at;
					Log[LogCount++] = at;
				}

				/// <summary>A capture made inside a repetition, kept until the rule gathers it.</summary>
				internal void Push(int slot, int a, int b)
				{
					if (RefsCount + 3 > Refs.Length)
						global::System.Array.Resize(ref Refs, Refs.Length * 2 + 3);

					Refs[RefsCount++] = slot;
					Refs[RefsCount++] = a;
					Refs[RefsCount++] = b;
				}

				/// <summary>
				/// Writes what was pushed for the given slots since <paramref name="from"/>: how
				/// many, then each one — the record alone where <paramref name="pairs"/> is false,
				/// the start and end where it is true.
				/// </summary>
				internal void Collect(int from, long slots, bool pairs)
				{
					var count = 0;

					for (var at = from; at < RefsCount; at += 3)
						if ((slots & (1L << Refs[at])) != 0)
							count++;

					Put(count);

					for (var at = from; at < RefsCount; at += 3)
						if ((slots & (1L << Refs[at])) != 0)
						{
							if (pairs)
								Put(Refs[at + 1], Refs[at + 2]);
							else
								Put(Refs[at + 1]);
						}
				}
			}

			/// <summary>Records a refusal against the furthest one seen, as the engine's Fail does.</summary>
			static void Refuse_DotGram(ref Failure failure, int at, string[]? expected)
			{
				if (failure.Looking > 0)
					return;

				if (at > failure.Position)
				{
					failure.Position     = at;
					failure.Expected     = expected;
					failure.ExpectedMore?.Clear();
				}
				else if (at == failure.Position && expected != null && !ReferenceEquals(expected, failure.Expected))
				{
					// The same set said twice is one thing wanted, not two. A rule refused at the
					// furthest position by several of its alternatives says the same set from
					// each, and a message listing it once is the message; a list holding it
					// several times is a list that grew on a parse that went on to succeed.
					var more = failure.ExpectedMore;

					if (more == null)
						failure.ExpectedMore = more = new global::System.Collections.Generic.List<string[]>();
					else if (more.Count > 0 && ReferenceEquals(more[more.Count - 1], expected))
						return;

					more.Add(expected);
				}
			}

			/// <summary>
			/// Records what a choice wanted where the call that begins its widest group refused at the
			/// same place: that call's own set, which the choice's holds, is dropped for it.
			/// </summary>
			static void Refuse_DotGram_Over(ref Failure failure, int at, string[] expected, string[] covered)
			{
				if (failure.Looking > 0)
					return;

				if (at == failure.Position)
				{
					if (ReferenceEquals(failure.Expected, covered))
						failure.Expected = expected;

					failure.ExpectedMore?.Remove(covered);
				}

				Refuse_DotGram(ref failure, at, expected);
			}

			/// <summary>How much of a run matched, asked only when it did not.</summary>
			static int Reach_DotGram(
				global::System.ReadOnlySpan<char> text, int pos, global::System.ReadOnlySpan<char> want)
			{
				var room = text.Length - pos;

				if (want.Length < room)
					room = want.Length;

				var at = 0;

				while (at < room && text[pos + at] == want[at])
					at++;

				return pos + at;
			}

			/// <summary>The stacks used by immediate readers in this class (Machine.Immediate.cs).</summary>
			sealed class ImmediateValues
			{
				internal string[] Stack1 = new string[8];
				internal int Count1;
				internal int High1;

				internal void Push1(string item)
				{
					if (Count1 == Stack1.Length)
						global::System.Array.Resize(ref Stack1, Count1 * 2);

					Stack1[Count1++] = item;

					if (Count1 > High1) High1 = Count1;
				}

				/// <summary>What was pushed since the mark, as one array, and the stack back at the mark.</summary>
				internal string[] Take1(int from)
				{
					var taken = Peek1(from);

					Count1 = from;

					return taken;
				}

				/// <summary>What was pushed since the mark, as one array, the stack left as it is.</summary>
				internal string[] Peek1(int from)
				{
					var count = Count1 - from;

					if (count == 0)
						return global::System.Array.Empty<string>();

					var taken = new string[count];

					global::System.Array.Copy(Stack1, from, taken, 0, count);

					return taken;
				}


				[global::System.ThreadStatic]
				static ImmediateValues? _spare;

				/// <summary>Spares below the one slot, for parses reached from inside others; made the first time one is.</summary>
				[global::System.ThreadStatic]
				static ImmediateValues?[]? _deeper;

				[global::System.ThreadStatic]
				static int _deeperCount;

				/// <summary>A store past the bound, kept while this thread's work still wants it.</summary>
				[global::System.ThreadStatic]
				static ImmediateValues? _large;

				/// <summary>Parses in a row that did not use the room; at <c>LargeIdle</c> it is let go of.</summary>
				[global::System.ThreadStatic]
				static int _largeIdle;

				/// <summary>And where it goes then: reachable until the memory is wanted elsewhere.</summary>
				[global::System.ThreadStatic]
				static global::System.WeakReference<ImmediateValues>? _largeLetGo;

				/// <summary>Parses in a row that left most of the ordinary spare's room unused.</summary>
				[global::System.ThreadStatic]
				static int _spareIdle;

				/// <summary>And where the ordinary spare goes when it has been too big for too long.</summary>
				[global::System.ThreadStatic]
				static global::System.WeakReference<ImmediateValues>? _spareLetGo;

				/// <summary>
				/// Eight is a claim rather than a taste: if eight parses in a row have not wanted
				/// the room a slot holds - the large store, or an ordinary spare far bigger than
				/// the parses that keep coming - this thread's work has changed and the next parse is unlikely
				/// to want it either. Carrying it through a few small parses costs the memory this
				/// thread held a moment ago anyway; carrying it through a hundred would be hoarding.
				///
				/// Counted where a parse ENDS, against what that parse USED. At the rental it
				/// could never arrive: a rental that takes the kept store zeroes the count, and
				/// with no ordinary spare - the state right after a large parse - every rental
				/// takes it. Against CAPACITY it could never arrive either: a store comes back
				/// as large as it was grown, whatever the document was.
				/// </summary>
				const int LargeIdle = 8;

				/// <summary>The same count for the ordinary slot, read the same way.</summary>
				const int SpareIdle = 8;

				internal static ImmediateValues Rent()
				{
					var spare = _spare;

					if (spare != null)
						_spare = null;
					else if (_deeperCount > 0)
					{
						spare = _deeper![--_deeperCount]!;
						_deeper![_deeperCount] = null;
					}
					else if (_large != null)
					{
						spare = _large;
						_large = null;
					}
					else if (_largeLetGo != null && _largeLetGo.TryGetTarget(out var letGo))
					{
						spare = letGo;
						_largeLetGo.SetTarget(null!);
					}
					else if (_spareLetGo != null && _spareLetGo.TryGetTarget(out var letGoSpare))
					{
						spare = letGoSpare;
						_spareLetGo.SetTarget(null!);
					}
					else
						return new ImmediateValues();

					return spare;
				}

				internal static void Return(ImmediateValues values)
				{
					var used = 0L + values.High1;

					if (values.High1 > 0)
					{
						global::System.Array.Clear(values.Stack1, 0, values.High1);
						values.Count1 = values.High1 = 0;
					}


					// Past the bound the store is not thrown away - that was a cliff
					// and not a bound - it is kept while the work keeps wanting it, and handed
					// to the collector once it stops (CSharpEmitter.Outsized). It is emptied
					// first, above: what is kept is the room, never what was built in it.
					if (0L + values.Stack1.Length > 1048576)
					{
						// The same question the ordinary slot asks below: is the room far larger than
						// the use. The bound decides WHICH slot holds the store; it does not decide
						// whether to keep it. This read the parse's use against the BOUND until
						// 2026-09-21, and for a dense store the two are not the same quantity: the
						// room counts three hundred value tables and the use counted only records, so
						// a parse that had just filled a seventeen-megabyte store read as idle and the
						// eighth STEADY parse of the same document threw the store away and rebuilt it.
						if (!(0L + values.Stack1.Length > 4L * used))
							_largeIdle = 0;
						else if (++_largeIdle >= LargeIdle)
						{
							(_largeLetGo ??= new global::System.WeakReference<ImmediateValues>(values)).SetTarget(values);
							_large = null;
							_largeIdle = 0;

							return;
						}

						if (_large != null && !ReferenceEquals(_large, values))
							(_largeLetGo ??= new global::System.WeakReference<ImmediateValues>(_large)).SetTarget(_large);

						_large = values;

						return;
					}

					// The ordinary slot lets go by the same rule as the parked one: counted where a
					// parse ENDS, against what that parse USED. At the rental it could not arrive,
					// for the reason written above LargeIdle. And it is let go of WEAKLY, so a thread that
					// wants the room straight back still gets it, while one that does not has stopped
					// holding it against everybody else.
					if (!(0L + values.Stack1.Length > 4L * used))
						_spareIdle = 0;
					else if (++_spareIdle >= SpareIdle)
					{
						(_spareLetGo ??= new global::System.WeakReference<ImmediateValues>(values)).SetTarget(values);
						_spareIdle = 0;

						return;
					}

					if (_spare == null)
						_spare = values;
					else if (_deeperCount < 3)
						(_deeper ??= new ImmediateValues?[3])[_deeperCount++] = values;
				}

				/// <summary>Whether a local a record would have been kept in was never written.</summary>
				internal static bool IsDefault<T>(T value) => global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(value, default!);
			}

		}
	}
}
