// <auto-generated/>
#nullable enable

namespace DotGram.Snapshots
{
	partial class Split
	{
		static int Recognize_DotGram(global::System.ReadOnlySpan<char> text, int pos, int state, int rootRule, bool whole, bool materialize, ref Failure failure, out object? recognized)
		{
			recognized = null;

			Parser parser = null!;
			RentParser(ref parser);
			var lent = parser != null;
			parser ??= Recycled();

			try
			{
				var entries = parser.Entries;
				var p       = pos;
				var call    = -1;
				var atomic  = -1;
				var repeat  = -1;
				var lookahead = -1;
				var c       = '\0';
				string[]? expected = null;
				var turn0 = 0;
				var completedCall = -1;
				var capture15 = 0;

				entries.Add(new ParserEntry(ParserEntry.Call, 1, pos, -1, -1, -1, -1, 0, rootRule));
				call = 0;
				Trace("enter", state, p, entries.Count, text, "");
				Dispatch:
				switch (state)
				{
					case 0: goto Return;
					case 1: goto Accept;
					case 2:   expected = null; goto Fail;
					case 3: goto S3;
					case 5: goto S5;
					case 6: goto S6;
					case 11: goto S11;
					case 21: goto S21;
					case 26: goto S26;
					case 30: goto S30;
					case 37: goto S37;
					case 44: goto S44;
					case 49: goto S49;
					case 61: goto S61;
					case 65: goto S65;
					case 68: goto S68;
					case 75: goto S75;
					case 82: goto S82;
					case 87: goto S87;
					case 98: goto S98;
					case 111: goto S111;
					case 112: goto S112;
					case 113: goto S113;
					case 114: goto S114;
					case 120: goto S120;
					case 121: goto S121;
					case 122: goto S122;
					default: expected = null; goto Fail;
				}

				S3:
				{
					var atomicIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Atomic, 0, p, call, atomic, repeat, lookahead, 0));
					atomic = atomicIndex;
					Trace("enter atomic", 4, p, entries.Count, text, "trivia");
				}

				{
					var runStart = p;
					while (true)
					{
						if ((uint)p >= (uint)text.Length)
						{
							failure.Starved = true;
							break;
						}
						c = text[p];
						if (!(c == ' ')) break;
						p++;
					}
					if (p > runStart)
						entries.Add(new ParserEntry(ParserEntry.Run, 5, runStart, call, atomic, repeat, lookahead, p));
					Trace("run", 5, p, entries.Count, text, "trivia");
				}

				S5:
				{
					global::System.Diagnostics.Debug.Assert(atomic >= 0 && atomic < entries.Count);
					var boundary = entries[atomic];
					global::System.Diagnostics.Debug.Assert(boundary.Kind == ParserEntry.Atomic);
					entries.RemoveRange(atomic, entries.Count - atomic);
					atomic = boundary.AtomicIndex;
					repeat = boundary.RepeatIndex;
					lookahead = boundary.LookaheadIndex;
					Trace("commit", 0, p, entries.Count, text, "trivia");
					goto Return;
				}

				S6:
				{
					if ((uint)p < (uint)text.Length)
					{
						c = text[p];
						if (c <= 255 && Recognize_DotGram_Class0[c] != 0) goto S7;
					}
					if (lookahead < 0 && !failure.Quiet) goto S7;
					goto Return;
				}

				S7:
				{
					var repeatIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Repeat, 0, p, call, atomic, repeat, lookahead, 0));
					repeat = repeatIndex;
					Trace("enter repeat", 8, p, entries.Count, text, "Script");
				}

				S8:
				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var repeating = entries[repeat];
					global::System.Diagnostics.Debug.Assert(repeating.Kind == ParserEntry.Repeat);
					{
						entries.Add(new ParserEntry(ParserEntry.LoopExit, 112, p, call, atomic, repeat, lookahead, 0));
						entries[repeat] = new ParserEntry(ParserEntry.Repeat, 0, repeating.Position, repeating.CallIndex, repeating.AtomicIndex, repeating.RepeatIndex, repeating.LookaheadIndex, repeating.Value, p);
						Trace("stand exit", 112, p, entries.Count, text, "Script");
					}
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 111, p, call, atomic, repeat, lookahead, 0, 2));
					call = callIndex;
					Trace("call Command", 11, p, entries.Count, text, "Script");
				}

				S11:
				{
					var prefixed = Prefix_DotGram_0(text, p);
					switch (prefixed)
					{
						case 0: goto S79;
						case 1: goto S72;
						case 2: goto S95;
						case 3: goto S14;
						case 4: goto S41;
						case 5: goto S58;
						case 6: goto S65;
						case 7: goto S30;
						case 8: goto S53;
						case 9: goto S91;
					}
					if (prefixed < -1 && Prefix_DotGram_0_Miss(text, ref p, -1 - prefixed, lookahead, ref failure, out expected)) goto Fail;
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						expected = Recognize_DotGram_Expected17;
						goto Fail;
					}
					c = text[p];
					switch (c)
					{
						case 'c': goto S95;
						case 'h': goto S91;
						case 'l': goto S79;
						case 'p': goto S72;
						case 'r': goto S57;
						case 's': goto S53;
						case 'u': goto S41;
						case 'w': goto S13;
					}
					expected = Recognize_DotGram_Expected17;
					goto Fail;
				}

				S13:
				{
					entries.Add(new ParserEntry(ParserEntry.Choice, 30, p, call, atomic, repeat, lookahead, 0));
					Trace("push choice", 30, p, entries.Count, text, "Command");
				}

				S14:
				{
					if (text.Length - p < 5)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected16;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 5), global::System.MemoryExtensions.AsSpan("while")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'w')
							{
								if (text[p + 1] != 'h')
									p += 1;
								else if (text[p + 2] != 'i')
									p += 2;
								else if (text[p + 3] != 'l')
									p += 3;
								else
									p += 4;
							}
						}
						expected = Recognize_DotGram_Expected16;
						goto Fail;
					}
					p += 5;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 21, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
				}

				S17:
				{
					entries.Add(new ParserEntry(ParserEntry.CaptureOpen, 13, p, call, atomic, repeat, lookahead, 0));
					Trace("open capture", 13, p, entries.Count, text, "Word");
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						expected = Recognize_DotGram_Expected2;
						goto Fail;
					}
					c = text[p];
					if (!(((c >= 'a' && c <= 'z'))))
					{
						expected = Recognize_DotGram_Expected2;
						goto Fail;
					}
					p++;
				}

				S19:
				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						expected = Recognize_DotGram_Expected2;
						goto S20;
					}
					c = text[p];
					if (!(((c >= 'a' && c <= 'z'))))
					{
						expected = Recognize_DotGram_Expected2;
						goto S20;
					}
					p++;
					goto S19;
				}

				S20:
				{
					var closed  = 0;
					var openedAt = entries.Count - 1;

					for (; openedAt >= 0; openedAt--)
					{
						var opened = entries[openedAt];

						if (opened.State != 13) continue;

						if (opened.Kind == ParserEntry.Capture)
						{
							closed++;
							continue;
						}

						if (opened.Kind != ParserEntry.CaptureOpen)
							continue;

						if (closed == 0)
							break;

						closed--;
					}

					global::System.Diagnostics.Debug.Assert(openedAt >= 0);
					entries.Add(new ParserEntry(ParserEntry.Capture, 13, entries[openedAt].Position, call, atomic, repeat, lookahead, p));
					Trace("capture", 13, p, entries.Count, text, "Word");
					goto Return;
				}

				S21:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 6, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 6, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected13;
						goto Fail;
					}
					if (text[p] != '{')
					{
						expected = Recognize_DotGram_Expected13;
						goto Fail;
					}
					p += 1;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 26, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S26:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 7, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 7, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected12;
						goto Fail;
					}
					if (text[p] != '}')
					{
						expected = Recognize_DotGram_Expected12;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 3, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 3, p, entries.Count, text, "Command");
					goto Return;
				}

				S30:
				{
					if (text.Length - p < 4)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected15;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 4), global::System.MemoryExtensions.AsSpan("wait")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'w')
							{
								if (text[p + 1] != 'a')
									p += 1;
								else if (text[p + 2] != 'i')
									p += 2;
								else
									p += 3;
							}
						}
						expected = Recognize_DotGram_Expected15;
						goto Fail;
					}
					p += 4;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 37, p, call, atomic, repeat, lookahead, 0, 4));
					call = callIndex;
					Trace("call Number", 33, p, entries.Count, text, "Command");
				}

				{
					entries.Add(new ParserEntry(ParserEntry.CaptureOpen, 14, p, call, atomic, repeat, lookahead, 0));
					Trace("open capture", 14, p, entries.Count, text, "Number");
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						expected = Recognize_DotGram_Expected18;
						goto Fail;
					}
					c = text[p];
					if (!(((c >= '0' && c <= '9'))))
					{
						expected = Recognize_DotGram_Expected18;
						goto Fail;
					}
					p++;
				}

				S35:
				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						expected = Recognize_DotGram_Expected18;
						goto S36;
					}
					c = text[p];
					if (!(((c >= '0' && c <= '9'))))
					{
						expected = Recognize_DotGram_Expected18;
						goto S36;
					}
					p++;
					goto S35;
				}

				S36:
				{
					var closed  = 0;
					var openedAt = entries.Count - 1;

					for (; openedAt >= 0; openedAt--)
					{
						var opened = entries[openedAt];

						if (opened.State != 14) continue;

						if (opened.Kind == ParserEntry.Capture)
						{
							closed++;
							continue;
						}

						if (opened.Kind != ParserEntry.CaptureOpen)
							continue;

						if (closed == 0)
							break;

						closed--;
					}

					global::System.Diagnostics.Debug.Assert(openedAt >= 0);
					entries.Add(new ParserEntry(ParserEntry.Capture, 14, entries[openedAt].Position, call, atomic, repeat, lookahead, p));
					Trace("capture", 14, p, entries.Count, text, "Number");
					goto Return;
				}

				S37:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 4 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 12, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 12, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					if (text[p] != ';')
					{
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 7, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 7, p, entries.Count, text, "Command");
					goto Return;
				}

				S41:
				{
					if (text.Length - p < 6)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected14;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 6), global::System.MemoryExtensions.AsSpan("unless")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'u')
							{
								if (text[p + 1] != 'n')
									p += 1;
								else if (text[p + 2] != 'l')
									p += 2;
								else if (text[p + 3] != 'e')
									p += 3;
								else if (text[p + 4] != 's')
									p += 4;
								else
									p += 5;
							}
						}
						expected = Recognize_DotGram_Expected14;
						goto Fail;
					}
					p += 6;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 44, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S44:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 8, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 8, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected13;
						goto Fail;
					}
					if (text[p] != '{')
					{
						expected = Recognize_DotGram_Expected13;
						goto Fail;
					}
					p += 1;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 49, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S49:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 9, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 9, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected12;
						goto Fail;
					}
					if (text[p] != '}')
					{
						expected = Recognize_DotGram_Expected12;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 4, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 4, p, entries.Count, text, "Command");
					goto Return;
				}

				S53:
				{
					if (text.Length - p < 4)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected11;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 4), global::System.MemoryExtensions.AsSpan("skip")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 's')
							{
								if (text[p + 1] != 'k')
									p += 1;
								else if (text[p + 2] != 'i')
									p += 2;
								else
									p += 3;
							}
						}
						expected = Recognize_DotGram_Expected11;
						goto Fail;
					}
					p += 4;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					if (text[p] != ';')
					{
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 8, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 8, p, entries.Count, text, "Command");
					goto Return;
				}

				S57:
				{
					entries.Add(new ParserEntry(ParserEntry.Choice, 65, p, call, atomic, repeat, lookahead, 0));
					Trace("push choice", 65, p, entries.Count, text, "Command");
				}

				S58:
				{
					if (text.Length - p < 6)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected10;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 6), global::System.MemoryExtensions.AsSpan("return")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'r')
							{
								if (text[p + 1] != 'e')
									p += 1;
								else if (text[p + 2] != 't')
									p += 2;
								else if (text[p + 3] != 'u')
									p += 3;
								else if (text[p + 4] != 'r')
									p += 4;
								else
									p += 5;
							}
						}
						expected = Recognize_DotGram_Expected10;
						goto Fail;
					}
					p += 6;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 61, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S61:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 10, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 10, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					if (text[p] != ';')
					{
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 5, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 5, p, entries.Count, text, "Command");
					goto Return;
				}

				S65:
				{
					if (text.Length - p < 5)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected9;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 5), global::System.MemoryExtensions.AsSpan("raise")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'r')
							{
								if (text[p + 1] != 'a')
									p += 1;
								else if (text[p + 2] != 'i')
									p += 2;
								else if (text[p + 3] != 's')
									p += 3;
								else
									p += 4;
							}
						}
						expected = Recognize_DotGram_Expected9;
						goto Fail;
					}
					p += 5;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 68, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S68:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 11, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 11, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					if (text[p] != ';')
					{
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 6, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 6, p, entries.Count, text, "Command");
					goto Return;
				}

				S72:
				{
					if (text.Length - p < 5)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected8;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 5), global::System.MemoryExtensions.AsSpan("print")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'p')
							{
								if (text[p + 1] != 'r')
									p += 1;
								else if (text[p + 2] != 'i')
									p += 2;
								else if (text[p + 3] != 'n')
									p += 3;
								else
									p += 4;
							}
						}
						expected = Recognize_DotGram_Expected8;
						goto Fail;
					}
					p += 5;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 75, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S75:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 3, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 3, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					if (text[p] != ';')
					{
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 1, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 1, p, entries.Count, text, "Command");
					goto Return;
				}

				S79:
				{
					if (text.Length - p < 3)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected7;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 3), global::System.MemoryExtensions.AsSpan("let")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'l')
							{
								if (text[p + 1] != 'e')
									p += 1;
								else
									p += 2;
							}
						}
						expected = Recognize_DotGram_Expected7;
						goto Fail;
					}
					p += 3;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 82, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S82:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 1, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 1, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected6;
						goto Fail;
					}
					if (text[p] != '=')
					{
						expected = Recognize_DotGram_Expected6;
						goto Fail;
					}
					p += 1;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 87, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S87:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 2, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 2, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					if (text[p] != ';')
					{
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 0, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 0, p, entries.Count, text, "Command");
					goto Return;
				}

				S91:
				{
					if (text.Length - p < 4)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected5;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 4), global::System.MemoryExtensions.AsSpan("halt")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'h')
							{
								if (text[p + 1] != 'a')
									p += 1;
								else if (text[p + 2] != 'l')
									p += 2;
								else
									p += 3;
							}
						}
						expected = Recognize_DotGram_Expected5;
						goto Fail;
					}
					p += 4;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					if (text[p] != ';')
					{
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 9, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 9, p, entries.Count, text, "Command");
					goto Return;
				}

				S95:
				{
					if (text.Length - p < 4)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected4;
						goto Fail;
					}
					if (!global::System.MemoryExtensions.SequenceEqual(text.Slice(p, 4), global::System.MemoryExtensions.AsSpan("call")))
					{
						if (lookahead < 0)
						{
							if (text[p] == 'c')
							{
								if (text[p + 1] != 'a')
									p += 1;
								else if (text[p + 2] != 'l')
									p += 2;
								else
									p += 3;
							}
						}
						expected = Recognize_DotGram_Expected4;
						goto Fail;
					}
					p += 4;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 98, p, call, atomic, repeat, lookahead, 0, 3));
					call = callIndex;
					Trace("call Word", 17, p, entries.Count, text, "Command");
					goto S17;
				}

				S98:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 3 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 4, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 4, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected3;
						goto Fail;
					}
					if (text[p] != '(')
					{
						expected = Recognize_DotGram_Expected3;
						goto Fail;
					}
					p += 1;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					capture15 = p;
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						expected = Recognize_DotGram_Expected2;
						goto Fail;
					}
					c = text[p];
					if (!(((c >= 'a' && c <= 'z'))))
					{
						expected = Recognize_DotGram_Expected2;
						goto Fail;
					}
					p++;
				}

				S104:
				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						expected = Recognize_DotGram_Expected2;
						goto S105;
					}
					c = text[p];
					if (!(((c >= 'a' && c <= 'z'))))
					{
						expected = Recognize_DotGram_Expected2;
						goto S105;
					}
					p++;
					goto S104;
				}

				S105:
				{
					entries.Add(new ParserEntry(ParserEntry.Capture, 15, capture15, call, atomic, repeat, lookahead, p));
					Trace("capture", 15, p, entries.Count, text, "Command");
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected1;
						goto Fail;
					}
					if (text[p] != ')')
					{
						expected = Recognize_DotGram_Expected1;
						goto Fail;
					}
					p += 1;
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						failure.OutOfInput = p + 1;
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					if (text[p] != ';')
					{
						expected = Recognize_DotGram_Expected0;
						goto Fail;
					}
					p += 1;
				}

				{
					entries.Add(new ParserEntry(ParserEntry.Construct, 2, p, call, atomic, repeat, lookahead, 0));
					Trace("construct", 2, p, entries.Count, text, "Command");
					goto Return;
				}

				S111:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 2 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 0, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 0, p, entries.Count, text, "Script");
					goto S8;
				}

				S112:
				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var finished = entries[repeat];
					global::System.Diagnostics.Debug.Assert(finished.Kind == ParserEntry.Repeat);
					var previousRepeat = finished.RepeatIndex;
					if (entries.Count == repeat + 1) entries.RemoveAt(repeat);
					repeat = previousRepeat;
					lookahead = finished.LookaheadIndex;
					Trace("leave repeat", 0, p, entries.Count, text, "Script");
					goto Return;
				}

				S113:
				{
					p = Scan_trivia(text, p, ref failure);
					goto Return;
				}

				S114:
				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					if ((uint)p < (uint)text.Length)
					{
						c = text[p];
						if (c <= 255 && Recognize_DotGram_Class0[c] != 0) goto S116;
					}
					if (lookahead < 0 && !failure.Quiet) goto S116;
					goto S113;
				}

				S116:
				{
					var repeatIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Repeat, 0, p, call, atomic, repeat, lookahead, 0));
					repeat = repeatIndex;
					Trace("enter repeat", 117, p, entries.Count, text, "Script");
				}

				S117:
				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var repeating = entries[repeat];
					global::System.Diagnostics.Debug.Assert(repeating.Kind == ParserEntry.Repeat);
					{
						entries.Add(new ParserEntry(ParserEntry.LoopExit, 121, p, call, atomic, repeat, lookahead, 0));
						entries[repeat] = new ParserEntry(ParserEntry.Repeat, 0, repeating.Position, repeating.CallIndex, repeating.AtomicIndex, repeating.RepeatIndex, repeating.LookaheadIndex, repeating.Value, p);
						Trace("stand exit", 121, p, entries.Count, text, "Script");
					}
				}

				{
					p = Scan_trivia(text, p, ref failure);
				}

				{
					var callIndex = entries.Count;
					entries.Add(new ParserEntry(ParserEntry.Call, 120, p, call, atomic, repeat, lookahead, 0, 2));
					call = callIndex;
					Trace("call Command", 11, p, entries.Count, text, "Script");
					goto S11;
				}

				S120:
				{
					var capturedCall = completedCall;
					global::System.Diagnostics.Debug.Assert(capturedCall >= 0);
					global::System.Diagnostics.Debug.Assert(entries[capturedCall].Kind == ParserEntry.Completed && entries[capturedCall].CallIndex == call && entries[capturedCall].RuleIndex == 2 && entries[capturedCall].Value == p);
					entries.Add(new ParserEntry(ParserEntry.RuleCapture, 0, capturedCall, call, atomic, repeat, lookahead, p));
					Trace("rule capture", 0, p, entries.Count, text, "Script");
					goto S117;
				}

				S121:
				{
					global::System.Diagnostics.Debug.Assert(repeat >= 0 && repeat < entries.Count);
					var finished = entries[repeat];
					global::System.Diagnostics.Debug.Assert(finished.Kind == ParserEntry.Repeat);
					var previousRepeat = finished.RepeatIndex;
					if (entries.Count == repeat + 1) entries.RemoveAt(repeat);
					repeat = previousRepeat;
					lookahead = finished.LookaheadIndex;
					Trace("leave repeat", 113, p, entries.Count, text, "Script");
					goto S113;
				}

				S122:
				{
					turn0 = p;
				}

				{
					if ((uint)p >= (uint)text.Length)
					{
						failure.Starved = true;
						expected = Recognize_DotGram_Expected20;
						goto S125;
					}
					p++;
				}

				{
					p = turn0;
					expected = Recognize_DotGram_Expected19;
					goto Fail;
				}

				S125:
				{
					p = turn0;
					goto Return;
				}

				Return:
				global::System.Diagnostics.Debug.Assert(call >= 0 && call < entries.Count);
				var returned = entries[call];
				global::System.Diagnostics.Debug.Assert(returned.Kind == ParserEntry.Call || returned.Kind == ParserEntry.Completed);
				state = returned.State;
				var previousCall = returned.CallIndex;
				completedCall = call;
				repeat = returned.RepeatIndex;
				lookahead = returned.LookaheadIndex;

				if (returned.RuleIndex >= 0)
				{
					entries[call] = new ParserEntry(ParserEntry.Completed, returned.State, returned.Position, returned.CallIndex, returned.AtomicIndex, returned.RepeatIndex, returned.LookaheadIndex, p, returned.RuleIndex);
				}
				else if (entries.Count == call + 1)
					entries.RemoveAt(call);

				call = previousCall;
				Trace("return", state, p, entries.Count, text, "");
				goto Dispatch;

				Accept:
				if (whole && p != text.Length) { expected = null; goto Fail; }
				if (materialize)
				{
					if (rootRule >= 0)
					{
						var values = parser.Materialization(entries.Count);
						var values0 = parser.Materialization0();
						var values1 = parser.Materialization1();
						Materialize_DotGram(text, parser, entries);
						switch (rootRule)
						{
							case 1:
								recognized = values0[0];
								break;
							case 2:
								recognized = values1[0];
								break;
							case 3:
								recognized = values1[0];
								break;
							case 4:
								recognized = values1[0];
								break;
							default:
								recognized = values[0];
								break;
						}
					}
				}
				return p;

				Fail:
				if (lookahead < 0 && !failure.Quiet && p > failure.Position)
				{
					failure.Position = p;
					failure.Expected = expected;
					failure.ExpectedMore?.Clear();
				}
				else if (lookahead < 0 && !failure.Quiet && p == failure.Position && expected != null)
				{
					(failure.ExpectedMore ??= new global::System.Collections.Generic.List<string[]>()).Add(expected);
				}
				Trace("fail", state, p, entries.Count, text, "");

				while (entries.Count > 0)
				{
					var last = entries.Count - 1;
					var entry = entries[last];
					entries.RemoveAt(last);

					if (entry.Kind == ParserEntry.Choice)
					{
						state  = entry.State;
						p      = entry.Position;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						Trace("resume", state, p, entries.Count, text, "");
						goto Dispatch;
					}
					if (entry.Kind == ParserEntry.LoopExit)
					{
						if (entry.RepeatIndex < 0 || entries[entry.RepeatIndex].Kind != ParserEntry.Repeat || entries[entry.RepeatIndex].RuleIndex != entry.Position)
							continue;

						state  = entry.State;
						p      = entry.Position;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						Trace("resume exit", state, p, entries.Count, text, "");
						goto Dispatch;
					}
					if (entry.Kind == ParserEntry.Run)
					{
						if (entry.Value <= entry.Position) continue;

						state  = entry.State;
						p      = entry.Value - 1;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						entries.Add(new ParserEntry(ParserEntry.Run, entry.State, entry.Position, entry.CallIndex, entry.AtomicIndex, entry.RepeatIndex, entry.LookaheadIndex, p));
						Trace("shorten run", state, p, entries.Count, text, "");
						goto Dispatch;
					}

					if (entry.Kind == ParserEntry.Capture || entry.Kind == ParserEntry.Construct || entry.Kind == ParserEntry.RuleCapture || entry.Kind == ParserEntry.CaptureOpen)
						continue;

					if (entry.Kind == ParserEntry.Call || entry.Kind == ParserEntry.Completed)
					{
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
						p      = entry.Position;
					}
					else if (entry.Kind == ParserEntry.Atomic)
					{
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
					}
					else if (entry.Kind == ParserEntry.Repeat)
					{
						p      = entry.Position;
						call   = entry.CallIndex;
						atomic = entry.AtomicIndex;
						repeat = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;
					}
					else
					{
						global::System.Diagnostics.Debug.Assert(entry.Kind == ParserEntry.Lookahead);
						p         = entry.Position;
						call      = entry.CallIndex;
						atomic    = entry.AtomicIndex;
						repeat    = entry.RepeatIndex;
						lookahead = entry.LookaheadIndex;

						if (entry.Value == 0)
						{
							state = entry.State;
							if (entry.RuleIndex >= 0)
							{
								entries.Add(new ParserEntry(ParserEntry.Capture, entry.RuleIndex, p, call, atomic, repeat, lookahead, p));
								Trace("capture negative lookahead", entry.RuleIndex, p, entries.Count, text, "");
							}
							Trace("negative lookahead succeeds", state, p, entries.Count, text, "");
							goto Dispatch;
						}
					}
				}

				return -1;
			}
			finally
			{
				parser.Reset();
				if (lent) ReturnParser(parser); else Recycle(parser);
			}
		}
	}
}
