// <auto-generated/>
#nullable enable

namespace DotGram.Snapshots
{
	partial class Twice
	{
		static partial class Immediate
		{
			/// <summary>Parses the whole input as <c>Sum</c>.</summary>
			/// <exception cref="global::System.FormatException">
			/// The input is not <c>Sum</c>. <c>TryParseSum</c> answers instead.
			/// </exception>
			public static int ParseSum(string input)
			{
				var match = TryParseSum(input);

				if (match.IsSuccess)
					return match.Value;

				throw new global::System.FormatException(match.Error + " at " + match.Position.ToString());
			}

			/// <summary>Parses the whole input as <c>Sum</c>, answering rather than throwing.</summary>
			public static Match<int> TryParseSum(string input)
			{
				var text    = global::System.MemoryExtensions.AsSpan(input);
				var parserWhole = global::System.MemoryExtensions.AsMemory(input);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Sum_Whole(text, 0, ref failure, out var recognized, parserWhole);

				if (end < 0)
				{
					failure = new Failure();
					end     = Recognize_Sum_Whole(text, 0, ref failure, out recognized, parserWhole);
				}

				if (end < 0)
				{
					var starved = failure.OutOfInput == failure.Position + 1 || failure.Position >= text.Length;

					var otherwise = starved
						? "Expected more input."
						: "Input does not match 'Sum'.";

					return Match<int>.Failed(starved ? Outcome.Starved : Outcome.NoMatch, otherwise, failure.Position, failure.Expected, failure.ExpectedMore);
				}

				return Match<int>.Success(recognized, 0, end);
			}

			/// <summary>Parses the whole input as <c>Sum</c>, answering only whether it is one.</summary>
			/// <remarks>
			/// Nothing is said about a refusal: <c>TryParseSum</c> returning a match says where and why.
			/// </remarks>
			public static bool TryParseSum(string input, out int value)
			{
				var text    = global::System.MemoryExtensions.AsSpan(input);
				var parserWhole = global::System.MemoryExtensions.AsMemory(input);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Sum_Whole(text, 0, ref failure, out var recognized, parserWhole);

				if (end < 0)
				{
					value = default!;
					return false;
				}

				value = recognized;

				return true;
			}

			/// <summary>Reads a <c>Sum</c> beginning at <paramref name="at"/>.</summary>
			/// <remarks>
			/// The input is not required to end there: what comes back says where the
			/// reading began and how far it got, so a caller may go on from it. A position
			/// is an offset into the text.
			/// </remarks>
			public static Match<int> TryParseSum(string input, int at)
			{
				if (at < 0 || at > input.Length)
				{
					return Match<int>.Failed(Outcome.NoMatch, "Position " + at.ToString() + " is outside the input.", at, null, null);
				}

				var text    = global::System.MemoryExtensions.AsSpan(input);
				var parserWhole = global::System.MemoryExtensions.AsMemory(input);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Sum(text, at, ref failure, out var recognized, parserWhole);

				if (end < 0)
				{
					failure = new Failure();
					end     = Recognize_Sum(text, at, ref failure, out recognized, parserWhole);
				}

				var began = failure.Began;

				if (end < 0)
				{
					var starved = failure.OutOfInput == failure.Position + 1 || failure.Position >= text.Length;

					var otherwise = starved
						? "Expected more input."
						: "Input does not match 'Sum'.";

					return Match<int>.Failed(starved ? Outcome.Starved : Outcome.NoMatch, otherwise, failure.Position, failure.Expected, failure.ExpectedMore);
				}

				return Match<int>.Success(recognized, began, end - began);
			}

			/// <summary>Reads a <c>Sum</c> at <paramref name="at"/>, answering only whether one is there.</summary>
			/// <remarks>
			/// Nothing is said about a refusal: <c>TryParseSum</c> returning a match says where and why.
			/// On a reading, <paramref name="at"/> moves to the end of what was read; on a
			/// refusal it stays where it was.
			/// </remarks>
			public static bool TryParseSum(string input, ref int at, out int value)
			{
				if (at < 0 || at > input.Length)
					throw new global::System.ArgumentOutOfRangeException(nameof(at));

				var text    = global::System.MemoryExtensions.AsSpan(input);
				var parserWhole = global::System.MemoryExtensions.AsMemory(input);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Sum(text, at, ref failure, out var recognized, parserWhole);

				if (end < 0)
				{
					value = default!;
					return false;
				}

				var began = failure.Began;

				value = recognized;
				at = end;

				return true;
			}

			/// <summary>Reads a <c>Sum</c> inside a window of the input.</summary>
			/// <remarks>
			/// The reading begins at <paramref name="at"/> and sees no character from
			/// <c>at + length</c> on; it is not required to reach that far, and what comes back
			/// says how far it got. Positions are offsets into the whole input.
			/// </remarks>
			public static Match<int> TryParseSum(string input, int at, int length)
			{
				if (at < 0 || length < 0 || at > input.Length - length)
				{
					return Match<int>.Failed(Outcome.NoMatch, "The window " + at.ToString() + ".." + (at + length).ToString() + " is outside the input.", at, null, null);
				}

				var text    = global::System.MemoryExtensions.AsSpan(input, 0, at + length);
				var parserWhole = global::System.MemoryExtensions.AsMemory(input, 0, at + length);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Sum(text, at, ref failure, out var recognized, parserWhole);

				if (end < 0)
				{
					failure = new Failure();
					end     = Recognize_Sum(text, at, ref failure, out recognized, parserWhole);
				}

				var began = failure.Began;

				if (end < 0)
				{
					var starved = failure.OutOfInput == failure.Position + 1 || failure.Position >= text.Length;

					var otherwise = starved
						? "Expected more input."
						: "Input does not match 'Sum'.";

					return Match<int>.Failed(starved ? Outcome.Starved : Outcome.NoMatch, otherwise, failure.Position, failure.Expected, failure.ExpectedMore);
				}

				return Match<int>.Success(recognized, began, end - began);
			}

			/// <summary>Reads a <c>Sum</c> at <paramref name="at"/>, answering only whether one is there.</summary>
			/// <remarks>
			/// Nothing is said about a refusal: <c>TryParseSum</c> returning a match says where and why.
			/// On a reading, <paramref name="at"/> moves to the end of what was read; on a
			/// refusal it stays where it was.
			/// </remarks>
			public static bool TryParseSum(string input, ref int at, int length, out int value)
			{
				if (at < 0 || length < 0 || at > input.Length - length)
					throw new global::System.ArgumentOutOfRangeException(nameof(at));

				var text    = global::System.MemoryExtensions.AsSpan(input, 0, at + length);
				var parserWhole = global::System.MemoryExtensions.AsMemory(input, 0, at + length);
				var failure = new Failure { Quiet = true };

				var end = Recognize_Sum(text, at, ref failure, out var recognized, parserWhole);

				if (end < 0)
				{
					value = default!;
					return false;
				}

				var began = failure.Began;

				value = recognized;
				at = end;

				return true;
			}

			/// <summary>What <c>Sum</c> builds its value with (docs/syntax.md §7.3).</summary>
			static int Construct_Sum(int first, int[] rest) =>
#line 27 "Twice.gram"
                                                                (first + rest.Length);
#line default

			/// <summary>What <c>More</c> builds its value with (docs/syntax.md §7.3).</summary>
			static int Construct_More(int value) =>
#line 29 "Twice.gram"
                                    (value);
#line default

			/// <summary>What <c>Term</c> builds its value with (docs/syntax.md §7.3).</summary>
			static int Construct_Term(int inner) =>
#line 32 "Twice.gram"
                                                              (inner);
#line default

			/// <summary>What <c>Term</c> builds its value with (docs/syntax.md §7.3).</summary>
			static int Construct_Term_1(int high, int low) =>
#line 33 "Twice.gram"
                                                              (high - low);
#line default

			/// <summary>What <c>Term</c> builds its value with (docs/syntax.md §7.3).</summary>
			static int Construct_Term_2(int high) =>
				(high);

			/// <summary>What <c>Digits</c> builds its value with (docs/syntax.md §7.3).</summary>
			static int Construct_Digits(string text) =>
#line 36 "Twice.gram"
                                      (int.Parse(text));
#line default

			/// <summary>The readers of the grammar, and what they all read from, in one place: a call between them passes a position and nothing else.</summary>
			private ref struct Reader_DotGram
			{
				readonly global::System.ReadOnlySpan<char> text;
				internal Failure failure;
				/// <summary>How many entries to a rule that can reach itself, for the stack probe.</summary>
				internal int probes;
				readonly Ways ways;
				/// <summary>The whole input, for a reading that has to go on with it elsewhere.</summary>
				readonly global::System.ReadOnlyMemory<char> whole;
				readonly ImmediateValues values;
				internal int last0;

				internal Reader_DotGram(global::System.ReadOnlySpan<char> text, Ways ways, ImmediateValues values, global::System.ReadOnlyMemory<char> parserWhole)
				{
					this.text    = text;
					this.failure = default;
					this.ways    = ways;
					this.probes  = 0;
					this.values = values;
					this.last0 = default!;
					this.whole   = parserWhole;
				}

				/// <summary>Whether there is stack left to read one more level with.</summary>
				/// <remarks>
				/// `TryEnsureSufficientExecutionStack` is .NET Core's and .NET Standard 2.1's. Where
				/// it is not there — .NET Framework, netstandard2.0 — the older pair answers the same
				/// question, at the cost of an exception on the one probe in sixty-four that finds
				/// the margin gone.
				/// </remarks>
				static bool EnoughStack_DotGram()
				{
					#if NETCOREAPP2_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
					return global::System.Runtime.CompilerServices.RuntimeHelpers.TryEnsureSufficientExecutionStack();
					#else
					try
					{
						global::System.Runtime.CompilerServices.RuntimeHelpers.EnsureSufficientExecutionStack();

						return true;
					}
					catch (global::System.InsufficientExecutionStackException)
					{
						return false;
					}
					#endif
				}

				/// <summary>Carries this reading onto a stack of its own and answers with what it read.</summary>
				internal int Deepen_DotGram(int pos, int which, int power)
				{
					// Nothing to carry it onto: a reading over a window has no whole input.
					if (this.whole.IsEmpty)
						throw new global::System.InsufficientExecutionStackException();

					var deep = new Deep_DotGram();

					deep.whole  = this.whole;
					deep.ways   = this.ways;
					deep.values = this.values;
					deep.failure = this.failure;
					deep.last0 = this.last0;
					deep.probes = this.probes;
					deep.pos    = pos;
					deep.which  = which;
					deep.power  = power;

					var thread = new global::System.Threading.Thread(deep.Run, 16 * 1024 * 1024);

					thread.Start();
					thread.Join();

					this.failure = deep.failure;
					this.last0 = deep.last0;
					this.probes = deep.probes;

					if (deep.thrown != null)
						global::System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(deep.thrown).Throw();

					return deep.end;
				}

				/// <summary><c>Sum</c>, and the way back into it.</summary>
				public int Read_Sum(int pos)
				{
					if ((probes++ & 63) == 0 && !EnoughStack_DotGram())
						return Deepen_DotGram(pos, 0, 0);

					var s  = ways.Cursor;

					while (true)
					{
						var q = Read_Sum_Body(pos);

						if (q >= 0)
							return q;


						if (ways.Cursor > s && ways.Retry(s))
							continue;

						return -1;
					}
				}

				/// <summary>What <c>Sum</c> is, one reading of it at a time.</summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				public int Read_Sum_Body(int pos)
				{
					var p = pos;
					var c = '\0';
					var rb_0 = values.Count0;
					int r0 = default!;
					var q0 = Read_Term(p);
					if (q0 < 0) return -1;
					p = q0;
					r0 = last0;
					var q1 = Read_trivia(p);
					if (q1 < 0) return -1;
					p = q1;
					while (true)
					{
						var o1 = (uint)p < (uint)text.Length;

						if (o1)
						{
							c = text[p];
							o1 = c == ' ' || c == '+';
						}

						if (!o1 && failure.Quiet)
						{
							break;
						}

						var s2  = ways.Cursor;
						var rr2_0 = values.Count0;
						var q2 = -1;

						while (true)
						{
							q2 = Read_Sum_Part0(p, pos, rb_0);

							if (q2 >= 0)
								break;

							values.Count0 = rr2_0;

							if (ways.Cursor > s2 && ways.Retry(s2))
								continue;

							break;
						}

						if (q2 < 0)
						{

							break;
						}

						p = q2;
					}
					var g0At = r0;
					var g0 = g0At;
					if (!Recognize_DotGram_Guard4(g0))
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, null);
						return -1;
					}
					last0 = Construct_Sum(r0!, values.Take0(rb_0)!);
					return p;
				}

				/// <summary>One alternative of <c>Sum</c>, read where it stood.</summary>
				public int Read_Sum_Part0(int pos, int start, int refs_0)
				{
					var p = pos;
					var q0 = Read_trivia(p);
					if (q0 < 0) return -1;
					p = q0;
					var q1 = Read_More(p);
					if (q1 < 0) return -1;
					p = q1;
					values.Push0(last0);
					return p;
				}

				/// <summary><c>Term</c>, and the way back into it.</summary>
				public int Read_Term(int pos)
				{
					var s  = ways.Cursor;

					while (true)
					{
						var q = Read_Term_Body(pos);

						if (q >= 0)
							return q;


						if (ways.Cursor > s && ways.Retry(s))
							continue;

						return -1;
					}
				}

				/// <summary>What <c>Term</c> is, one reading of it at a time.</summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				public int Read_Term_Body(int pos)
				{
					var p = pos;
					var c = '\0';
					int? r0 = default;
					int? r1 = default;
					if ((uint)p >= (uint)text.Length)
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected4);
						return -1;
					}
					c = text[p];
					switch (c)
					{
						case '(':
							{
								p += 1;
								var q0 = Read_trivia(p);
								if (q0 < 0) return -1;
								p = q0;
								var q1 = Read_Sum(p);
								if (q1 < 0) return -1;
								p = q1;
								r0 = last0;
								var q2 = Read_trivia(p);
								if (q2 < 0) return -1;
								p = q2;
								if ((uint)p >= (uint)text.Length || text[p] != ')')
								{
									if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected1);
									return -1;
								}
								p += 1;
								last0 = Construct_Term((int)r0!);
								break;
							}
						default:
							{
								var q3 = Read_Digits(p);
								if (q3 < 0)
								{
									if (!failure.Quiet) Refuse_DotGram_Over(ref failure, p, Recognize_DotGram_Expected4, Recognize_DotGram_Expected5);
									return -1;
								}
								p = q3;
								r1 = last0;
								var w0  = -1;
								var d0 = 0;
								if (ways.Cursor < ways.Count)
								{
									w0  = ways.Cursor;
									d0 = ways.Items[w0 * 2];
									ways.Cursor++;
								}
								else
								{
									w0 = ways.Open(0, 1);
								}

								var q4 = -1;
								if (q4 < 0 && d0 <= 0)
								{
									var s1  = ways.Cursor;

									q4 = Read_Term_Part0(p, pos, r1);

									if (q4 < 0)
									{
									}

									if (q4 < 0)
										ways.Next(w0, 1, 1);
								}
								if (q4 < 0 && d0 <= 1)
								{
									var s2  = ways.Cursor;

									q4 = Read_Term_Part1(p, pos, r1);

									if (q4 < 0)
									{
									}
								}

								if (q4 < 0)
									return -1;

								p = q4;
								break;
							}
					}
					return p;
				}

				/// <summary>One alternative of <c>Term</c>, read where it stood.</summary>
				public int Read_Term_Part0(int pos, int start, int? r1)
				{
					var p = pos;
					int? r2 = default;
					var q0 = Read_trivia(p);
					if (q0 < 0) return -1;
					p = q0;
					if ((uint)p >= (uint)text.Length || text[p] != '^')
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected3);
						return -1;
					}
					p += 1;
					var q1 = Read_trivia(p);
					if (q1 < 0) return -1;
					p = q1;
					var q2 = Read_Digits(p);
					if (q2 < 0) return -1;
					p = q2;
					r2 = last0;
					var g0At = r1;
					int? g0 = ImmediateValues.IsDefault(g0At) ? default(int?) : g0At;
					var g1At = r2;
					int? g1 = ImmediateValues.IsDefault(g1At) ? default(int?) : g1At;
					if (!Recognize_DotGram_Guard5(g0, g1))
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, null);
						return -1;
					}
					last0 = Construct_Term_1((int)r1!, (int)r2!);
					return p;
				}

				/// <summary>One alternative of <c>Term</c>, read where it stood.</summary>
				public int Read_Term_Part1(int pos, int start, int? r1)
				{
					var p = pos;
					last0 = Construct_Term_2((int)r1!);
					return p;
				}

				/// <summary><c>trivia</c>, read by a method of its own.</summary>
				public int Read_trivia(int pos)
				{
					var p = pos;
					var q0 = Read_trivia_Part0(p);
					if (q0 < 0)
						return -1;
					p = q0;
					return p;
				}

				/// <summary>One alternative of <c>trivia</c>, read where it stood.</summary>
				public int Read_trivia_Part0(int pos)
				{
					var p = pos;
					var c = '\0';
					while (true)
					{
						if ((uint)p >= (uint)text.Length)
							break;

						c = text[p];

						if (!(c == ' '))
							break;

						p++;
					}

					return p;
				}

				/// <summary><c>Digits</c>, read by a method of its own.</summary>
				public int Read_Digits(int pos)
				{
					var p = pos;
					var c = '\0';
					var a0 = -1;
					var b0 = -1;
					a0 = p;
					var m0 = p;
					while (true)
					{
						if ((uint)p >= (uint)text.Length)
							break;

						c = text[p];

						if (!(((c >= '0' && c <= '9'))))
							break;

						p++;
					}

					if (p < m0 + 1)
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected5);
						return -1;
					}

					b0 = p;
					last0 = Construct_Digits((a0 < 0 ? string.Empty : text.Slice(a0, b0 - a0).ToString())!);
					return p;
				}

				/// <summary><c>More</c>, and the way back into it.</summary>
				public int Read_More(int pos)
				{
					var s  = ways.Cursor;

					while (true)
					{
						var q = Read_More_Body(pos);

						if (q >= 0)
							return q;


						if (ways.Cursor > s && ways.Retry(s))
							continue;

						return -1;
					}
				}

				/// <summary>What <c>More</c> is, one reading of it at a time.</summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				public int Read_More_Body(int pos)
				{
					var p = pos;
					int r0 = default!;
					if ((uint)p >= (uint)text.Length || text[p] != '+')
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, Recognize_DotGram_Expected0);
						return -1;
					}
					p += 1;
					var q0 = Read_trivia(p);
					if (q0 < 0) return -1;
					p = q0;
					var q1 = Read_Term(p);
					if (q1 < 0) return -1;
					p = q1;
					r0 = last0;
					last0 = Construct_More(r0!);
					return p;
				}

				/// <summary>The whole input as <c>Sum</c>, and the way back into it.</summary>
				public int Recognize_Sum_Whole_Read(int pos)
				{
					var s  = ways.Cursor;

					while (true)
					{
						var q = Recognize_Sum_Whole_Read_Body(pos);

						if (q >= 0)
							return q;


						if (ways.Cursor > s && ways.Retry(s))
							continue;

						return -1;
					}
				}

				/// <summary>What <c>Sum</c> is read by, whichever stack it is read on.</summary>
				public int Recognize_Sum_Whole_Read_Body(int pos)
				{
					var p = pos;
					var rb_0 = values.Count0;
					var q0 = Read_trivia(p);
					if (q0 < 0) return -1;
					p = q0;
					var q1 = Read_Sum(p);
					if (q1 < 0) return -1;
					p = q1;
					var q2 = Read_trivia(p);
					if (q2 < 0) return -1;
					p = q2;
					if (p != text.Length)
					{
						if (!failure.Quiet) Refuse_DotGram(ref failure, p, null);
						return -1;
					}
					return p;
				}

				/// <summary>A reading of <c>Sum</c>, and the way back into it.</summary>
				public int Recognize_Sum_Read(int pos)
				{
					var s  = ways.Cursor;

					while (true)
					{
						var q = Recognize_Sum_Read_Body(pos);

						if (q >= 0)
							return q;


						if (ways.Cursor > s && ways.Retry(s))
							continue;

						return -1;
					}
				}

				/// <summary>What <c>Sum</c> is read by, whichever stack it is read on.</summary>
				public int Recognize_Sum_Read_Body(int pos)
				{
					var p = pos;
					var rb_0 = values.Count0;
					var q0 = Read_trivia(p);
					if (q0 < 0) return -1;
					p = q0;
					failure.Began = p;
					var q1 = Read_Sum(p);
					if (q1 < 0) return -1;
					p = q1;
					return p;
				}

			}

			/// <summary>A reading, in a shape another thread can pick up (Machine.Reader.cs).</summary>
			private sealed class Deep_DotGram
			{
				internal global::System.ReadOnlyMemory<char> whole;
				internal Ways ways = default!;
				internal ImmediateValues values = default!;
				internal Failure failure = default!;
				internal int last0 = default!;
				internal int probes;
				internal int pos;
				internal int which;
				internal int power;
				internal int end;
				internal global::System.Exception? thrown;

				internal void Run()
				{
					try
					{
						var reader = new Reader_DotGram(this.whole.Span, this.ways, this.values, this.whole);

						reader.failure = this.failure;
						reader.last0 = this.last0;
						reader.probes = this.probes;

						switch (this.which)
						{
							case 0: this.end = reader.Read_Sum(this.pos); break;
						}

						this.failure = reader.failure;
						this.last0 = reader.last0;
						this.probes = reader.probes;
					}
					catch (global::System.Exception caught)
					{
						this.thrown = caught;
					}
				}
			}

			/// <summary>The whole input as <c>Sum</c>, read by methods.</summary>
			static int Recognize_Sum_Whole(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out int value, global::System.ReadOnlyMemory<char> parserWhole)
			{
				var ways = Ways.Rent();
				var values = ImmediateValues.Rent();

				try
				{
					var reader = new Reader_DotGram(text, ways, values, parserWhole);

					reader.failure = failure;

					var end = reader.Recognize_Sum_Whole_Read(pos);

					failure = reader.failure;

					if (end < 0)
					{
						value = default!;

						return end;
					}

					value = reader.last0;

					return end;
				}
				finally
				{
					Ways.Return(ways);
					ImmediateValues.Return(values);
				}
			}

			/// <summary>The whole input as <c>Sum</c>, read by methods.</summary>
			static int Recognize_Sum(global::System.ReadOnlySpan<char> text, int pos, ref Failure failure, out int value, global::System.ReadOnlyMemory<char> parserWhole)
			{
				var ways = Ways.Rent();
				var values = ImmediateValues.Rent();

				try
				{
					var reader = new Reader_DotGram(text, ways, values, parserWhole);

					reader.failure = failure;

					var end = reader.Recognize_Sum_Read(pos);

					failure = reader.failure;

					if (end < 0)
					{
						value = default!;

						return end;
					}

					value = reader.last0;

					return end;
				}
				finally
				{
					Ways.Return(ways);
					ImmediateValues.Return(values);
				}
			}



			static bool Recognize_DotGram_Guard0(int first) =>
#line 27 "Twice.gram"
                                               (first >= 0);
#line default

			static bool Recognize_DotGram_Guard1(int? high, int? low) =>
#line 33 "Twice.gram"
                                            (high >= low);
#line default

			static bool Recognize_DotGram_Guard2(int first) =>
#line 27 "Twice.gram"
                                               (first >= 0);
#line default

			static bool Recognize_DotGram_Guard3(int? high, int? low) =>
#line 33 "Twice.gram"
                                            (high >= low);
#line default

			static bool Recognize_DotGram_Guard4(int first) =>
#line 27 "Twice.gram"
                                               (first >= 0);
#line default

			static bool Recognize_DotGram_Guard5(int? high, int? low) =>
#line 33 "Twice.gram"
                                            (high >= low);
#line default

			static string[]? Recognize_DotGram_Expected0_Built;
			static string[] Recognize_DotGram_Expected0 => Recognize_DotGram_Expected0_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected0_Built, new string[] { "'+'" }, null) ?? Recognize_DotGram_Expected0_Built!;

			static string[]? Recognize_DotGram_Expected1_Built;
			static string[] Recognize_DotGram_Expected1 => Recognize_DotGram_Expected1_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected1_Built, new string[] { "')'" }, null) ?? Recognize_DotGram_Expected1_Built!;

			static string[]? Recognize_DotGram_Expected2_Built;
			static string[] Recognize_DotGram_Expected2 => Recognize_DotGram_Expected2_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected2_Built, new string[] { "'('" }, null) ?? Recognize_DotGram_Expected2_Built!;

			static string[]? Recognize_DotGram_Expected3_Built;
			static string[] Recognize_DotGram_Expected3 => Recognize_DotGram_Expected3_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected3_Built, new string[] { "'^'" }, null) ?? Recognize_DotGram_Expected3_Built!;

			static string[]? Recognize_DotGram_Expected4_Built;
			static string[] Recognize_DotGram_Expected4 => Recognize_DotGram_Expected4_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected4_Built, new string[] { "['(' | '0'..'9']" }, null) ?? Recognize_DotGram_Expected4_Built!;

			static string[]? Recognize_DotGram_Expected5_Built;
			static string[] Recognize_DotGram_Expected5 => Recognize_DotGram_Expected5_Built ?? global::System.Threading.Interlocked.CompareExchange(ref Recognize_DotGram_Expected5_Built, new string[] { "['0'..'9']" }, null) ?? Recognize_DotGram_Expected5_Built!;

			/// <summary>What kind of answer a publication gave (docs/syntax.md §7.5).</summary>
			public enum Outcome
			{
				/// <summary>The input matched, and <c>Value</c> holds what it built.</summary>
				Success,

				/// <summary>The input was there and did not fit.</summary>
				NoMatch,

				/// <summary>The input ran out where more was needed.</summary>
				Starved,
			}

			/// <summary>What a publication answers with: the value, or why there is none.</summary>
			public readonly struct Match<T>
			{
				/// <summary>What would have fit at the furthest position, or null.</summary>
				private readonly string[]? _expected;

				/// <summary>The arrays that tied with it, or null where none did.</summary>
				private readonly global::System.Collections.Generic.List<string[]>? _tied;

				/// <summary>
				/// What <c>Error</c> says when nothing named what would have fit. A literal
				/// chosen where the match failed, so naming it costs nothing.
				/// </summary>
				private readonly string? _otherwise;

				private Match(
					Outcome outcome, T value, long position, int length,
					string[]? expected, global::System.Collections.Generic.List<string[]>? tied,
					string? otherwise)
				{
					Outcome    = outcome;
					Value      = value;
					Position   = position;
					Length     = length;
					_expected  = expected;
					_tied      = tied;
					_otherwise = otherwise;
				}

				/// <summary>Whether there is a value.</summary>
				public bool IsSuccess { get { return Outcome == Outcome.Success; } }

				/// <summary>
				/// Which kind of answer this is: the value, input that did not fit, or input
				/// that ran out (docs/syntax.md §7.5).
				/// </summary>
				public Outcome Outcome { get; }

				/// <summary>What was recognized. Meaningless unless <c>IsSuccess</c>.</summary>
				public T Value { get; }

				/// <summary>
				/// Why nothing was recognized, or null.
				/// </summary>
				/// <remarks>
				/// Built where it is asked for rather than where the match failed, and built
				/// again on each ask. A caller that only wants to know whether the input
				/// matched pays for none of it, which is most callers and every one in a loop
				/// over input that is expected to fail sometimes.
				/// </remarks>
				public string? Error
				{
					get
					{
						if (IsSuccess)
							return null;

						var expected = _expected;

						if (_tied != null)
						{
							var total = expected == null ? 0 : expected.Length;

							foreach (var each in _tied)
								total += each.Length;

							var merged = new string[total];
							var at     = 0;

							if (expected != null)
							{
								expected.CopyTo(merged, 0);
								at = expected.Length;
							}

							foreach (var each in _tied)
							{
								each.CopyTo(merged, at);
								at += each.Length;
							}

							expected = merged;
						}

						if (expected == null || expected.Length == 0)
							return _otherwise;

						// A rule that says what its own refusal says (docs/syntax.md §4's `on
						// fail`) writes it as one item, marked with a character no grammar can
						// write. Where one stands here it is the whole answer: the author took
						// the wording, and what else could have stood here is not it.
						for (var i = 0; i < expected.Length; i++)
							if (expected[i].Length > 0 && expected[i][0] == '\u0000')
								return expected[i].Substring(1);

						// Two sites may ask for the same thing — a literal written in two rules,
						// or the `<` that opens a type argument list in more than one — and a
						// reader is owed one mention of it rather than one per site. Copied
						// rather than compacted where it stands: without a tie this array is the
						// one the generator declared `static readonly`, and rewriting that would
						// change what every later failure says.
						if (expected.Length > 1)
						{
							var unique = new string[expected.Length];
							var kept   = 0;

							for (var i = 0; i < expected.Length; i++)
							{
								var seen = false;

								for (var j = 0; j < kept; j++)
									if (string.Equals(
											unique[j], expected[i], global::System.StringComparison.Ordinal))
									{
										seen = true;
										break;
									}

								if (!seen)
									unique[kept++] = expected[i];
							}

							if (kept < expected.Length)
							{
								expected = new string[kept];
								global::System.Array.Copy(unique, expected, kept);
							}
						}

						if (expected.Length == 1)
							return "Expected " + expected[0] + ".";

						return "Expected " +
							string.Join(", ", expected, 0, expected.Length - 1) +
							" or " + expected[expected.Length - 1] + ".";
					}
				}

				/// <summary>
				/// Where the match began, or how far the input could be followed before it
				/// failed. An offset into the whole input, so a <c>long</c>: an input may be a
				/// file larger than an <c>int</c> can index (docs/syntax.md §6.3).
				/// </summary>
				public long Position { get; }

				/// <summary>
				/// How much was matched, in input items, and zero when nothing was. An extent
				/// into a buffer rather than an offset into the input, so an <c>int</c>.
				/// </summary>
				public int Length { get; }

				internal static Match<T> Success(T value, long position, int length)
				{
					return new Match<T>(Outcome.Success, value, position, length, null, null, null);
				}

				internal static Match<T> Failed(
					Outcome outcome, string otherwise, long position, string[]? expected,
					global::System.Collections.Generic.List<string[]>? tied)
				{
					return new Match<T>(outcome, default!, position, 0, expected, tied, otherwise);
				}
			}

			/// <summary>Where a match got before it gave up, and why.</summary>
			struct Failure
			{
				/// <summary>
				/// The furthest position the input was followed to. Zero on a match that
				/// succeeded without ever backtracking, and meaningless unless one failed.
				/// </summary>
				public int Position;

				/// <summary>
				/// Where something wanted more input than remained, one past the position, or
				/// zero — what <c>Outcome</c> tells "the input ran out" from "the input did
				/// not fit" by (§7.5).
				/// </summary>
				/// <remarks>
				/// <para>
				/// A position rather than a flag, and written straight here rather than
				/// threaded through <c>Fail:</c> like <c>Expected</c>: what the boundary asks
				/// is whether the <em>furthest</em> failure ran out, so a room check that
				/// failed somewhere the parse later got past answers by not matching
				/// <c>Position</c>. Nothing has to be adopted, nothing has to be cleared, and
				/// the automaton's own unwinding is untouched — which is why this costs a
				/// store on a failure path and nothing anywhere else.
				/// </para>
				/// <para>
				/// One past, because a zeroed struct has to mean "nowhere" and zero is a
				/// position. Only a test wanting more than one character writes it: one
				/// wanting a single character can only fail for want of room at the very end
				/// of the input, which the boundary reads off <c>Position</c> itself.
				/// </para>
				/// </remarks>
				// A grammar whose every test wants one character never writes this — and a
				// field nothing assigns is a warning in somebody else's build, which for a
				// build that treats warnings as errors is a broken compilation of a file
				// they did not write.
				#pragma warning disable 0649
				public int OutOfInput;
				#pragma warning restore 0649
			/// <summary>Where the value begins: past the trivia the reading started on.</summary>
			// A publication compiled as a plain method has no reading that begins where it is told,
			// so nothing writes this — and a field nothing assigns is a warning in somebody else's
			// build, as OutOfInput says above.
			#pragma warning disable 0649
			public int Began;
			#pragma warning restore 0649

				/// <summary>
				/// What would have fit at the furthest position, or null. Meaningless unless
				/// the match failed. A reference into one of the generator's own arrays, not
				/// a copy of it.
				/// </summary>
				public string[]? Expected;

				/// <summary>
				/// A second array and beyond, where more than one terminal tied for the
				/// furthest position. Null until an actual tie needs one, and emptied rather
				/// than dropped when the furthest position moves on: a parse that ties once
				/// tends to tie again, and a list per tie was an allocation per operand.
				/// </summary>
				public global::System.Collections.Generic.List<string[]>? ExpectedMore;

				/// <summary>
				/// How many lookaheads the reading is inside. A refusal there is not the parse's —
				/// the look is read and given back whatever it says — so a reader records none
				/// while this is above zero, as the engine records none inside its own lookahead.
				/// </summary>
				// Never written where a grammar's readers hold no lookahead.
				#pragma warning disable 0649
				public int Looking;
				#pragma warning restore 0649

				/// <summary>
				/// Whether nothing reads what this failure would record, so nothing is recorded: a
				/// `find` trying each start, the lexer measuring or valuing a token again.
				/// </summary>
				// Declared for the machines that ask it, and never set where no such reading is
				// emitted — a lexer that measures nothing again, say.
				#pragma warning disable 0649
				public bool Quiet;
				#pragma warning restore 0649
			}

			/// <summary>The ways back still open in a direct parse (Machine.Direct.cs).</summary>
			/// <remarks>
			/// Two integers per way: the alternative in force, and the last one there is. A
			/// way whose two are equal is spent — it stays on the tape so that a replay reads
			/// the same decisions in the same places, and is never taken again.
			/// </remarks>
			sealed class Ways
			{
				internal int[] Items = new int[32];

				/// <summary>How many ways are on the tape.</summary>
				internal int Count;

				/// <summary>The next way a replay reads; equal to <see cref="Count"/> when nothing is being replayed.</summary>
				internal int Cursor;

				/// <summary>
				/// What was recognized, for building values with once the parse has accepted: one
				/// record per completed valued rule, written after its children, each starting
				/// with its own length so that a walk from the front steps from record to record.
				/// </summary>
				internal int[] Log = new int[64];

				/// <summary>How much of the log is written.</summary>
				internal int LogCount;

				/// <summary>How many records the log holds: the number the next one is given.</summary>
				/// <remarks>
				/// A record is named by its number and not by where it was written, so that the
				/// tables the walk builds into are as long as there are records and not as long as
				/// the log. On a real grammar that is four or five times shorter, which is the
				/// difference between a table that fits in the first cache and one that does not.
				/// </remarks>
				internal int Records;

				/// <summary>Which record finished most recently: the number a caller captures.</summary>
				internal int Last = -1;

				/// <summary>
				/// How much of the log the values built for a guard still stand for: a record
				/// below this that was built need not be built again, and one above it was
				/// written since — the log was put back past it and has grown again.
				/// </summary>
				internal int Built;

				/// <summary>
				/// Captures collected while a rule runs and gathered into its record at the end:
				/// three integers each — the slot, and either a record and -1, or a start and end.
				/// </summary>
				internal int[] Refs = new int[48];

				/// <summary>How much of the side stack is in use.</summary>
				internal int RefsCount;

				/// <summary>Where the record being written begins, and which record it is.</summary>
				/// <remarks>
				/// Once it is closed, where the last one begins: a guard asking for the record it just
				/// captured is handed its place without a walk of the log to find it.
				/// </remarks>
				internal int Opened;
				int _number;

				[global::System.ThreadStatic]
				static Ways? _spare;

				/// <summary>Spares below the one slot, for parses reached from inside others; made the first time one is.</summary>
				[global::System.ThreadStatic]
				static Ways?[]? _deeper;

				[global::System.ThreadStatic]
				static int _deeperCount;

				/// <summary>A tape too large for the ordinary slot, kept while the work still wants it.</summary>
				[global::System.ThreadStatic]
				static Ways? _large;

				/// <summary>Parses in a row that did not use the room; at <c>LargeIdle</c> it is let go of.</summary>
				[global::System.ThreadStatic]
				static int _largeIdle;

				/// <summary>And where it goes then: reachable while nothing else wants the memory.</summary>
				[global::System.ThreadStatic]
				static global::System.WeakReference<Ways>? _largeLetGo;

				/// <summary>Parses in a row that left most of the ordinary spare's room unused.</summary>
				[global::System.ThreadStatic]
				static int _spareIdle;

				/// <summary>And where the ordinary spare goes when it has been too big for too long.</summary>
				[global::System.ThreadStatic]
				static global::System.WeakReference<Ways>? _spareLetGo;

				/// <summary>
				/// Eight is a claim, not a taste: if eight parses in a row have not wanted the large
				/// tape, this thread's work has changed and the next parse is unlikely to want it
				/// either. Holding it through a few small parses costs the memory we were holding a
				/// moment ago anyway; holding it through a hundred would be hoarding.
				/// </summary>
				const int LargeIdle = 8;

				/// <summary>The same count for the ordinary slot, read the same way.</summary>
				const int SpareIdle = 8;

				internal static Ways Rent()
				{
					var spare = _spare;

					if (spare != null)
						_spare = null;
					else if (_deeperCount > 0)
					{
						spare = _deeper![--_deeperCount]!;
						_deeper![_deeperCount] = null;
					}
					else if (_large != null)
					{
						spare = _large;
						_large = null;
					}
					else if (_largeLetGo != null && _largeLetGo.TryGetTarget(out var letGo))
					{
						spare = letGo;
						_largeLetGo.SetTarget(null!);
					}
					else if (_spareLetGo != null && _spareLetGo.TryGetTarget(out var letGoSpare))
					{
						spare = letGoSpare;
						_spareLetGo.SetTarget(null!);
					}
					else
						return new Ways();
					spare.Count = 0;
					spare.Cursor = 0;
					spare.LogCount  = 0;
					spare.Records   = 0;
					spare.RefsCount = 0;
					spare.Last      = -1;
					spare.Built     = 0;

					return spare;
				}

				internal static void Return(Ways ways)
				{
					// Bound retained capacity, including an earlier parse's high-water size. Past it
					// the tape is not thrown away — that was a cliff rather than a bound: one entry
					// over and the next parse of a document that size grew everything again from
					// nothing, which cost twenty times the memory of a document a third smaller.
					// It goes to a slot of its own instead, held while the work keeps wanting it
					// (Return, LargeIdle) and let go of by the collector afterwards. Handing it to
					// ArrayPool<T>.Shared instead was considered and is not the same thing: that
					// pool's largest kept array is 2^20 elements, the very number this bound is
					// written in, so it would decline exactly these arrays and "pool it" would mean
					// "drop it" in more words.
					if ((long)ways.Items.Length + ways.Log.Length + ways.Refs.Length > 1048576)
					{
						if (_large != null && !ReferenceEquals(_large, ways))
							(_largeLetGo ??= new global::System.WeakReference<Ways>(_large)).SetTarget(_large);

						// Against what this parse USED, read the same way the bound reads capacity.
						if (ways.Count * 2L + ways.LogCount + ways.RefsCount > 1048576)
							_largeIdle = 0;
						else if (++_largeIdle >= LargeIdle)
						{
							(_largeLetGo ??= new global::System.WeakReference<Ways>(ways)).SetTarget(ways);
							_large = null;
							_largeIdle = 0;

							return;
						}

						_large = ways;

						return;
					}

					// The ordinary slot lets go by the rule the parked one uses, counted where a parse
					// ENDS and against what it used. Room and use are the two sums already written above:
					// every array here is indexed by the same thing, so the bound's capacities and the
					// release's counts are the same quantity twice. Four times and not twice because a
					// table grows to at least double: one doubling is the slack a steady workload leaves,
					// and two is a workload that has shrunk.
					if (!((long)ways.Items.Length + ways.Log.Length + ways.Refs.Length
						> 4L * (ways.Count * 2L + ways.LogCount + ways.RefsCount)))
						_spareIdle = 0;
					else if (++_spareIdle >= SpareIdle)
					{
						(_spareLetGo ??= new global::System.WeakReference<Ways>(ways)).SetTarget(ways);
						_spareIdle = 0;

						return;
					}

					if (_spare == null)
						_spare = ways;
					else if (_deeperCount < 3)
						(_deeper ??= new Ways?[3])[_deeperCount++] = ways;
				}

				/// <summary>Opens a way at the end of the tape, in force at its first alternative.</summary>
				internal int Open(int last) => Open(0, last);

				/// <summary>Opens a way at the end of the tape, in force at <paramref name="at"/>.</summary>
				internal int Open(int at, int last)
				{
					if (Count * 2 + 2 > Items.Length)
						global::System.Array.Resize(ref Items, Items.Length * 2);

					Items[Count * 2]     = at;
					Items[Count * 2 + 1] = last;
					Count++;
					Cursor = Count;

					return Count - 1;
				}

				/// <summary>
				/// Takes the latest way decided since <paramref name="segment"/> that still has an
				/// alternative left, drops everything decided after it, and sets the replay to
				/// begin at the segment. False when none is left, and then nothing moves.
				/// </summary>
				/// <remarks>
				/// Only what stands before the cursor is the construct's own. During a replay the
				/// tape past the cursor is the future — decisions of what comes after, waiting to
				/// be read again — and a construct that fails on the way there, exactly as it did
				/// the first time, must leave that future alone.
				/// </remarks>
				internal bool Retry(int segment)
				{
					for (var way = Cursor - 1; way >= segment; way--)
					{
						if (Items[way * 2] < Items[way * 2 + 1])
						{
							Items[way * 2]++;
							Count  = way + 1;
							Cursor = segment;

							return true;
						}
					}

					return false;
				}

				/// <summary>
				/// Moves a way on to its next alternative once the one in force is spent, and
				/// drops what that alternative decided: the next one starts from nothing.
				/// </summary>
				internal void Next(int way, int value)
				{
					Items[way * 2] = value;
					Count  = way + 1;
					Cursor = way + 1;
				}

				/// <summary>
				/// <see cref="Next(int, int)"/>, and the way now reaches <paramref name="last"/>:
				/// as far as the alternative it moved to could be mended from.
				/// </summary>
				internal void Next(int way, int value, int last)
				{
					Items[way * 2]     = value;
					Items[way * 2 + 1] = last;
					Count  = way + 1;
					Cursor = way + 1;
				}

				/// <summary>Spends every way decided since the segment, keeping its decision.</summary>
				internal void Seal(int segment)
				{
					for (var way = segment; way < Cursor; way++)
						Items[way * 2 + 1] = Items[way * 2];
				}

				/// <summary>
				/// Opens a record: its length is written when it ends.
				/// </summary>
				/// <remarks>
				/// One number says which rule wrote it and which of that rule's alternatives,
				/// because the walk at the end wants both together and asking twice cost a
				/// switch inside a switch — two jump tables where a record needs one.
				/// </remarks>
				/// <summary>
				/// Opens a record that stands nowhere in particular: where nothing a machine
				/// builds is a span of the input, and no factory it runs asks where it read,
				/// the two positions are two integers written and never looked at.
				/// </summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void Begin(int arm)
				{
					if (LogCount + 2 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 2);

					Opened = LogCount;
					_number = Records++;
					Log[LogCount++] = 0;
					Log[LogCount++] = arm;
				}

				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void Begin(int arm, int start, int end)
				{
					if (LogCount + 4 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 4);

					Opened = LogCount;
					_number = Records++;
					Log[LogCount++] = 0;
					Log[LogCount++] = arm;
					Log[LogCount++] = start;
					Log[LogCount++] = end;
				}

				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void Put(int value)
				{
					if (LogCount + 1 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 1);

					Log[LogCount++] = value;
				}

				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void Put(int a, int b)
				{
					if (LogCount + 2 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 2);

					Log[LogCount++] = a;
					Log[LogCount++] = b;
				}

				/// <summary>Closes the record: its length goes in front, and it becomes the last.</summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void End(int refs)
				{
					Log[Opened] = LogCount - Opened;
					Last         = _number;
					RefsCount    = refs;
				}

				/// <summary>
				/// The record closed, and named by where it stands rather than by its number:
				/// an extent is the one thing whose value is the record itself, read straight
				/// out of the log by whoever captured it, and never put in a table.
				/// </summary>
				[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
				internal void EndAt(int refs)
				{
					Log[Opened] = LogCount - Opened;
					Last         = Opened;
					RefsCount    = refs;
				}

				/// <summary>
				/// A mark placed or taken away (docs/syntax.md §7.8): a record of its own in the
				/// log, so that what was put back with the log takes its marks with it. The kind
				/// is -1 where the mark opens and -2 where it closes; nothing captures one.
				/// </summary>
				internal void Mark(int kind, int site, int at)
				{
					if (LogCount + 5 > Log.Length)
						global::System.Array.Resize(ref Log, Log.Length * 2 + 5);

					Records++;

					Log[LogCount++] = 5;
					Log[LogCount++] = kind;
					Log[LogCount++] = site;
					Log[LogCount++] = at;
					Log[LogCount++] = at;
				}

				/// <summary>A capture made inside a repetition, kept until the rule gathers it.</summary>
				internal void Push(int slot, int a, int b)
				{
					if (RefsCount + 3 > Refs.Length)
						global::System.Array.Resize(ref Refs, Refs.Length * 2 + 3);

					Refs[RefsCount++] = slot;
					Refs[RefsCount++] = a;
					Refs[RefsCount++] = b;
				}

				/// <summary>
				/// Writes what was pushed for the given slots since <paramref name="from"/>: how
				/// many, then each one — the record alone where <paramref name="pairs"/> is false,
				/// the start and end where it is true.
				/// </summary>
				internal void Collect(int from, long slots, bool pairs)
				{
					var count = 0;

					for (var at = from; at < RefsCount; at += 3)
						if ((slots & (1L << Refs[at])) != 0)
							count++;

					Put(count);

					for (var at = from; at < RefsCount; at += 3)
						if ((slots & (1L << Refs[at])) != 0)
						{
							if (pairs)
								Put(Refs[at + 1], Refs[at + 2]);
							else
								Put(Refs[at + 1]);
						}
				}
			}

			/// <summary>Records a refusal against the furthest one seen, as the engine's Fail does.</summary>
			static void Refuse_DotGram(ref Failure failure, int at, string[]? expected)
			{
				if (failure.Looking > 0)
					return;

				if (at > failure.Position)
				{
					failure.Position     = at;
					failure.Expected     = expected;
					failure.ExpectedMore?.Clear();
				}
				else if (at == failure.Position && expected != null && !ReferenceEquals(expected, failure.Expected))
				{
					// The same set said twice is one thing wanted, not two. A rule refused at the
					// furthest position by several of its alternatives says the same set from
					// each, and a message listing it once is the message; a list holding it
					// several times is a list that grew on a parse that went on to succeed.
					var more = failure.ExpectedMore;

					if (more == null)
						failure.ExpectedMore = more = new global::System.Collections.Generic.List<string[]>();
					else if (more.Count > 0 && ReferenceEquals(more[more.Count - 1], expected))
						return;

					more.Add(expected);
				}
			}

			/// <summary>
			/// Records what a choice wanted where the call that begins its widest group refused at the
			/// same place: that call's own set, which the choice's holds, is dropped for it.
			/// </summary>
			static void Refuse_DotGram_Over(ref Failure failure, int at, string[] expected, string[] covered)
			{
				if (failure.Looking > 0)
					return;

				if (at == failure.Position)
				{
					if (ReferenceEquals(failure.Expected, covered))
						failure.Expected = expected;

					failure.ExpectedMore?.Remove(covered);
				}

				Refuse_DotGram(ref failure, at, expected);
			}

			/// <summary>How much of a run matched, asked only when it did not.</summary>
			static int Reach_DotGram(
				global::System.ReadOnlySpan<char> text, int pos, global::System.ReadOnlySpan<char> want)
			{
				var room = text.Length - pos;

				if (want.Length < room)
					room = want.Length;

				var at = 0;

				while (at < room && text[pos + at] == want[at])
					at++;

				return pos + at;
			}

			/// <summary>The stacks used by immediate readers in this class (Machine.Immediate.cs).</summary>
			sealed class ImmediateValues
			{
				internal int[] Stack0 = new int[8];
				internal int Count0;
				internal int High0;

				internal void Push0(int item)
				{
					if (Count0 == Stack0.Length)
						global::System.Array.Resize(ref Stack0, Count0 * 2);

					Stack0[Count0++] = item;

					if (Count0 > High0) High0 = Count0;
				}

				/// <summary>What was pushed since the mark, as one array, and the stack back at the mark.</summary>
				internal int[] Take0(int from)
				{
					var taken = Peek0(from);

					Count0 = from;

					return taken;
				}

				/// <summary>What was pushed since the mark, as one array, the stack left as it is.</summary>
				internal int[] Peek0(int from)
				{
					var count = Count0 - from;

					if (count == 0)
						return global::System.Array.Empty<int>();

					var taken = new int[count];

					global::System.Array.Copy(Stack0, from, taken, 0, count);

					return taken;
				}


				[global::System.ThreadStatic]
				static ImmediateValues? _spare;

				/// <summary>Spares below the one slot, for parses reached from inside others; made the first time one is.</summary>
				[global::System.ThreadStatic]
				static ImmediateValues?[]? _deeper;

				[global::System.ThreadStatic]
				static int _deeperCount;

				/// <summary>A store past the bound, kept while this thread's work still wants it.</summary>
				[global::System.ThreadStatic]
				static ImmediateValues? _large;

				/// <summary>Parses in a row that did not use the room; at <c>LargeIdle</c> it is let go of.</summary>
				[global::System.ThreadStatic]
				static int _largeIdle;

				/// <summary>And where it goes then: reachable until the memory is wanted elsewhere.</summary>
				[global::System.ThreadStatic]
				static global::System.WeakReference<ImmediateValues>? _largeLetGo;

				/// <summary>Parses in a row that left most of the ordinary spare's room unused.</summary>
				[global::System.ThreadStatic]
				static int _spareIdle;

				/// <summary>And where the ordinary spare goes when it has been too big for too long.</summary>
				[global::System.ThreadStatic]
				static global::System.WeakReference<ImmediateValues>? _spareLetGo;

				/// <summary>
				/// Eight is a claim rather than a taste: if eight parses in a row have not wanted
				/// the room a slot holds - the large store, or an ordinary spare far bigger than
				/// the parses that keep coming - this thread's work has changed and the next parse is unlikely
				/// to want it either. Carrying it through a few small parses costs the memory this
				/// thread held a moment ago anyway; carrying it through a hundred would be hoarding.
				///
				/// Counted where a parse ENDS, against what that parse USED. At the rental it
				/// could never arrive: a rental that takes the kept store zeroes the count, and
				/// with no ordinary spare - the state right after a large parse - every rental
				/// takes it. Against CAPACITY it could never arrive either: a store comes back
				/// as large as it was grown, whatever the document was.
				/// </summary>
				const int LargeIdle = 8;

				/// <summary>The same count for the ordinary slot, read the same way.</summary>
				const int SpareIdle = 8;

				internal static ImmediateValues Rent()
				{
					var spare = _spare;

					if (spare != null)
						_spare = null;
					else if (_deeperCount > 0)
					{
						spare = _deeper![--_deeperCount]!;
						_deeper![_deeperCount] = null;
					}
					else if (_large != null)
					{
						spare = _large;
						_large = null;
					}
					else if (_largeLetGo != null && _largeLetGo.TryGetTarget(out var letGo))
					{
						spare = letGo;
						_largeLetGo.SetTarget(null!);
					}
					else if (_spareLetGo != null && _spareLetGo.TryGetTarget(out var letGoSpare))
					{
						spare = letGoSpare;
						_spareLetGo.SetTarget(null!);
					}
					else
						return new ImmediateValues();

					return spare;
				}

				internal static void Return(ImmediateValues values)
				{
					var used = 0L + values.High0;

					if (values.High0 > 0)
					{
						global::System.Array.Clear(values.Stack0, 0, values.High0);
						values.Count0 = values.High0 = 0;
					}


					// Past the bound the store is not thrown away - that was a cliff
					// and not a bound - it is kept while the work keeps wanting it, and handed
					// to the collector once it stops (CSharpEmitter.Outsized). It is emptied
					// first, above: what is kept is the room, never what was built in it.
					if (0L + values.Stack0.Length > 1048576)
					{
						// Against what this parse USED, not what the store holds: capacity does not
						// shrink because a document was small, so a count against it would reset here
						// every time and never arrive. Eight parses that did not use the room and it
						// stops being held strongly - the borrower is what demotes it.
						if (used > 1048576)
							_largeIdle = 0;
						else if (++_largeIdle >= LargeIdle)
						{
							(_largeLetGo ??= new global::System.WeakReference<ImmediateValues>(values)).SetTarget(values);
							_large = null;
							_largeIdle = 0;

							return;
						}

						if (_large != null && !ReferenceEquals(_large, values))
							(_largeLetGo ??= new global::System.WeakReference<ImmediateValues>(_large)).SetTarget(_large);

						_large = values;

						return;
					}

					// The ordinary slot lets go by the same rule as the parked one: counted where a
					// parse ENDS, against what that parse USED. At the rental it could not arrive,
					// for the reason written above LargeIdle. And it is let go of WEAKLY, so a thread that
					// wants the room straight back still gets it, while one that does not has stopped
					// holding it against everybody else.
					if (!(0L + values.Stack0.Length > 4L * used))
						_spareIdle = 0;
					else if (++_spareIdle >= SpareIdle)
					{
						(_spareLetGo ??= new global::System.WeakReference<ImmediateValues>(values)).SetTarget(values);
						_spareIdle = 0;

						return;
					}

					if (_spare == null)
						_spare = values;
					else if (_deeperCount < 3)
						(_deeper ??= new ImmediateValues?[3])[_deeperCount++] = values;
				}

				/// <summary>Whether a local a record would have been kept in was never written.</summary>
				internal static bool IsDefault<T>(T value) => global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(value, default!);
			}

		}
	}
}
