"""Generate FIX 4.4 grammar and public message types from pinned Orchestra XML."""
from pathlib import Path
import json
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/DotGram.Finance/Fix"
NS = {"r": "http://fixprotocol.io/2020/orchestra/repository"}
repo = ET.parse(OUT / "Specification/OrchestraFIX44.xml").getroot()
fields = {int(x.attrib["id"]): x for x in repo.findall("r:fields/r:field", NS)}
components = {int(x.attrib["id"]): x for x in repo.findall("r:components/r:component", NS)}
groups = {int(x.attrib["id"]): x for x in repo.findall("r:groups/r:group", NS)}
messages = repo.findall("r:messages/r:message", NS)
codes = {x.attrib["name"]: x for x in repo.findall("r:codeSets/r:codeSet", NS)}


def write(name, text):
	path = OUT / name
	data = ("\ufeff" if path.suffix == ".cs" else "").encode() + (text.rstrip() + "\n").replace("\n", "\r\n").encode()
	if not path.exists() or path.read_bytes() != data: path.write_bytes(data)


def kind(element):
	return element.tag.rsplit("}", 1)[-1]


def refs(element):
	return [x for x in element if kind(x) in ("fieldRef", "componentRef", "groupRef")]


def flatten(element):
	result = []
	for x in refs(element):
		i = int(x.attrib["id"])
		if kind(x) == "componentRef":
			result.extend(flatten(components[i]))
		else:
			result.append(("G" if kind(x) == "groupRef" else "F", i))
	return result


def tag(item):
	k, i = item
	return int(groups[i].find("r:numInGroup", NS).attrib["id"]) if k == "G" else i


def field_type(field):
	t = field.attrib["type"]
	return codes[t].attrib["type"] if t in codes else t


header_items = flatten(components[1024])
header_tags = {tag(x) for x in header_items}
trailer_tags = {tag(x) for x in flatten(components[1025])}
reachable_groups = set()


def visit(items):
	for k, i in items:
		if k == "G" and i not in reachable_groups:
			reachable_groups.add(i)
			visit(flatten(groups[i]))


for m in messages:
	visit(flatten(m.find("r:structure", NS)))
model = ["// <auto-generated />", "#nullable enable", "using System;", "using System.Collections.Generic;", "", "namespace DotGram.Finance;", ""]
for m in messages:
	i, name, mt = m.attrib["id"], m.attrib["name"], m.attrib["msgType"]
	items = [x for x in flatten(m.find("r:structure", NS)) if tag(x) not in header_tags | trailer_tags]
	model += [f"/// <summary>FIX 4.4 {name}, MsgType {mt}.</summary>", f"public sealed class {name} : FixMessage", "{",
		f"\tinternal {name}(string source, FixNode[] header, FixNode[] body, FixNode[] trailer)",
		f'\t\t: base(source, "{mt}", header, body, trailer)',
		"\t{", "\t}", ""]
	seen = set()
	for item in items:
		t = tag(item)
		f = fields[t]
		prop = f.attrib["name"]
		if prop in seen:
			continue
		seen.add(prop)
		if item[0] == "G":
			group_name = groups[item[1]].attrib['name']
			model.append(f"\tpublic IReadOnlyList<{group_name}Entry> {group_name} => GetTypedGroup<{group_name}Entry>({t});")
		elif field_type(f) in ("int", "Length", "NumInGroup", "SeqNum", "TagNum", "DayOfMonth", "float", "Qty", "Price", "PriceOffset", "Amt", "Percentage"):
			model.append(f"\tpublic FixNumber? {prop} => GetNumber({t});")
		else:
			model.append(f"\tpublic string? {prop} => GetText({t});")
	model += ["}", ""]
for name, items in [(g.attrib["name"] + "Entry", flatten(g)) for g in groups.values()] + [("StandardHeader", header_items), ("StandardTrailer", flatten(components[1025]))]:
	model += [f"/// <summary>FIX 4.4 {name} field scope.</summary>", f"public sealed class {name} : FixFieldSet", "{", f"\tinternal {name}(string source, FixNode[] fields)", "\t\t: base(source, fields)", "\t{", "\t}", ""]
	seen = set()
	for item in items:
		t = tag(item)
		f = fields[t]
		prop = f.attrib["name"]
		if prop in seen: continue
		seen.add(prop)
		if item[0] == "G":
			group_name = groups[item[1]].attrib["name"]
			model.append(f"\tpublic IReadOnlyList<{group_name}Entry> {group_name} => GetTypedGroup<{group_name}Entry>({t});")
		elif field_type(f) in ("int", "Length", "NumInGroup", "SeqNum", "TagNum", "DayOfMonth", "float", "Qty", "Price", "PriceOffset", "Amt", "Percentage"):
			model.append(f"\tpublic FixNumber? {prop} => GetNumber({t});")
		else:
			model.append(f"\tpublic string? {prop} => GetText({t});")
	model += ["}", ""]
write("Messages.Generated.cs", "\n".join(model))
inventory = {
	"version": repo.attrib["version"],
	"counts": {"messages": len(messages), "fields": len(fields), "components": len(components), "groups": len(groups), "codeSets": len(codes)},
	"messages": [{"name": m.attrib["name"], "msgType": m.attrib["msgType"]} for m in messages],
	"lengthDataPairs": [{"lengthTag": int(f.attrib["lengthId"]), "dataTag": i} for i, f in fields.items() if "lengthId" in f.attrib],
}
write("Specification/inventory.json", json.dumps(inventory, indent="\t"))
print(inventory["counts"])


def schema_array(name, element, display_name=None):
	"""Keep each schema member on its own line, with the dictionary name beside it."""
	display_name = display_name or element.attrib["name"]
	lines = [f"\t// {display_name}", f"\tstatic readonly SchemaRef[] {name} =", "\t{"]
	for reference in refs(element):
		number = int(reference.attrib["id"])
		required = str(reference.attrib.get("presence") == "required").lower()
		reference_kind = kind(reference)
		kind_number, dictionary = {
			"fieldRef": (0, fields),
			"componentRef": (1, components),
			"groupRef": (2, groups),
		}[reference_kind]
		member_name = dictionary[number].attrib["name"]
		lines.append(f"\t\tnew SchemaRef({number}, {required}, {kind_number}), // {member_name}")
	lines.extend(["\t};", ""])
	return lines


schema = [
	"// <auto-generated />",
	"#nullable enable",
	"using System;",
	"",
	"namespace DotGram.Finance;",
	"",
	"static class FixSchema",
	"{",
]
for label, dictionary in [("C", components), ("G", groups)]:
	for number, element in dictionary.items():
		schema.extend(schema_array(f"{label}{number}", element))
for message in messages:
	structure = message.find("r:structure", NS)
	name = "M" + message.attrib["id"]
	schema.extend(schema_array(name, structure, message.attrib["name"]))
schema += ["\tpublic static SchemaRef[] Component(int id) => id switch", "\t{"]
schema += [f"\t\t{i} => C{i}," for i in components]
schema += ['\t\t_ => throw new InvalidOperationException("Unknown component."),', "\t};", "", "\tpublic static SchemaRef[] Group(int id) => id switch", "\t{"]
schema += [f"\t\t{i} => G{i}," for i in groups]
schema += ['\t\t_ => throw new InvalidOperationException("Unknown group."),', "\t};", "", "\tpublic static SchemaRef[] Message(string type) => type switch", "\t{"]
schema += [f'\t\t"{m.attrib["msgType"]}" => M{m.attrib["id"]},' for m in messages]
schema += ["\t\t_ => Array.Empty<SchemaRef>(),", "\t};", "", "\tpublic static int Counter(int group) => group switch", "\t{"]
schema += [f'\t\t{i} => {g.find("r:numInGroup", NS).attrib["id"]},' for i, g in groups.items()]
schema += ["\t\t_ => 0,", "\t};", "", "\tpublic static int LengthTag(int dataTag) => dataTag switch", "\t{"]
schema += [f'\t\t{i} => {f.attrib["lengthId"]},' for i, f in fields.items() if "lengthId" in f.attrib]
schema += ["\t\t_ => 0,", "\t};", "", "\tpublic static int DataTag(int lengthTag) => lengthTag switch", "\t{"]
schema += [f'\t\t{f.attrib["lengthId"]} => {i},' for i, f in fields.items() if "lengthId" in f.attrib]
schema += ["\t\t_ => 0,", "\t};", "", "\tpublic static string? Type(int tag) => tag switch", "\t{"]
schema += [f'\t\t{i} => "{field_type(f)}",' for i, f in fields.items()]
schema += ["\t\t_ => null,", "\t};"]
for name, code_set in codes.items():
	schema.extend(["", f"\tstatic readonly string[] {name} =", "\t{"])
	for code in code_set.findall("r:code", NS):
		value = json.dumps(code.attrib["value"])
		code_name = code.attrib["name"]
		schema.append(f"\t\t{value}, // {code_name}")
	schema.append("\t};")
schema.append("")
schema += ["\tpublic static string[]? Codes(int tag) => tag switch", "\t{"]
schema += [f'\t\t{i} => {f.attrib["type"]},' for i, f in fields.items() if f.attrib["type"] in codes]
schema += ["\t\t_ => null,", "\t};", "", "\tpublic static bool RequiresEncoding(int tag) => tag switch", "\t{"]
schema += [f'\t\t{i} => true,' for i, f in fields.items() if f.attrib["name"].startswith("Encoded") and f.attrib["type"] == "data"]
schema += ["\t\t_ => false,", "\t};", "}"]
write("Schema.Generated.cs", "\n".join(schema))

# Runtime factories accompany the schema; group structure is interpreted once by
# the shared semantic assembler instead of compiled into each message parser.
factories = ["// <auto-generated />", "#nullable enable", "using System;", "using System.Collections.Generic;", "", "namespace DotGram.Finance;", "", "static class FixFactories", "{"]
factories += ["\tpublic static FixMessage Message(string type, string source, FixNode[] header, FixNode[] body, FixNode[] trailer) => type switch", "\t{"]
for m in messages:
	factories.append(f'\t\t"{m.attrib["msgType"]}" => new {m.attrib["name"]}(source, header, body, trailer),')
factories += ["\t\t_ => new CustomFixMessage(source, type, header, body, trailer),", "\t};", "", "\tpublic static IReadOnlyList<FixFieldSet> Group(int id, string source, List<FixNode[]> entries)", "\t{", "\t\tswitch (id)", "\t\t{"]
for i, g in groups.items():
	name = g.attrib["name"] + "Entry"
	factories += [f"\t\t\tcase {i}:", "\t\t\t{", f"\t\t\t\tvar result = new {name}[entries.Count];", "\t\t\t\tfor (var n = 0; n < result.Length; n++)", f"\t\t\t\t\tresult[n] = new {name}(source, entries[n]);", "", "\t\t\t\treturn Array.AsReadOnly(result);", "\t\t\t}", ""]
factories += ['\t\t\tdefault:', '\t\t\t\tthrow new InvalidOperationException("Unknown FIX group.");', "\t\t}", "\t}", "}"]
write("Factories.Generated.cs", "\n".join(factories))



# One field grammar. The specification supplies both each numeric tag and its
# primitive type; message and group membership belongs to FixSemantics.
primitive = {
	"int": ("System.Numerics.BigInteger", "Integer"), "Length": ("System.Numerics.BigInteger", "Integer"),
	"NumInGroup": ("System.Numerics.BigInteger", "Integer"), "SeqNum": ("System.Numerics.BigInteger", "Integer"),
	"TagNum": ("System.Numerics.BigInteger", "Integer"), "DayOfMonth": ("System.Numerics.BigInteger", "Integer"),
	"float": ("FixDecimal", "Decimal"), "Qty": ("FixDecimal", "Decimal"), "Price": ("FixDecimal", "Decimal"),
	"PriceOffset": ("FixDecimal", "Decimal"), "Amt": ("FixDecimal", "Decimal"), "Percentage": ("FixDecimal", "Decimal"),
	"Boolean": ("bool", "Boolean"), "char": ("char", "Character"), "data": ("ReadOnlyMemory<byte>", "Data"),
	"UTCTimestamp": ("FixTimestamp", "Timestamp"), "UTCTimeOnly": ("FixTime", "Time"),
	"UTCDateOnly": ("FixDate", "Date"), "LocalMktDate": ("FixDate", "Date"), "MonthYear": ("FixMonthYear", "MonthYear"),
	"MultipleValueString": ("string[]", "Multiple"),
}
def generate_fields():
	"""Emit declarations only; parsing policy and field behavior are handwritten."""
	adt = [
		"// <auto-generated />",
		"// Generated from the pinned Orchestra FIX 4.4 dictionary.",
		"using System;",
		"using System.Numerics;",
		"",
		"namespace DotGram.Finance;",
		"",
		"public abstract partial class FixField",
		"{",
	]
	grammar = [
		"// Generated by tools/generate-fix44.py from the pinned Orchestra FIX 4.4 dictionary.",
		"// Reading policy is supplied by the handwritten Fix44Grammar.gram.",
		"@using DotGram.Finance;",
		"",
	]
	grammar.append("KnownField(text) : @FixField =")
	index = 0
	paired_lengths = {int(f.attrib["lengthId"]) for f in fields.values() if "lengthId" in f.attrib}
	for number, field in fields.items():
		name = field.attrib["name"]
		fix_type = field_type(field)
		cs_type, conversion = primitive.get(fix_type, ("string", "Text"))
		cs_type = cs_type.replace("System.Numerics.", "")
		argument = f"{cs_type} value" if conversion == "Text" else f"(bool Valid, {cs_type} Value) value"
		adt.extend([
			f"\t/// <summary>FIX {number}: {name} ({fix_type}).</summary>",
			f"\tpublic sealed class {name}({argument})",
			f"\t\t: FixField<{cs_type}>({number}, value);",
			"",
		])
		if fix_type == "data" or number in paired_lengths:
			continue
		content = "text"
		grammar.extend([
			f"\t// {number}: {name} ({fix_type})",
			f'\t{"" if index == 0 else "| "}{{ "{number}=" & value: {content} }}',
			f"\t  => @(new FixField.{name}(FixConvert.{conversion}(value)))",
			"",
		])
		index += 1
	adt[-1] = "}"
	write("FixField.Generated.cs", "\n".join(adt))
	write(ROOT / "examples/DotGram.Examples/Finance/Fix44/FixField.gram", "\n".join(grammar))


generate_fields()


def generate_dispatch_factory():
	"""Typed field construction for the production computed-dispatch parser."""
	lines = ["// <auto-generated />", "// Generated from the pinned Orchestra FIX 4.4 dictionary.",
		"using System;", "", "namespace DotGram.Finance;", "", "static class FixFactory", "{"]
	buckets = sorted({number // 64 for number in fields})
	for domain in ("char", "byte"):
		lines += [f"\tpublic static FixField Value(int tag, ReadOnlySpan<{domain}> value) => (tag / 64) switch", "\t{"]
		lines += [f"\t\t{bucket} => Part{bucket}(tag, value)," for bucket in buckets]
		lines += ["\t\t_ => new FixField.Unknown(tag, FixConvert.Data(value)),", "\t};", ""]
		for bucket in buckets:
			lines += [f"\tstatic FixField Part{bucket}(int tag, ReadOnlySpan<{domain}> value) => tag switch", "\t{"]
			for number, field in fields.items():
				if number // 64 != bucket: continue
				conversion = primitive.get(field_type(field), ("string", "Text"))[1]
				lines += [f"\t\t{number} => new FixField.{field.attrib['name']}(FixConvert.{conversion}(value)),"]
			lines += ["\t\t_ => new FixField.Unknown(tag, FixConvert.Data(value)),", "\t};", ""]
	lines += ["\tpublic static FixField Binary(int tag, (bool Valid, ReadOnlyMemory<byte> Value) value) => tag switch", "\t{"]
	for number, field in fields.items():
		if field_type(field) == "data": lines += [f"\t\t{number} => new FixField.{field.attrib['name']}(value),"]
	lines += ["\t\t_ => new FixField.Unknown(tag, value),", "\t};", "}"]
	write("FixFactory.Generated.cs", "\n".join(lines))


generate_dispatch_factory()


def sample_field(i):
	f = fields[i]
	t = field_type(f)
	if f.attrib["type"] in codes:
		return codes[f.attrib["type"]].find("r:code", NS).attrib["value"]
	return {"String": "X", "char": "X", "Boolean": "N", "Currency": "USD", "Country": "US", "Exchange": "XNAS", "MonthYear": "202609", "UTCTimestamp": "20260915-12:00:00", "UTCTimeOnly": "12:00:00", "UTCDateOnly": "20260915", "LocalMktDate": "20260915", "data": "X", "MultipleValueString": "X"}.get(t, "1")


def sample_structure(element, force_first=False, required_component=False, full=False):
	result = []
	children = refs(element)
	for index, x in enumerate(children):
		i = int(x.attrib["id"])
		if not full and x.attrib.get("presence") != "required" and not (force_first and index == 0):
			continue
		if kind(x) == "componentRef":
			if i not in (1024, 1025):
				result.extend(sample_structure(components[i], required_component=True, full=full))
		elif kind(x) == "groupRef":
			result.append((tag(("G", i)), "1"))
			result.extend(sample_structure(groups[i], force_first=True, full=full))
		else:
			result.append((i, sample_field(i)))
	if required_component and not result:
		return sample_structure(element, force_first=True)
	return result


fixtures = []
for m, full in [(m, full) for m in messages for full in (False, True)]:
	mt = m.attrib["msgType"]
	body = f"35={mt}\x0149=SENDER\x0156=TARGET\x0134=1\x0152=20260915-12:00:00\x01"
	if full:
		body = f"35={mt}\x01" + "".join(f"{i}={v}\x01" for i, v in sample_structure(components[1024], full=True) if i not in (8, 9, 35))
	body += "".join(f"{i}={v}\x01" for i, v in sample_structure(m.find("r:structure", NS), full=full))
	if full: body += "93=1\x0189=X\x01"
	wire = f"8=FIX.4.4\x019={len(body)}\x01{body}"
	wire += f"10={sum(map(ord, wire)) % 256:03}\x01"
	fixtures.append({"name": m.attrib["name"], "wire": wire})
(ROOT / "tests/DotGram.Finance.Tests/Fixtures.json").write_bytes((json.dumps(fixtures, indent="\t") + "\n").replace("\n", "\r\n").encode())
