"""Generate FIX 4.4 grammar and public message types from pinned Orchestra XML."""
from pathlib import Path
import json
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src/DotGram.Finance/Fix/Fix44"
NS = {"r": "http://fixprotocol.io/2020/orchestra/repository"}
repo = ET.parse(OUT / "Specification/OrchestraFIX44.xml").getroot()
fields = {int(x.attrib["id"]): x for x in repo.findall("r:fields/r:field", NS)}
components = {int(x.attrib["id"]): x for x in repo.findall("r:components/r:component", NS)}
groups = {int(x.attrib["id"]): x for x in repo.findall("r:groups/r:group", NS)}
messages = repo.findall("r:messages/r:message", NS)
codes = {x.attrib["name"]: x for x in repo.findall("r:codeSets/r:codeSet", NS)}


def write(name, text):
	path = OUT / name
	data = ("\ufeff" if path.suffix == ".cs" else "").encode() + (text.rstrip() + "\n").replace("\n", "\r\n").encode()
	if not path.exists() or path.read_bytes() != data: path.write_bytes(data)


def kind(element):
	return element.tag.rsplit("}", 1)[-1]


def refs(element):
	return [x for x in element if kind(x) in ("fieldRef", "componentRef", "groupRef")]


def flatten(element):
	result = []
	for x in refs(element):
		i = int(x.attrib["id"])
		if kind(x) == "componentRef":
			result.extend(flatten(components[i]))
		else:
			result.append(("G" if kind(x) == "groupRef" else "F", i))
	return result


def tag(item):
	k, i = item
	return int(groups[i].find("r:numInGroup", NS).attrib["id"]) if k == "G" else i


def field_type(field):
	t = field.attrib["type"]
	return codes[t].attrib["type"] if t in codes else t


header_items = flatten(components[1024])
header_tags = {tag(x) for x in header_items}
trailer_tags = {tag(x) for x in flatten(components[1025])}
reachable_groups = set()


def visit(items):
	for k, i in items:
		if k == "G" and i not in reachable_groups:
			reachable_groups.add(i)
			visit(flatten(groups[i]))


for m in messages:
	visit(flatten(m.find("r:structure", NS)))
gram = ["// Generated by tools/generate-fix44.py; do not edit.",
	"@using DotGram.Finance.Fix;", "context : @FixContext", "",
	"Text : @SourceSpan = [^ '\\u0001']+",
	"Digits : @SourceSpan = ['0'..'9']+",
	"Data : @SourceSpan = @ReadData", ""]
for i, f in fields.items():
	value = "Data" if f.attrib["type"] == "data" else "Text"
	gram.append(f'F{i} : @FixNode = {{ "{i}=" & v: {value} & \'\\u0001\' }} => @(new FixNode({i}, parserSpan.Start, v.Start, v.Length))')
gram += ["", "Unknown : @FixNode = v: UnknownData => @(v) | v: UnknownText => @(v)",
	"UnknownText : @FixNode = t: Digits & when @(context.IsExtension(t.Start, t.Length)) & '=' & v: Text & '\\u0001' => @(new FixNode(context.TagAt(t.Start, t.Length), parserSpan.Start, v.Start, v.Length))",
	"UnknownData : @FixNode = t: Digits & when @(context.IsExtensionData(t.Start, t.Length)) & '=' & v: Data & '\\u0001' => @(new FixNode(context.TagAt(t.Start, t.Length), parserSpan.Start, v.Start, v.Length))", ""]
for i, group in groups.items():
	if i not in reachable_groups:
		continue
	items = flatten(group)
	if not items:
		raise ValueError(f"Empty group {i}")
	count = int(group.find("r:numInGroup", NS).attrib["id"])
	first = items[0][0] + str(items[0][1])
	remaining = [k + str(n) for k, n in items[1:]] + ["Unknown"]
	entry_type = group.attrib["name"] + "Entry"
	gram += [f'G{i} : @FixNode = {{ count: F{count} & when @(context.BeginGroup(count)) & entries: L{i} & when @(context.EndGroup()) }} => @(count.WithEntries(entries))',
		f'L{i} : @{entry_type}[] = {{ E{i}* }}',
		f'E{i} : @{entry_type} = fields: V{i} => @(new {entry_type}(context.Source, fields))',
		f'R{i} : @FixNode = ' + ' | '.join(f'v: {x} => @(v)' for x in remaining),
		f'V{i} : @FixNode[] = {{ when @(context.HasEntry) & {first} & when @(context.ConsumeEntry()) & R{i}* }}', ""]
header_rest = " | ".join(k + str(i) for k, i in header_items if tag((k, i)) not in (8, 9, 35))
gram += [f"HeaderRest : @FixNode[] = ({header_rest})*", "Trailer : @FixNode[] = F93? & F89? & F10", "Header : @FixNode[] = begin: F8 & length: F9 & type: MessageType & rest: HeaderRest => @(FixContext.Header(begin, length, type, rest))", "MessageType : @FixNode = f: F35 & when @(context.SetMessageType(f)) => @(f)", ""]
model = ["// <auto-generated />", "#nullable enable", "using System;", "using System.Collections.Generic;", "", "namespace DotGram.Finance.Fix;", ""]
hosts = ["// <auto-generated />", "using System;", "using DotGram;", "namespace DotGram.Finance.Fix;", ""]
for m in messages:
	i, name, mt = m.attrib["id"], m.attrib["name"], m.attrib["msgType"]
	items = [x for x in flatten(m.find("r:structure", NS)) if tag(x) not in header_tags | trailer_tags]
	needed = {"Text", "Digits", "Data", "Unknown", "UnknownText", "UnknownData", "Header", "HeaderRest", "MessageType", "Trailer"}

	def need(items):
		for k, n in items:
			key = k + str(n)
			if key in needed:
				continue
			needed.add(key)
			if k == "G":
				needed.update({f"E{n}", f"V{n}", f"R{n}", f"L{n}", f"F{tag((k, n))}"})
				need(flatten(groups[n]))

	regular_body = [n for k, n in items if k == "F" and fields[n].attrib["type"] != "data"]
	special_body = [(k, n) for k, n in items if k == "G" or fields[n].attrib["type"] == "data"]
	need(special_body + header_items + flatten(components[1025]))
	alts = " | ".join(k + str(n) for k, n in items)
	if alts:
		alts += " | "
	choices = [k + str(n) for k, n in special_body] + (["BodyField"] if regular_body else []) + ["Unknown"]
	message_grammar = [line for line in gram if not line or line.startswith(("//", "@", "context")) or line.split(" ", 1)[0] in needed]
	if regular_body:
		message_grammar += ['BodyTag : @SourceSpan = { ' + ' | '.join(f'"{n}="' for n in sorted(set(regular_body))) + ' }',
			"BodyField : @FixNode = t: BodyTag & v: Text & '\\u0001' => @(new FixNode(context.TagAt(t.Start, t.Length - 1), parserSpan.Start, v.Start, v.Length))"]
	message_grammar += [f'Item : @FixNode = ' + ' | '.join(f'v: {x} => @(v)' for x in choices),
		'Body : @FixNode[] = { Item* }',
		f'Message : @FixMessage = h: Header & b: Body & t: Trailer => @(new {name}(context.Source, h, b, t))', 'parse Message']
	write(f"Parser{name}.gram", "\n".join(message_grammar))
	hosts += [f'[Gram("Parser{name}.gram", PartSize = 1000, Portable = false)]', f'static partial class Parser{name}', "{", "\tstatic bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);", "}", ""]
	model += [f"/// <summary>FIX 4.4 {name}, MsgType {mt}.</summary>", f"public sealed class {name} : FixMessage", "{",
		f'\tinternal {name}(string source, FixNode[] header, FixNode[] body, FixNode[] trailer) : base(source, "{mt}", header, body, trailer) {{ }}']
	seen = set()
	for item in items:
		t = tag(item)
		f = fields[t]
		prop = f.attrib["name"]
		if prop in seen:
			continue
		seen.add(prop)
		if item[0] == "G":
			group_name = groups[item[1]].attrib['name']
			model.append(f"\tpublic IReadOnlyList<{group_name}Entry> {group_name} => GetTypedGroup<{group_name}Entry>({t});")
		elif field_type(f) in ("int", "Length", "NumInGroup", "SeqNum", "TagNum", "DayOfMonth", "float", "Qty", "Price", "PriceOffset", "Amt", "Percentage"):
			model.append(f"\tpublic FixNumber? {prop} => GetNumber({t});")
		else:
			model.append(f"\tpublic string? {prop} => GetText({t});")
	model += ["}", ""]
for name, items in [(g.attrib["name"] + "Entry", flatten(g)) for g in groups.values()] + [("StandardHeader", header_items), ("StandardTrailer", flatten(components[1025]))]:
	model += [f"/// <summary>FIX 4.4 {name} field scope.</summary>", f"public sealed class {name} : FixFieldSet", "{", f"\tinternal {name}(string source, FixNode[] fields) : base(source, fields) {{ }}"]
	seen = set()
	for item in items:
		t = tag(item)
		f = fields[t]
		prop = f.attrib["name"]
		if prop in seen: continue
		seen.add(prop)
		if item[0] == "G":
			group_name = groups[item[1]].attrib["name"]
			model.append(f"\tpublic IReadOnlyList<{group_name}Entry> {group_name} => GetTypedGroup<{group_name}Entry>({t});")
		elif field_type(f) in ("int", "Length", "NumInGroup", "SeqNum", "TagNum", "DayOfMonth", "float", "Qty", "Price", "PriceOffset", "Amt", "Percentage"):
			model.append(f"\tpublic FixNumber? {prop} => GetNumber({t});")
		else:
			model.append(f"\tpublic string? {prop} => GetText({t});")
	model += ["}", ""]
write("FixGrammar.gram", "\n".join(gram))
write("Messages.Generated.cs", "\n".join(model))
custom_needed = {"Text", "Digits", "Data", "Header", "HeaderRest", "MessageType", "Trailer", "Unknown", "UnknownText", "UnknownData"}
# Header group grammar is shared by custom messages too; retain exactly its closure.
needed = custom_needed
need(header_items + flatten(components[1025]))
data_fields = [("F", i) for i, f in fields.items() if f.attrib["type"] == "data" and i not in header_tags | trailer_tags]
need(data_fields)
custom = [line for line in gram if not line or line.startswith(("//", "@", "context")) or line.split(" ", 1)[0] in needed]
custom += ["Plain : @FixNode = t: Digits & when @(context.IsPlainBody(t.Start, t.Length)) & '=' & v: Text & '\\u0001' => @(new FixNode(context.TagAt(t.Start, t.Length), parserSpan.Start, v.Start, v.Length))",
	"Item : @FixNode = " + " | ".join(f"v: F{i} => @(v)" for _, i in data_fields) + " | v: UnknownData => @(v) | v: Plain => @(v)",
	"Body : @FixNode[] = { Item* }", "Message : @FixMessage = h: Header & b: Body & t: Trailer => @(new CustomFixMessage(context.Source, context.MessageType, h, b, t))", "parse Message"]
write("ParserCustom.gram", "\n".join(custom))
hosts += ['[Gram("ParserCustom.gram", PartSize = 1000, Portable = false)]', 'static partial class ParserCustom', "{", "\tstatic bool ReadData(ReadOnlySpan<char> input, ref int position) => FixGrammar.ReadData(input, ref position);", "}"]
write("Parsers.Generated.cs", "\n".join(hosts))
inventory = {
	"version": repo.attrib["version"],
	"counts": {"messages": len(messages), "fields": len(fields), "components": len(components), "groups": len(groups), "codeSets": len(codes)},
	"messages": [{"name": m.attrib["name"], "msgType": m.attrib["msgType"]} for m in messages],
	"lengthDataPairs": [{"lengthTag": int(f.attrib["lengthId"]), "dataTag": i} for i, f in fields.items() if "lengthId" in f.attrib],
}
write("Specification/inventory.json", json.dumps(inventory, indent="\t"))
print(inventory["counts"])


def entries(element):
	return ", ".join(f'new SchemaRef({int(x.attrib["id"])}, {str(x.attrib.get("presence") == "required").lower()}, { {"fieldRef": 0, "componentRef": 1, "groupRef": 2}[kind(x)]})' for x in refs(element))


schema = ["// <auto-generated />", "#nullable enable", "using System;", "namespace DotGram.Finance.Fix;", "static class FixSchema", "{"]
for label, values in [("C", components), ("G", groups)]:
	for i, x in values.items():
		schema.append(f'\tstatic readonly SchemaRef[] {label}{i} = {{ {entries(x)} }};')
for m in messages:
	schema.append(f'\tstatic readonly SchemaRef[] M{m.attrib["id"]} = {{ {entries(m.find("r:structure", NS))} }};')
schema += ["\tpublic static SchemaRef[] Component(int id) => id switch", "\t{"]
schema += [f"\t\t{i} => C{i}," for i in components]
schema += ['\t\t_ => throw new InvalidOperationException("Unknown component."),', "\t};", "\tpublic static SchemaRef[] Group(int id) => id switch", "\t{"]
schema += [f"\t\t{i} => G{i}," for i in groups]
schema += ['\t\t_ => throw new InvalidOperationException("Unknown group."),', "\t};", "\tpublic static SchemaRef[] Message(string type) => type switch", "\t{"]
schema += [f'\t\t"{m.attrib["msgType"]}" => M{m.attrib["id"]},' for m in messages]
schema += ["\t\t_ => Array.Empty<SchemaRef>(),", "\t};", "\tpublic static int Counter(int group) => group switch", "\t{"]
schema += [f'\t\t{i} => {g.find("r:numInGroup", NS).attrib["id"]},' for i, g in groups.items()]
schema += ["\t\t_ => 0,", "\t};", "\tpublic static int LengthTag(int dataTag) => dataTag switch", "\t{"]
schema += [f'\t\t{i} => {f.attrib["lengthId"]},' for i, f in fields.items() if "lengthId" in f.attrib]
schema += ["\t\t_ => 0,", "\t};", "\tpublic static int DataTag(int lengthTag) => lengthTag switch", "\t{"]
schema += [f'\t\t{f.attrib["lengthId"]} => {i},' for i, f in fields.items() if "lengthId" in f.attrib]
schema += ["\t\t_ => 0,", "\t};", "\tpublic static string? Type(int tag) => tag switch", "\t{"]
schema += [f'\t\t{i} => "{field_type(f)}",' for i, f in fields.items()]
schema += ["\t\t_ => null,", "\t};"]
for name, c in codes.items():
	values = ", ".join(json.dumps(x.attrib["value"]) for x in c.findall("r:code", NS))
	schema.append(f'\tstatic readonly string[] {name} = {{ {values} }};')
schema += ["\tpublic static string[]? Codes(int tag) => tag switch", "\t{"]
schema += [f'\t\t{i} => {f.attrib["type"]},' for i, f in fields.items() if f.attrib["type"] in codes]
schema += ["\t\t_ => null,", "\t};", "\tpublic static bool RequiresEncoding(int tag) => tag switch", "\t{"]
schema += [f'\t\t{i} => true,' for i, f in fields.items() if f.attrib["name"].startswith("Encoded") and f.attrib["type"] == "data"]
schema += ["\t\t_ => false,", "\t};", "}"]
write("Schema.Generated.cs", "\n".join(schema))

dispatch = ["// <auto-generated />", "#nullable enable", "using System;", "namespace DotGram.Finance.Fix;", "public static partial class Fix44", "{", "\tstatic bool Recognize(string input, FixContext context, out FixMessage? message, out int position, out string? reason)", "\t{", "\t\tmessage = null;", "\t\tposition = 0;", "\t\treason = null;", "\t\tswitch (context.MessageType)", "\t\t{"]
for m in messages:
	dispatch += [f'\t\t\tcase "{m.attrib["msgType"]}":', "\t\t\t{", f'\t\t\t\tvar result = Parser{m.attrib["name"]}.TryParseMessage(input, context);', "\t\t\t\tposition = (int)result.Position;", "\t\t\t\tif (result.IsSuccess) { message = result.Value; return true; }", "\t\t\t\treason = result.Error;", "\t\t\t\treturn false;", "\t\t\t}"]
dispatch += ["\t\t\tdefault:", "\t\t\t\tif (context.Mode == FixParseMode.Lenient)", "\t\t\t\t{", "\t\t\t\t\tvar result = ParserCustom.TryParseMessage(input, context);", "\t\t\t\t\tposition = (int)result.Position;", "\t\t\t\t\tif (result.IsSuccess) { message = result.Value; return true; }", "\t\t\t\t\treason = result.Error;", "\t\t\t\t\treturn false;", "\t\t\t\t}", '\t\t\t\treason = "Unknown FIX 4.4 message type.";', "\t\t\t\treturn false;", "\t\t}", "\t}", "}"]
write("Dispatch.Generated.cs", "\n".join(dispatch))



# Runtime factories accompany the schema; group structure is interpreted once by
# the shared semantic assembler instead of compiled into each message parser.
factories = ["// <auto-generated />", "#nullable enable", "using System;", "using System.Collections.Generic;", "", "namespace DotGram.Finance.Fix;", "", "static class FixFactories", "{"]
factories += ["\tpublic static FixMessage Message(string type, string source, FixNode[] header, FixNode[] body, FixNode[] trailer) => type switch", "\t{"]
for m in messages:
	factories.append(f'\t\t"{m.attrib["msgType"]}" => new {m.attrib["name"]}(source, header, body, trailer),')
factories += ["\t\t_ => new CustomFixMessage(source, type, header, body, trailer),", "\t};", "", "\tpublic static IReadOnlyList<FixFieldSet> Group(int id, string source, List<FixNode[]> entries)", "\t{", "\t\tswitch (id)", "\t\t{"]
for i, g in groups.items():
	name = g.attrib["name"] + "Entry"
	factories += [f"\t\t\tcase {i}:", "\t\t\t{", f"\t\t\t\tvar result = new {name}[entries.Count];", f"\t\t\t\tfor (var n = 0; n < result.Length; n++) result[n] = new {name}(source, entries[n]);", "\t\t\t\treturn Array.AsReadOnly(result);", "\t\t\t}"]
factories += ['\t\t\tdefault: throw new InvalidOperationException("Unknown FIX group.");', "\t\t}", "\t}", "}"]
write("Factories.Generated.cs", "\n".join(factories))


def sample_field(i):
	f = fields[i]
	t = field_type(f)
	if f.attrib["type"] in codes:
		return codes[f.attrib["type"]].find("r:code", NS).attrib["value"]
	return {"String": "X", "char": "X", "Boolean": "N", "Currency": "USD", "Country": "US", "Exchange": "XNAS", "MonthYear": "202609", "UTCTimestamp": "20260915-12:00:00", "UTCTimeOnly": "12:00:00", "UTCDateOnly": "20260915", "LocalMktDate": "20260915", "data": "X", "MultipleValueString": "X"}.get(t, "1")


def sample_structure(element, force_first=False, required_component=False, full=False):
	result = []
	children = refs(element)
	for index, x in enumerate(children):
		i = int(x.attrib["id"])
		if not full and x.attrib.get("presence") != "required" and not (force_first and index == 0):
			continue
		if kind(x) == "componentRef":
			if i not in (1024, 1025):
				result.extend(sample_structure(components[i], required_component=True, full=full))
		elif kind(x) == "groupRef":
			result.append((tag(("G", i)), "1"))
			result.extend(sample_structure(groups[i], force_first=True, full=full))
		else:
			result.append((i, sample_field(i)))
	if required_component and not result:
		return sample_structure(element, force_first=True)
	return result


fixtures = []
for m, full in [(m, full) for m in messages for full in (False, True)]:
	mt = m.attrib["msgType"]
	body = f"35={mt}\x0149=SENDER\x0156=TARGET\x0134=1\x0152=20260915-12:00:00\x01"
	if full:
		body = f"35={mt}\x01" + "".join(f"{i}={v}\x01" for i, v in sample_structure(components[1024], full=True) if i not in (8, 9, 35))
	body += "".join(f"{i}={v}\x01" for i, v in sample_structure(m.find("r:structure", NS), full=full))
	if full: body += "93=1\x0189=X\x01"
	wire = f"8=FIX.4.4\x019={len(body)}\x01{body}"
	wire += f"10={sum(map(ord, wire)) % 256:03}\x01"
	fixtures.append({"name": m.attrib["name"], "wire": wire})
(ROOT / "tests/DotGram.Finance.Tests/Fixtures.json").write_bytes((json.dumps(fixtures, indent="\t") + "\n").replace("\n", "\r\n").encode())
